/**
 * Framework Backend Tests
 *
 * `compiler/backends/framework.ts` (572 LOC) generates `M()` framework calls
 * from Mirror AST. Was 0.39% covered.
 */

import { describe, it, expect } from 'vitest'
import { parse } from '../../compiler/parser'
import { generateFramework } from '../../compiler/backends/framework'

function fw(src: string): string {
  return generateFramework(parse(src))
}

describe('Framework Backend — Header & Boilerplate', () => {
  it('emits header comment + import + mount export', () => {
    const out = fw('Frame')
    expect(out).toContain('Generated by Mirror Compiler (Framework Backend)')
    expect(out).toContain("import { M } from 'mirror-runtime'")
    expect(out).toContain('export function mount(container)')
    expect(out).toContain('return M.render(ui, container)')
  })

  it('empty program → M("Box") fallback', () => {
    const out = fw('')
    expect(out).toContain("export const ui = M('Box')")
  })
})

describe('Framework Backend — Token emission', () => {
  it('tokens are exported as a const object', () => {
    const out = fw(`primary.bg: #2271C1
danger.bg: #ef4444

Frame`)
    expect(out).toContain('export const tokens = {')
    expect(out).toContain('primary')
  })

  it('no tokens block when none defined', () => {
    const out = fw(`Frame`)
    expect(out).not.toContain('export const tokens')
  })
})

describe('Framework Backend — Primitive → Type mapping', () => {
  it.each([
    ['Frame', 'Frame'],
    ['Text "Hi"', 'Text'],
    ['Button "OK"', 'Button'],
    ['Input placeholder "X"', 'Input'],
    ['Image src "/x.jpg"', 'Image'],
    ['Link "Home", href "/"', 'Link'],
  ])("%s → contains M('%s')", (src, type) => {
    const out = fw(src)
    expect(out).toContain(`M('${type}'`)
  })
})

describe('Framework Backend — Content + Props + Children', () => {
  it('Text "Hello" → M("Text", "Hello")', () => {
    const out = fw(`Text "Hello"`)
    expect(out).toMatch(/M\('Text', 'Hello'/)
  })

  it('Frame with single text child', () => {
    const out = fw(`Frame
  Text "Inner"`)
    expect(out).toContain("M('Frame'")
    expect(out).toContain('Inner')
  })

  it('Frame with two children produces array', () => {
    const out = fw(`Frame
  Text "A"
  Text "B"`)
    expect(out).toContain('A')
    expect(out).toContain('B')
    // Children expressed as an array
    expect(out).toMatch(/\[[\s\S]*M\('Text'/)
  })

  it('multiple root nodes wrap in Box', () => {
    const out = fw(`Text "A"
Text "B"`)
    expect(out).toContain("export const ui = M('Box', [")
  })
})

describe('Framework Backend — Properties', () => {
  it('numeric props get serialized', () => {
    const out = fw(`Frame w 200, h 100`)
    // Either "200" appears as value or as serialized prop
    expect(out).toMatch(/200/)
    expect(out).toMatch(/100/)
  })

  it('color props get serialized', () => {
    const out = fw(`Frame bg #2271C1`)
    expect(out.toLowerCase()).toContain('#2271c1')
  })
})

describe('Framework Backend — Each loops', () => {
  it('each generates M.each call', () => {
    const out = fw(`tasks:
  t1:
    title: "A"

each task in $tasks
  Text task.title`)
    expect(out).toContain('M.each')
    expect(out).toContain("'task'")
    expect(out).toContain("'tasks'")
  })

  it('each with where filter passes filter argument', () => {
    const out = fw(`tasks:
  t1:
    done: true
    title: "A"

each task in $tasks where task.done
  Text task.title`)
    expect(out).toContain('M.each')
  })
})

describe('Framework Backend — Conditionals', () => {
  it('if-block generates M.if call', () => {
    const out = fw(`flag: true

if flag
  Text "Yes"`)
    expect(out).toContain('M.if')
    expect(out).toContain('flag')
  })

  it('if/else generates M.if with two branches', () => {
    const out = fw(`flag: true

if flag
  Text "Yes"
else
  Text "No"`)
    expect(out).toContain('M.if')
    expect(out).toContain('Yes')
    expect(out).toContain('No')
  })
})

describe('Framework Backend — Reverse-translation hint', () => {
  it('emits the toMirror() comment at the bottom', () => {
    const out = fw(`Frame`)
    expect(out).toContain('M.toMirror(ui)')
  })
})

describe('Framework Backend — Determinism', () => {
  it('same input produces identical output', () => {
    const src = `Frame gap 8
  Text "A"
  Text "B"`
    expect(fw(src)).toBe(fw(src))
  })
})

describe('Framework Backend — More edge paths', () => {
  it('px-value parsing in props (200px → number)', () => {
    const out = fw(`Frame w 200`)
    // Either as 200 or '200px' or '200' depending on how IR represents it
    expect(out).toMatch(/200/)
  })

  it('component with state-block survives compilation', () => {
    const out = fw(`Btn: pad 12, bg #333, toggle()
  on:
    bg #2271C1

Btn "Click"`)
    expect(out).toContain('mirror-runtime')
    expect(out).toContain('Click')
  })

  it('image with src is rendered', () => {
    const out = fw(`Image src "/foo.jpg", w 200`)
    expect(out).toContain("'Image'")
    expect(out).toContain('/foo.jpg')
  })

  it('icon with custom size + color', () => {
    const out = fw(`Icon "check", is 24, ic #10b981`)
    expect(out).toContain("'Icon'")
    expect(out).toContain('check')
  })

  it('Frame with many properties (large props object)', () => {
    const out = fw(`Frame w 200, h 100, bg #333, col white, pad 12, gap 8, rad 6, bor 1, boc #444`)
    expect(out).toContain("'Frame'")
    expect(out).toMatch(/width|w:|200/)
  })

  it('multiple distinct token definitions all emitted', () => {
    const out = fw(`primary.bg: #2271C1
primary.col: white
danger.bg: #ef4444
spacing.gap: 12`)
    expect(out).toContain('primary')
    expect(out).toContain('danger')
    expect(out).toContain('spacing')
  })

  it('nested each (each-in-each) compiles', () => {
    const out = fw(`groups:
  g1:
    items:
      i1:
        title: "A"

each group in $groups
  Frame
    each item in group.items
      Text item.title`)
    expect(out).toContain('M.each')
  })
})
