/**
 * DOM Backend Tests
 */

import { describe, it, expect } from 'vitest'
import { parse } from '../../compiler/parser/parser'
import { generateDOM } from '../../compiler/backends/dom'

describe('DOM Backend: Basic Generation', () => {
  it('generates valid JavaScript for simple component', () => {
    const ast = parse(`
Card as frame:
  pad 16
  bg #1a1a23

Card
`)
    const js = generateDOM(ast)
    
    expect(js).toContain('// Generated by Mirror Compiler')
    expect(js).toContain('export function createUI')
    expect(js).toContain("document.createElement('div')")
  })

  it('generates styles from properties', () => {
    const ast = parse(`
Button as button:
  pad 12
  bg #3B82F6
  rad 8

Button "Click me"
`)
    const js = generateDOM(ast)
    
    expect(js).toContain("'padding': '12px'")
    expect(js).toContain("'background': '#3B82F6'")
    expect(js).toContain("'border-radius': '8px'")
  })

  it('generates named instance accessors', () => {
    const ast = parse(`
Button as button:
  pad 8

Button named saveBtn "Save"
`)
    const js = generateDOM(ast)
    
    expect(js).toContain("_elements['saveBtn']")
    expect(js).toContain('get saveBtn()')
  })

  it('generates event listeners', () => {
    const ast = parse(`
Button as button:
  onclick toggle()

Button "Toggle"
`)
    const js = generateDOM(ast)

    expect(js).toContain("addEventListener('click'")
  })

  it('generates tokens', () => {
    const ast = parse(`
primary: color = #3B82F6
spacing: size = 16
`)
    const js = generateDOM(ast)

    // Tokens are now stored in __mirrorData and aliased to tokens
    expect(js).toContain('const __mirrorData = window.__mirrorData = {')
    expect(js).toContain('"primary": "#3B82F6"')
    expect(js).toContain('"spacing":')
  })

  it('generates hover state as CSS', () => {
    const ast = parse(`
Card as frame:
  pad 16
  bg #333
  hover:
    bg #555

Card
`)
    const js = generateDOM(ast)

    // Hover is now CSS, not _stateStyles
    expect(js).toContain(':hover {')
    expect(js).toContain('background: #555')
  })

  it('generates children', () => {
    const ast = parse(`
Card as frame:
  pad 16

Text as text:

Card
  Text "Hello"
`)
    const js = generateDOM(ast)
    
    expect(js).toContain('appendChild')
  })
})

describe('DOM Backend: Layout Properties', () => {
  it('converts gap to CSS gap', () => {
    const ast = parse(`
Row as frame:
  gap 16

Row
`)
    const js = generateDOM(ast)

    expect(js).toContain("'gap': '16px'")
  })

  it('converts padding to CSS padding', () => {
    const ast = parse(`
Box as frame:
  pad 16

Box
`)
    const js = generateDOM(ast)

    expect(js).toContain("'padding': '16px'")
  })

  it('converts width to CSS width', () => {
    const ast = parse(`
Fixed as frame:
  width 200

Fixed
`)
    const js = generateDOM(ast)

    expect(js).toContain("'width': '200px'")
  })

  it('converts horizontal to flexbox row', () => {
    const ast = parse(`
Row as frame:
  horizontal

Row
`)
    const js = generateDOM(ast)

    expect(js).toContain("'display': 'flex'")
    expect(js).toContain("'flex-direction': 'row'")
  })

  it('converts center to flexbox centering', () => {
    const ast = parse(`
Center as frame:
  center

Center
`)
    const js = generateDOM(ast)

    expect(js).toContain("'justify-content': 'center'")
    expect(js).toContain("'align-items': 'center'")
  })

  it('converts spread to space-between', () => {
    const ast = parse(`
Spread as frame:
  spread

Spread
`)
    const js = generateDOM(ast)

    expect(js).toContain("'justify-content': 'space-between'")
  })
})

describe('DOM Backend: Token References', () => {
  it('resolves token references to CSS variables', () => {
    const ast = parse(`
primary: color = #3B82F6

Button as button:
  bg primary

Button
`)
    const js = generateDOM(ast)

    expect(js).toContain("'background': 'var(--primary)'")
  })

  it('leaves non-token values as-is', () => {
    const ast = parse(`
Button as button:
  bg #FF0000

Button
`)
    const js = generateDOM(ast)

    expect(js).toContain("'background': '#FF0000'")
  })
})

describe('DOM Backend: Design Tokens', () => {
  it('generates tokens object from token definitions', () => {
    const ast = parse(`
primary: color = #3B82F6
surface: color = #1a1a23

Card as frame:
Card
`)
    const js = generateDOM(ast)

    // Tokens are now stored in __mirrorData
    expect(js).toContain('const __mirrorData = window.__mirrorData = {')
    expect(js).toContain('"primary": "#3B82F6"')
    expect(js).toContain('"surface": "#1a1a23"')
  })

  it('includes box-sizing reset', () => {
    const ast = parse(`
primary: color = #FFF
Card as frame:
Card
`)
    const js = generateDOM(ast)

    expect(js).toContain('box-sizing: border-box')
  })
})

describe('DOM Backend: System States as CSS', () => {
  it('generates CSS :hover pseudo-class', () => {
    const ast = parse(`
Button as button:
  bg #333
  hover:
    bg #555

Button
`)
    const js = generateDOM(ast)

    expect(js).toContain(':hover {')
    expect(js).toContain('background: #555')
  })

  it('generates CSS :focus pseudo-class', () => {
    const ast = parse(`
Input as input:
  bor 1 #333
  focus:
    bor 1 #3B82F6

Input
`)
    const js = generateDOM(ast)

    expect(js).toContain(':focus {')
  })

  it('adds data-mirror-id attribute', () => {
    const ast = parse(`
Card as frame:
Card
`)
    const js = generateDOM(ast)

    expect(js).toContain("dataset.mirrorId = 'node-")
  })

  it('keeps behavior states in _stateStyles', () => {
    const ast = parse(`
Item as frame:
  bg #333
  selected:
    bg #3B82F6

Item
`)
    const js = generateDOM(ast)

    expect(js).toContain("'selected':")
    expect(js).toContain("_stateStyles")
  })
})

describe('DOM Backend: Runtime', () => {
  it('includes runtime helpers', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('const _runtime = {')
    expect(js).toContain('wrap(el)')
    expect(js).toContain('toggle(el)')
    expect(js).toContain('show(el)')
    expect(js).toContain('hide(el)')
    expect(js).toContain('select(el)')
    expect(js).toContain('highlight(el)')
  })

  it('includes state management API', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('setState(key, value)')
    expect(js).toContain('getState(key)')
  })
})

describe('DOM Backend: Each Loop', () => {
  it('generates each loop container', () => {
    const ast = parse(`
Card as frame:
  pad 16

each $task in $tasks
  Card $task.title
`)
    const js = generateDOM(ast)

    expect(js).toContain('// Each loop: task in tasks')
    expect(js).toContain('data-each-container')
    expect(js).toContain('_eachConfig')
    expect(js).toContain("itemVar: 'task'")
    expect(js).toContain("collection: 'tasks'")
  })

  it('generates renderItem function', () => {
    const ast = parse(`
Card as frame:

each $task in $tasks
  Card $task.title
`)
    const js = generateDOM(ast)

    expect(js).toContain('renderItem: (task, index) => {')
    expect(js).toContain('dataset.eachItem')
  })

  it('generates initial render with data', () => {
    const ast = parse(`
Item as frame:

each $item in $items
  Item $item.name
`)
    const js = generateDOM(ast)

    // Each loop now uses $get for data access
    expect(js).toContain('$get')
    expect(js).toContain('items')
  })

  it('handles filter in each loop', () => {
    const ast = parse(`
Task as frame:

each $task in $tasks where $task.done == false
  Task $task.title
`)
    const js = generateDOM(ast)

    expect(js).toContain('filterFn:')  // Function instead of string to avoid eval()
    expect(js).toContain('tasksFiltered')
  })

  it('includes update method for reactive loops', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('update()')
    expect(js).toContain("querySelectorAll('[data-each-container]')")
    expect(js).toContain('renderItem')
  })
})

describe('DOM Backend: Conditionals', () => {
  it('generates conditional container', () => {
    const ast = parse(`
Button as button:

if (loggedIn)
  Button "Logout"
`)
    const js = generateDOM(ast)

    expect(js).toContain('// Conditional')
    expect(js).toContain('data-conditional-id')
    expect(js).toContain('_conditionalConfig')
  })

  it('generates condition function', () => {
    const ast = parse(`
Avatar as frame:

if (isAdmin)
  Avatar
`)
    const js = generateDOM(ast)

    // Variables in conditions are wrapped with $get() for data context lookup
    expect(js).toContain('condition: () => ($get("isAdmin"))')
  })

  it('generates renderThen function', () => {
    const ast = parse(`
Panel as frame:

if (showPanel)
  Panel
`)
    const js = generateDOM(ast)

    expect(js).toContain('renderThen: () => {')
    expect(js).toContain('createDocumentFragment')
  })

  it('generates renderElse function for if-else', () => {
    const ast = parse(`
Avatar as frame:
LoginButton as button:

if (loggedIn)
  Avatar
else
  LoginButton "Login"
`)
    const js = generateDOM(ast)

    expect(js).toContain('renderThen: () => {')
    expect(js).toContain('renderElse: () => {')
  })

  it('generates initial conditional render', () => {
    const ast = parse(`
Content as frame:

if (hasData)
  Content
`)
    const js = generateDOM(ast)

    expect(js).toContain('// Initial conditional render')
    // Variables in conditions are wrapped with $get() for data context lookup
    expect(js).toContain('if (($get("hasData"))) {')
    expect(js).toContain('renderThen()')
  })

  it('includes conditionals in update method', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain("querySelectorAll('[data-conditional-id]')")
    expect(js).toContain('_conditionalConfig')
    expect(js).toContain('condition()')
  })

  it('handles complex condition expressions', () => {
    const ast = parse(`
Panel as frame:

if (user.isAdmin && hasPermission)
  Panel
`)
    const js = generateDOM(ast)

    // Variables in conditions are wrapped with $get() for data context lookup
    expect(js).toContain('condition: () => ($get("user.isAdmin") && $get("hasPermission"))')
  })
})

describe('DOM Backend: Slots', () => {
  it('renders component with slot definitions', () => {
    const ast = parse(`
Card as frame:
  pad 16
  Title:
  Content:

Card
  Title "Welcome"
  Content "Get started"
`)
    const js = generateDOM(ast)

    // Should render the Title and Content as children
    expect(js).toContain("'padding': '16px'")
    expect(js).toContain('appendChild')
  })

  it('slot fillers replace slot defaults', () => {
    const ast = parse(`
Header as frame:
  Label:

Label as text:
  col #999

Header
  Label "Custom Title"
`)
    const js = generateDOM(ast)

    // The Label slot should be filled with "Custom Title"
    expect(js).toContain('Custom Title')
  })

  it('unfilled slots use default content', () => {
    const ast = parse(`
Panel as frame:
  Title "Default"

Panel
`)
    const js = generateDOM(ast)

    // Should still render the default "Default" content
    expect(js).toContain('Default')
  })

  it('handles multiple children filling same-name slots', () => {
    const ast = parse(`
List as frame:
  Item:

Item as frame:
  pad 8

List
  Item "First"
  Item "Second"
`)
    const js = generateDOM(ast)

    expect(js).toContain('First')
    expect(js).toContain('Second')
  })
})

describe('DOM Backend: Click Outside Event', () => {
  it('generates document click listener for onclick-outside', () => {
    const ast = parse(`
Dropdown as frame:
  onclick-outside close

Dropdown
`)
    const js = generateDOM(ast)

    expect(js).toContain('Click outside handler')
    expect(js).toContain("document.addEventListener('click'")
    expect(js).toContain('.contains(e.target)')
    expect(js).toContain('_clickOutsideHandler')
  })

  it('onclick-outside executes actions when clicked outside', () => {
    const ast = parse(`
Panel as frame:
  onclick-outside hide

Panel
`)
    const js = generateDOM(ast)

    expect(js).toContain('if (!node')
    expect(js).toContain('.contains(e.target))')
  })
})


describe('DOM Backend: Runtime Helpers', () => {
  it('generates destroy method for cleanup', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('destroy(el)')
    expect(js).toContain("removeEventListener('click', el._clickOutsideHandler)")
    expect(js).toContain('delete el._clickOutsideHandler')
  })

  it('generates updateVisibility method', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('updateVisibility(el)')
    expect(js).toContain('_visibleWhen')
    expect(js).toContain("visible ? '' : 'none'")
  })

  it('toggle method handles open/closed states', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('toggle(el)')
    expect(js).toContain("currentState === 'closed'")
    expect(js).toContain("currentState === 'open'")
    expect(js).toContain("newState = currentState === 'closed' ? 'open' : 'closed'")
  })

  it('toggle method handles collapsed/expanded states', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain("currentState === 'collapsed'")
    expect(js).toContain("currentState === 'expanded'")
  })

  it('setState calls updateVisibility', () => {
    const ast = parse(`Card as frame:`)
    const js = generateDOM(ast)

    expect(js).toContain('setState(el, stateName)')
    expect(js).toContain('this.updateVisibility(el)')
  })
})
