/**
 * Hospital Dashboard Test
 * Quick test to verify the dashboard.mirror file compiles correctly
 */

import { describe, it, expect } from 'vitest'
import { readFileSync, writeFileSync } from 'fs'
import { join } from 'path'
import { parse } from '../../compiler/parser/parser'
import { generateDOM } from '../../compiler/backends/dom'

describe('Hospital Dashboard', () => {
  it('parses the dashboard.mirror file', () => {
    const code = readFileSync(
      join(__dirname, '../../examples/hospital-dashboard/dashboard.mirror'),
      'utf-8'
    )

    const ast = parse(code)

    // Check that we have components and instances
    expect(ast.components.length).toBeGreaterThan(0)
    expect(ast.instances.length).toBeGreaterThan(0)

    console.log('Components:', ast.components.length)
    console.log('Instances:', ast.instances.length)
    console.log('Tokens:', ast.tokens?.length || 0)
    console.log('Data:', ast.data?.length || 0)
  })

  it('compiles the dashboard.mirror file to DOM', () => {
    const code = readFileSync(
      join(__dirname, '../../examples/hospital-dashboard/dashboard.mirror'),
      'utf-8'
    )

    const ast = parse(code)
    const jsOutput = generateDOM(ast)

    expect(jsOutput).toContain('// Generated by Mirror Compiler')
    expect(jsOutput).toContain('createUI')

    console.log('Output length:', jsOutput.length, 'characters')

    // Write the compiled output to a file for browser testing
    const htmlOutput = `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StationView – Mirror Dashboard</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  <link rel="stylesheet" href="../../assets/mirror-defaults.css">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background: #0a0a0f;
      min-height: 100vh;
    }
    #app { width: 100%; min-height: 100vh; }
  </style>
</head>
<body>
  <div id="app"></div>
  <script type="module">
${jsOutput}

// Initialize the UI
const container = document.getElementById('app');
const { root } = createUI();
container.appendChild(root);
  </script>
</body>
</html>`

    writeFileSync(
      join(__dirname, '../../examples/hospital-dashboard/dashboard-compiled.html'),
      htmlOutput
    )

    console.log('Written compiled HTML to examples/hospital-dashboard/dashboard-compiled.html')
  })
})
