/**
 * Mirror DOM Backend
 *
 * Generates pure JavaScript DOM manipulation code.
 * Flagship backend - no framework dependencies.
 */

import type { AST, JavaScriptBlock } from '../parser/ast'
import { toIR } from '../ir'
import type { IR, IRNode, IRStyle, IREvent, IRAction, IREach, IRConditional } from '../ir/types'

/**
 * Generate DOM manipulation JavaScript code from Mirror AST
 *
 * Output: ES module with factory function
 *
 * @example
 * ```javascript
 * import { createUI } from "./app.mirror.js"
 *
 * const ui = createUI()
 * ui.header.text = "Hello"
 * ui.saveBtn.onclick = () => { ... }
 * document.body.appendChild(ui.root)
 * ```
 */
export function generateDOM(ast: AST): string {
  const ir = toIR(ast)
  const generator = new DOMGenerator(ir, ast.javascript)
  return generator.generate()
}

class DOMGenerator {
  private ir: IR
  private javascript?: JavaScriptBlock
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR, javascript?: JavaScriptBlock) {
    this.ir = ir
    this.javascript = javascript
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitCreateUI()
    this.emitRuntime()

    // If there's JavaScript, emit initialization with named instance exposure
    if (this.javascript) {
      this.emitInitialization()
    }

    return this.lines.join('\n')
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitRaw(line: string): void {
    this.lines.push(line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (DOM Backend)')
    this.emit('// Do not edit manually')
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('const tokens = {')
    this.indent++
    for (const token of this.ir.tokens) {
      const value = typeof token.value === 'string' ? `"${token.value}"` : token.value
      this.emit(`"${token.name}": ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitStyles(): void {
    this.emit('// Inject CSS styles')
    this.emit("const _style = document.createElement('style')")
    this.emit('_style.textContent = `')

    // CSS Variables
    if (this.ir.tokens.length > 0) {
      this.emit(':root {')
      this.indent++
      for (const token of this.ir.tokens) {
        const value = token.value
        this.emit(`--${token.name}: ${value};`)
      }
      this.indent--
      this.emit('}')
      this.emit('')
    }

    // Base reset
    this.emit('.mirror-root * {')
    this.emit('  box-sizing: border-box;')
    this.emit('}')

    // Emit CSS for system states (hover, focus, active, disabled)
    this.emitSystemStateCSS()

    this.emit('`')
    this.emit('document.head.appendChild(_style)')
    this.emit('')
  }

  private emitSystemStateCSS(): void {
    // Collect all system states from nodes
    const systemStates = ['hover', 'focus', 'active', 'disabled']

    for (const node of this.ir.nodes) {
      this.emitNodeStateCSS(node, systemStates)
    }
  }

  private emitNodeStateCSS(node: IRNode, systemStates: string[]): void {
    const stateStyles = node.styles.filter(s => s.state && systemStates.includes(s.state))

    if (stateStyles.length > 0) {
      const byState = this.groupByState(stateStyles)

      for (const [state, styles] of Object.entries(byState)) {
        const pseudoClass = state === 'disabled' ? '[disabled]' : `:${state}`
        this.emit('')
        this.emit(`[data-mirror-id="${node.id}"]${pseudoClass} {`)
        this.indent++
        for (const style of styles) {
          this.emit(`${style.property}: ${style.value} !important;`)
        }
        this.indent--
        this.emit('}')
      }
    }

    // Recurse into children
    for (const child of node.children) {
      this.emitNodeStateCSS(child, systemStates)
    }
  }

  private emitCreateUI(): void {
    this.emit('export function createUI(data = {}) {')
    this.indent++

    this.emit('const _elements = {}')
    this.emit('const _state = { ...data }')
    this.emit('const _listeners = new Map()')
    this.emit('')

    // Generate root container
    this.emit('// Root container')
    this.emit("const _root = document.createElement('div')")
    this.emit("_root.className = 'mirror-root'")
    this.emit('')

    // Inject CSS (variables + system state styles)
    this.emitStyles()

    // Generate each node
    for (const node of this.ir.nodes) {
      this.emitNode(node, '_root')
    }

    this.emit('')
    this.emitPublicAPI()

    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitNode(node: IRNode, parentVar: string): void {
    // Handle each loop nodes
    if (node.each) {
      this.emitEachLoop(node.each, parentVar)
      return
    }

    // Handle conditional nodes
    if (node.conditional) {
      this.emitConditional(node.conditional, parentVar)
      return
    }

    const varName = this.sanitizeVarName(node.id)

    this.emit(`// ${node.name || node.tag}`)
    this.emit(`const ${varName} = document.createElement('${node.tag}')`)
    this.emit(`_elements['${node.id}'] = ${varName}`)
    this.emit(`${varName}.dataset.mirrorId = '${node.id}'`)

    // Instance name for external access
    if (node.instanceName) {
      this.emit(`_elements['${node.instanceName}'] = ${varName}`)
    }

    // Detect if this is an icon element (based on primitive type)
    const isIcon = node.primitive === 'icon'
    let iconName: string | null = null

    // Set HTML properties
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(prop.value)}"` : prop.value
        // For icons, store the name for loading instead of setting textContent
        if (isIcon && typeof prop.value === 'string') {
          iconName = prop.value
        } else {
          this.emit(`${varName}.textContent = ${value}`)
        }
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(String(prop.value))}"` : prop.value
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Load icon from CDN if this is an icon element
    if (isIcon && iconName) {
      this.emit(`// Load Lucide icon`)
      this.emit(`_runtime.loadIcon(${varName}, "${this.escapeString(iconName)}")`)
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        this.emit(`'${style.property}': '${style.value}',`)
      }
      this.indent--
      this.emit('})')
    }

    // Store state styles for runtime (excluding CSS-handled system states)
    const cssStates = new Set(['hover', 'focus', 'active', 'disabled'])
    const behaviorStyles = node.styles.filter(s => s.state && !cssStates.has(s.state))
    if (behaviorStyles.length > 0) {
      this.emit(`${varName}._stateStyles = {`)
      this.indent++
      const byState = this.groupByState(behaviorStyles)
      for (const [state, styles] of Object.entries(byState)) {
        this.emit(`'${state}': {`)
        this.indent++
        for (const style of styles) {
          this.emit(`'${style.property}': '${style.value}',`)
        }
        this.indent--
        this.emit('},')
      }
      this.indent--
      this.emit('}')
    }

    // Initial state
    if (node.initialState) {
      this.emit(`${varName}.dataset.state = '${node.initialState}'`)
      this.emit(`${varName}._initialState = '${node.initialState}'`)
    }

    // Visible when state condition
    if (node.visibleWhen) {
      this.emit(`${varName}._visibleWhen = '${node.visibleWhen}'`)
      this.emit(`// Initially hidden until parent state matches`)
      this.emit(`${varName}.style.display = 'none'`)
    }

    // Selection binding
    if (node.selection) {
      const selectionVar = node.selection.startsWith('$') ? node.selection.slice(1) : node.selection
      this.emit(`${varName}._selectionBinding = '${selectionVar}'`)
    }

    // Component name (for navigation targets)
    if (node.name) {
      this.emit(`${varName}.dataset.component = '${node.name}'`)
    }

    // Route (for navigation)
    if (node.route) {
      this.emit(`${varName}.dataset.route = '${node.route}'`)
    }

    // Add event listeners
    // Check if there are keyboard events and make element focusable
    const hasKeyboardEvents = node.events.some(e => e.key || e.name === 'keydown' || e.name === 'keyup')
    if (hasKeyboardEvents) {
      this.emit(`${varName}.setAttribute('tabindex', '0')`)
    }
    for (const event of node.events) {
      this.emitEventListener(varName, event)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitNode(child, varName)
    }

    // Append to parent
    this.emit(`${parentVar}.appendChild(${varName})`)
    this.emit('')
  }

  private emitEachLoop(each: IREach, parentVar: string): void {
    const containerId = this.sanitizeVarName(each.id)
    // Strip $ prefix for valid JavaScript variable names
    const itemVar = each.itemVar.startsWith('$') ? each.itemVar.slice(1) : each.itemVar
    const collection = each.collection.startsWith('$') ? each.collection.slice(1) : each.collection

    this.emit(`// Each loop: ${itemVar} in ${collection}`)
    this.emit(`const ${containerId}_container = document.createElement('div')`)
    this.emit(`${containerId}_container.dataset.eachContainer = '${each.id}'`)
    this.emit('')

    // Store template factory for runtime updates
    this.emit(`_elements['${each.id}'] = ${containerId}_container`)
    this.emit(`${containerId}_container._eachConfig = {`)
    this.indent++
    this.emit(`itemVar: '${itemVar}',`)
    this.emit(`collection: '${collection}',`)
    if (each.filter) {
      this.emit(`filter: ${JSON.stringify(each.filter)},`)
    }
    this.emit(`renderItem: (${itemVar}, index) => {`)
    this.indent++

    // Create a container for each item
    this.emit(`const itemContainer = document.createElement('div')`)
    this.emit(`itemContainer.dataset.eachItem = index`)

    // Render template nodes
    for (const templateNode of each.template) {
      this.emitEachTemplateNode(templateNode, 'itemContainer', itemVar)
    }

    this.emit(`return itemContainer`)
    this.indent--
    this.emit('},')
    this.indent--
    this.emit('}')
    this.emit('')

    // Initial render with data
    this.emit(`// Initial render`)
    this.emit(`const ${collection}Data = data['${collection}'] || []`)
    if (each.filter) {
      this.emit(`const ${collection}Filtered = ${collection}Data.filter(${itemVar} => ${each.filter})`)
      this.emit(`${collection}Filtered.forEach((${itemVar}, index) => {`)
    } else {
      this.emit(`${collection}Data.forEach((${itemVar}, index) => {`)
    }
    this.indent++
    this.emit(`${containerId}_container.appendChild(${containerId}_container._eachConfig.renderItem(${itemVar}, index))`)
    this.indent--
    this.emit('})')
    this.emit('')

    this.emit(`${parentVar}.appendChild(${containerId}_container)`)
    this.emit('')
  }

  private emitConditional(cond: IRConditional, parentVar: string): void {
    const containerId = this.sanitizeVarName(cond.id)

    this.emit(`// Conditional`)
    this.emit(`const ${containerId}_container = document.createElement('div')`)
    this.emit(`${containerId}_container.dataset.conditionalId = '${cond.id}'`)
    this.emit(`_elements['${cond.id}'] = ${containerId}_container`)
    this.emit('')

    // Store conditional config for reactive updates
    this.emit(`${containerId}_container._conditionalConfig = {`)
    this.indent++
    this.emit(`condition: () => ${cond.condition},`)
    this.emit(`renderThen: () => {`)
    this.indent++
    this.emit(`const fragment = document.createDocumentFragment()`)
    for (const node of cond.then) {
      this.emitConditionalTemplateNode(node, 'fragment')
    }
    this.emit(`return fragment`)
    this.indent--
    this.emit(`},`)
    if (cond.else && cond.else.length > 0) {
      this.emit(`renderElse: () => {`)
      this.indent++
      this.emit(`const fragment = document.createDocumentFragment()`)
      for (const node of cond.else) {
        this.emitConditionalTemplateNode(node, 'fragment')
      }
      this.emit(`return fragment`)
      this.indent--
      this.emit(`},`)
    }
    this.indent--
    this.emit(`}`)
    this.emit('')

    // Initial render based on condition
    this.emit(`// Initial conditional render`)
    this.emit(`if (${cond.condition}) {`)
    this.indent++
    this.emit(`${containerId}_container.appendChild(${containerId}_container._conditionalConfig.renderThen())`)
    this.indent--
    if (cond.else && cond.else.length > 0) {
      this.emit(`} else {`)
      this.indent++
      this.emit(`${containerId}_container.appendChild(${containerId}_container._conditionalConfig.renderElse())`)
      this.indent--
    }
    this.emit(`}`)
    this.emit('')

    this.emit(`${parentVar}.appendChild(${containerId}_container)`)
    this.emit('')
  }

  private emitConditionalTemplateNode(node: IRNode, parentVar: string): void {
    // Handle nested conditionals
    if (node.conditional) {
      const nestedId = this.sanitizeVarName(node.conditional.id)
      this.emit(`// Nested conditional`)
      this.emit(`const ${nestedId}_nested = document.createElement('div')`)
      this.emit(`if (${node.conditional.condition}) {`)
      this.indent++
      for (const child of node.conditional.then) {
        this.emitConditionalTemplateNode(child, `${nestedId}_nested`)
      }
      this.indent--
      if (node.conditional.else && node.conditional.else.length > 0) {
        this.emit(`} else {`)
        this.indent++
        for (const child of node.conditional.else) {
          this.emitConditionalTemplateNode(child, `${nestedId}_nested`)
        }
        this.indent--
      }
      this.emit(`}`)
      this.emit(`${parentVar}.appendChild(${nestedId}_nested)`)
      return
    }

    // Handle each loops inside conditionals
    if (node.each) {
      this.emitEachLoop(node.each, parentVar)
      return
    }

    const varName = this.sanitizeVarName(node.id) + '_cond'

    this.emit(`const ${varName} = document.createElement('${node.tag}')`)

    // Set HTML properties
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(prop.value)}"` : prop.value
        this.emit(`${varName}.textContent = ${value}`)
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(String(prop.value))}"` : prop.value
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        this.emit(`'${style.property}': '${style.value}',`)
      }
      this.indent--
      this.emit('})')
    }

    // Add event listeners
    for (const event of node.events) {
      this.emitEventListener(varName, event)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitConditionalTemplateNode(child, varName)
    }

    this.emit(`${parentVar}.appendChild(${varName})`)
  }

  private emitEachTemplateNode(node: IRNode, parentVar: string, itemVar: string): void {
    const varName = this.sanitizeVarName(node.id) + '_tpl'

    this.emit(`const ${varName} = document.createElement('${node.tag}')`)

    // Set HTML properties (with data binding)
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = this.resolveTemplateValue(prop.value, itemVar)
        this.emit(`${varName}.textContent = ${value}`)
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = this.resolveTemplateValue(prop.value, itemVar)
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        const value = this.resolveTemplateStyleValue(style.value, itemVar)
        this.emit(`'${style.property}': ${value},`)
      }
      this.indent--
      this.emit('})')
    }

    // Add event listeners
    for (const event of node.events) {
      this.emitTemplateEventListener(varName, event, itemVar)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitEachTemplateNode(child, varName, itemVar)
    }

    this.emit(`${parentVar}.appendChild(${varName})`)
  }

  private resolveTemplateValue(value: string | number | boolean, itemVar: string): string {
    if (typeof value === 'string') {
      // Check if value contains item variable reference like $task.title
      if (value.includes(`$${itemVar}.`) || value.includes(`\${${itemVar}.`)) {
        // Convert $task.title to task.title
        const resolved = value.replace(new RegExp(`\\$${itemVar}\\.`, 'g'), `${itemVar}.`)
        return resolved
      }
      // Check for plain item reference $task -> task
      if (value === `$${itemVar}`) {
        return itemVar
      }
      return `"${this.escapeString(String(value))}"`
    }
    return String(value)
  }

  private resolveTemplateStyleValue(value: string, itemVar: string): string {
    // Check if value contains item variable reference
    if (value.includes(`$${itemVar}.`) || value.includes(`\${${itemVar}.`)) {
      const resolved = value.replace(new RegExp(`\\$${itemVar}\\.`, 'g'), `${itemVar}.`)
      return resolved
    }
    return `'${value}'`
  }

  private emitTemplateEventListener(varName: string, event: IREvent, itemVar: string): void {
    const eventName = event.name

    this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
    this.indent++
    for (const action of event.actions) {
      this.emitTemplateAction(action, varName, itemVar)
    }
    this.indent--
    this.emit('})')
  }

  private emitTemplateAction(action: IRAction, currentVar: string, itemVar: string): void {
    const target = action.target || 'self'

    switch (action.type) {
      case 'toggle':
        this.emit(`_runtime.toggle(_elements['${target}'] || ${currentVar})`)
        break
      case 'select':
        this.emit(`_runtime.select(${currentVar})`)
        break
      case 'assign':
        // Handle assign $selected to $item
        if (action.args && action.args[0] === `$${itemVar}`) {
          const stateVar = target.startsWith('$') ? target.slice(1) : target
          this.emit(`_state['${stateVar}'] = ${itemVar}`)
          this.emit(`api.update()`)
        }
        break
      default:
        this.emit(`// TODO: Template action '${action.type}' not implemented`)
    }
  }

  private emitEventListener(varName: string, event: IREvent): void {
    const eventName = event.name

    // Handle hover event specially - needs both mouseenter and mouseleave
    if (eventName === 'mouseenter') {
      const hasHighlight = event.actions.some(a => a.type === 'highlight')
      if (hasHighlight) {
        this.emit(`${varName}.addEventListener('mouseenter', (e) => {`)
        this.indent++
        for (const action of event.actions) {
          this.emitAction(action, varName)
        }
        this.indent--
        this.emit('})')
        // Add mouseleave to clear highlight
        this.emit(`${varName}.addEventListener('mouseleave', (e) => {`)
        this.indent++
        this.emit(`_runtime.unhighlight(${varName})`)
        this.indent--
        this.emit('})')
        return
      }
    }

    // Handle click-outside event specially
    if (eventName === 'click-outside') {
      this.emit(`// Click outside handler`)
      this.emit(`const ${varName}_clickOutsideHandler = (e) => {`)
      this.indent++
      this.emit(`if (!${varName}.contains(e.target)) {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('}')
      this.indent--
      this.emit('}')
      this.emit(`document.addEventListener('click', ${varName}_clickOutsideHandler)`)
      this.emit(`${varName}._clickOutsideHandler = ${varName}_clickOutsideHandler`)
      return
    }

    // Handle keyboard events with specific keys
    if (event.key) {
      this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
      this.indent++
      this.emit(`if (e.key === '${this.mapKeyName(event.key)}') {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('}')
      this.indent--
      this.emit('})')
    } else {
      this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('})')
    }
  }

  private emitAction(action: IRAction, currentVar: string): void {
    const target = action.target || 'self'

    // Known built-in actions
    const builtinActions = new Set([
      'toggle', 'show', 'hide', 'select', 'deselect', 'highlight',
      'activate', 'deactivate', 'call', 'assign', 'page', 'open', 'close',
      'filter', 'validate', 'reset', 'focus', 'alert', 'clear-selection',
      'deactivate-siblings', 'toggle-state', 'set-state', 'change', 'navigate'
    ])

    switch (action.type) {
      case 'toggle':
        this.emit(`_runtime.toggle(_elements['${target}'] || ${currentVar})`)
        break
      case 'show':
        this.emit(`_runtime.show(_elements['${target}'] || ${currentVar})`)
        break
      case 'hide':
        this.emit(`_runtime.hide(_elements['${target}'] || ${currentVar})`)
        break
      case 'close':
        // close sets state to "closed" for toggle elements, otherwise hides
        this.emit(`_runtime.close(_elements['${target}'] || ${currentVar})`)
        break
      case 'select':
        if (target === 'highlighted') {
          this.emit(`_runtime.selectHighlighted(${currentVar})`)
        } else {
          this.emit(`_runtime.select(_elements['${target}'] || ${currentVar})`)
        }
        break
      case 'deselect':
        this.emit(`_runtime.deselect(_elements['${target}'] || ${currentVar})`)
        break
      case 'highlight':
        if (target === 'next') {
          this.emit(`_runtime.highlightNext(${currentVar})`)
        } else if (target === 'prev') {
          this.emit(`_runtime.highlightPrev(${currentVar})`)
        } else if (target === 'first') {
          this.emit(`_runtime.highlightFirst(${currentVar})`)
        } else if (target === 'last') {
          this.emit(`_runtime.highlightLast(${currentVar})`)
        } else {
          this.emit(`_runtime.highlight(_elements['${target}'] || ${currentVar})`)
        }
        break
      case 'activate':
        this.emit(`_runtime.activate(_elements['${target}'] || ${currentVar})`)
        break
      case 'deactivate':
        this.emit(`_runtime.deactivate(_elements['${target}'] || ${currentVar})`)
        break
      case 'toggle-state':
        // toggle-state Target or toggle-state Target stateName
        const stateArg = action.args?.[0] || 'on'
        this.emit(`_runtime.toggleState(_elements['${target}'] || ${currentVar}, '${stateArg}')`)
        break
      case 'set-state':
        // set-state Target stateName
        const newState = action.args?.[0] || 'default'
        this.emit(`_runtime.setState(_elements['${target}'] || ${currentVar}, '${newState}')`)
        break
      case 'call':
        const fnName = action.target || ''
        const args = action.args?.map(a => `"${a}"`).join(', ') || ''
        this.emit(`if (typeof ${fnName} === 'function') ${fnName}(${args})`)
        break
      case 'navigate':
        // Navigate to a target component or page
        // Lowercase = page route (load file), Uppercase = component route
        const isPageRoute = /^[a-z]/.test(target)
        if (isPageRoute) {
          this.emit(`_runtime.navigateToPage('${target}', ${currentVar})`)
        } else {
          this.emit(`_runtime.navigate('${target}', ${currentVar})`)
        }
        break
      default:
        // Unknown action = treat as direct function call
        // This allows: onclick addTask -> calls addTask()
        if (!builtinActions.has(action.type)) {
          const funcName = action.type
          const funcArgs = action.target ? `"${action.target}"` : ''
          this.emit(`if (typeof ${funcName} === 'function') ${funcName}(${funcArgs})`)
        } else {
          this.emit(`// TODO: Action '${action.type}' not implemented`)
        }
    }
  }

  private emitPublicAPI(): void {
    this.emit('// Public API')
    this.emit('const api = {')
    this.indent++

    this.emit('root: _root,')
    this.emit('')

    // Generate accessors for named instances
    const namedNodes = this.collectNamedNodes(this.ir.nodes)
    for (const node of namedNodes) {
      this.emit(`get ${node.instanceName}() {`)
      this.indent++
      this.emit(`return _runtime.wrap(_elements['${node.instanceName}'])`)
      this.indent--
      this.emit('},')
    }

    this.emit('')
    this.emit('// State management')
    this.emit('setState(key, value) {')
    this.indent++
    this.emit('_state[key] = value')
    this.emit('this.update()')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('getState(key) {')
    this.indent++
    this.emit('return _state[key]')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('update() {')
    this.indent++
    this.emit('// Re-render each loops based on state changes')
    this.emit("for (const el of _root.querySelectorAll('[data-each-container]')) {")
    this.indent++
    this.emit('if (el._eachConfig) {')
    this.indent++
    this.emit('const { collection, renderItem, filter } = el._eachConfig')
    this.emit('const items = _state[collection] || []')
    this.emit('const filtered = filter ? items.filter(item => eval(filter)) : items')
    this.emit('el.innerHTML = ""')
    this.emit('filtered.forEach((item, index) => el.appendChild(renderItem(item, index)))')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Re-render conditionals based on state changes')
    this.emit("for (const el of _root.querySelectorAll('[data-conditional-id]')) {")
    this.indent++
    this.emit('if (el._conditionalConfig) {')
    this.indent++
    this.emit('const { condition, renderThen, renderElse } = el._conditionalConfig')
    this.emit('el.innerHTML = ""')
    this.emit('if (condition()) {')
    this.indent++
    this.emit('el.appendChild(renderThen())')
    this.indent--
    this.emit('} else if (renderElse) {')
    this.indent++
    this.emit('el.appendChild(renderElse())')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')

    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('return api')
  }

  private emitRuntime(): void {
    this.emit('// Runtime helpers')
    this.emit('const _runtime = {')
    this.indent++

    // Property mapping for Mirror -> CSS conversion
    this.emit('// Mirror property to CSS mapping')
    this.emit('_propMap: {')
    this.indent++
    this.emit("'bg': 'background',")
    this.emit("'col': 'color',")
    this.emit("'pad': 'padding',")
    this.emit("'rad': 'borderRadius',")
    this.emit("'gap': 'gap',")
    this.emit("'w': 'width',")
    this.emit("'h': 'height',")
    this.emit("'opacity': 'opacity',")
    this.indent--
    this.emit('},')
    this.emit('')

    // Alignment mapping based on flex-direction
    this.emit('// Convert alignment value to CSS')
    this.emit('_alignToCSS(el, prop, value) {')
    this.indent++
    this.emit("const dir = el.style.flexDirection || 'column'")
    this.emit("const isRow = dir === 'row'")
    this.emit('')
    this.emit("const alignMap = { 'left': 'flex-start', 'right': 'flex-end', 'center': 'center', 'top': 'flex-start', 'bottom': 'flex-end' }")
    this.emit("const cssVal = alignMap[value] || value")
    this.emit('')
    this.emit("if (prop === 'align' || prop === 'hor-align') {")
    this.indent++
    this.emit("// Horizontal alignment")
    this.emit("if (isRow) { el.style.justifyContent = cssVal }")
    this.emit("else { el.style.alignItems = cssVal }")
    this.indent--
    this.emit("} else if (prop === 'ver-align') {")
    this.indent++
    this.emit("// Vertical alignment")
    this.emit("if (isRow) { el.style.alignItems = cssVal }")
    this.emit("else { el.style.justifyContent = cssVal }")
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    // Get alignment from element
    this.emit('_getAlign(el, prop) {')
    this.indent++
    this.emit("const dir = el.style.flexDirection || 'column'")
    this.emit("const isRow = dir === 'row'")
    this.emit("const reverseMap = { 'flex-start': 'left', 'flex-end': 'right', 'center': 'center' }")
    this.emit('')
    this.emit("if (prop === 'align' || prop === 'hor-align') {")
    this.indent++
    this.emit("const val = isRow ? el.style.justifyContent : el.style.alignItems")
    this.emit("return reverseMap[val] || val")
    this.indent--
    this.emit("} else if (prop === 'ver-align') {")
    this.indent++
    this.emit("const val = isRow ? el.style.alignItems : el.style.justifyContent")
    this.emit("const vertMap = { 'flex-start': 'top', 'flex-end': 'bottom', 'center': 'center' }")
    this.emit("return vertMap[val] || val")
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('wrap(el) {')
    this.indent++
    this.emit('if (!el) return null')
    this.emit('const self = this')
    this.emit('return {')
    this.indent++
    this.emit('_el: el,')
    this.emit('')
    this.emit('// Text & Value')
    this.emit('get text() { return el.textContent },')
    this.emit('set text(v) { el.textContent = v },')
    this.emit('get value() { return el.value },')
    this.emit('set value(v) { el.value = v },')
    this.emit('')
    this.emit('// Visibility')
    this.emit('get visible() { return el.style.display !== "none" },')
    this.emit('set visible(v) { el.style.display = v ? "" : "none" },')
    this.emit('get hidden() { return el.hidden },')
    this.emit('set hidden(v) { el.hidden = v; el.style.display = v ? "none" : "" },')
    this.emit('')
    this.emit('// Alignment (smart based on flex-direction)')
    this.emit("get align() { return self._getAlign(el, 'align') },")
    this.emit("set align(v) { self._alignToCSS(el, 'align', v) },")
    this.emit("get verAlign() { return self._getAlign(el, 'ver-align') },")
    this.emit("set verAlign(v) { self._alignToCSS(el, 'ver-align', v) },")
    this.emit('')
    this.emit('// Common style properties')
    this.emit('get bg() { return el.style.background },')
    this.emit('set bg(v) { el.style.background = v },')
    this.emit('get col() { return el.style.color },')
    this.emit('set col(v) { el.style.color = v },')
    this.emit("get pad() { return el.style.padding },")
    this.emit("set pad(v) { el.style.padding = typeof v === 'number' ? v + 'px' : v },")
    this.emit("get gap() { return el.style.gap },")
    this.emit("set gap(v) { el.style.gap = typeof v === 'number' ? v + 'px' : v },")
    this.emit("get rad() { return el.style.borderRadius },")
    this.emit("set rad(v) { el.style.borderRadius = typeof v === 'number' ? v + 'px' : v },")
    this.emit("get w() { return el.style.width },")
    this.emit("set w(v) { el.style.width = typeof v === 'number' ? v + 'px' : v },")
    this.emit("get h() { return el.style.height },")
    this.emit("set h(v) { el.style.height = typeof v === 'number' ? v + 'px' : v },")
    this.emit('get opacity() { return el.style.opacity },')
    this.emit('set opacity(v) { el.style.opacity = v },')
    this.emit('')
    this.emit('// State')
    this.emit("get state() { return el.dataset.state || 'default' },")
    this.emit('set state(v) { self.setState(el, v) },')
    this.emit('')
    this.emit('// Events')
    this.emit('set onclick(fn) { el.addEventListener("click", fn) },')
    this.emit('set onchange(fn) { el.addEventListener("change", fn) },')
    this.emit('')
    this.emit('// Methods')
    this.emit('addClass(c) { el.classList.add(c) },')
    this.emit('removeClass(c) { el.classList.remove(c) },')
    this.emit('toggleClass(c) { el.classList.toggle(c) },')
    this.emit('setStyle(prop, val) { el.style[prop] = val },')
    this.emit('getStyle(prop) { return el.style[prop] },')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('toggle(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// Handle dropdown-style open/closed states')
    this.emit('const currentState = el.dataset.state || el._initialState')
    this.emit('if (currentState === "closed" || currentState === "open") {')
    this.indent++
    this.emit('const newState = currentState === "closed" ? "open" : "closed"')
    this.emit('this.setState(el, newState)')
    this.indent--
    this.emit('} else if (currentState === "collapsed" || currentState === "expanded") {')
    this.indent++
    this.emit('const newState = currentState === "collapsed" ? "expanded" : "collapsed"')
    this.emit('this.setState(el, newState)')
    this.indent--
    this.emit('} else {')
    this.indent++
    this.emit('// Fallback to hidden toggle')
    this.emit('el.hidden = !el.hidden')
    this.emit('this.applyState(el, el.hidden ? "off" : "on")')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('show(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('el.hidden = false')
    this.emit('el.style.display = ""')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('hide(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('el.hidden = true')
    this.emit('el.style.display = "none"')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('close(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// If element has toggle state (open/closed), set to closed')
    this.emit('const initialState = el._initialState')
    this.emit('if (initialState === "closed" || initialState === "open" || el.dataset.state === "open" || el.dataset.state === "closed") {')
    this.indent++
    this.emit('this.setState(el, "closed")')
    this.indent--
    this.emit('} else if (initialState === "expanded" || initialState === "collapsed" || el.dataset.state === "expanded" || el.dataset.state === "collapsed") {')
    this.indent++
    this.emit('this.setState(el, "collapsed")')
    this.indent--
    this.emit('} else {')
    this.indent++
    this.emit('// Fallback to hide')
    this.emit('this.hide(el)')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('select(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// Clear previous selection from siblings')
    this.emit('if (el.parentElement) {')
    this.indent++
    this.emit('Array.from(el.parentElement.children).forEach(sibling => {')
    this.indent++
    this.emit('if (sibling !== el && sibling.dataset.selected) {')
    this.indent++
    this.emit('this.deselect(sibling)')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('}')
    this.emit('el.dataset.selected = "true"')
    this.emit('this.applyState(el, "selected")')
    this.emit('// Update selection binding if present')
    this.emit('this.updateSelectionBinding(el)')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('deselect(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('delete el.dataset.selected')
    this.emit('this.removeState(el, "selected")')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('highlight(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// Clear highlight from siblings first')
    this.emit('if (el.parentElement) {')
    this.indent++
    this.emit('Array.from(el.parentElement.children).forEach(sibling => {')
    this.indent++
    this.emit('if (sibling !== el && sibling.dataset.highlighted) {')
    this.indent++
    this.emit('this.unhighlight(sibling)')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('}')
    this.emit('el.dataset.highlighted = "true"')
    this.emit('this.applyState(el, "highlighted")')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('unhighlight(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('delete el.dataset.highlighted')
    this.emit('this.removeState(el, "highlighted")')
    this.indent--
    this.emit('},')
    this.emit('')

    // Add highlightNext - find and highlight next sibling item
    this.emit('highlightNext(container) {')
    this.indent++
    this.emit('if (!container) return')
    this.emit('// Find the menu/list container with items')
    this.emit('const items = this.getHighlightableItems(container)')
    this.emit('if (!items.length) return')
    this.emit('const current = items.findIndex(el => el.dataset.highlighted === "true")')
    this.emit('const next = current === -1 ? 0 : Math.min(current + 1, items.length - 1)')
    this.emit('this.highlight(items[next])')
    this.indent--
    this.emit('},')
    this.emit('')

    // Add highlightPrev - find and highlight previous sibling item
    this.emit('highlightPrev(container) {')
    this.indent++
    this.emit('if (!container) return')
    this.emit('const items = this.getHighlightableItems(container)')
    this.emit('if (!items.length) return')
    this.emit('const current = items.findIndex(el => el.dataset.highlighted === "true")')
    this.emit('const prev = current === -1 ? items.length - 1 : Math.max(current - 1, 0)')
    this.emit('this.highlight(items[prev])')
    this.indent--
    this.emit('},')
    this.emit('')

    // Add highlightFirst
    this.emit('highlightFirst(container) {')
    this.indent++
    this.emit('if (!container) return')
    this.emit('const items = this.getHighlightableItems(container)')
    this.emit('if (items.length) this.highlight(items[0])')
    this.indent--
    this.emit('},')
    this.emit('')

    // Add highlightLast
    this.emit('highlightLast(container) {')
    this.indent++
    this.emit('if (!container) return')
    this.emit('const items = this.getHighlightableItems(container)')
    this.emit('if (items.length) this.highlight(items[items.length - 1])')
    this.indent--
    this.emit('},')
    this.emit('')

    // Helper to get highlightable items in a container
    this.emit('getHighlightableItems(container) {')
    this.indent++
    this.emit('// Find all children that have _stateStyles.highlighted (proper highlight targets)')
    this.emit('// Falls back to cursor: pointer only if no highlighted items found')
    this.emit('const findItems = (el, requireHighlightState) => {')
    this.indent++
    this.emit('const items = []')
    this.emit('for (const child of el.children) {')
    this.indent++
    this.emit('if (child._stateStyles?.highlighted) {')
    this.indent++
    this.emit('items.push(child)')
    this.indent--
    this.emit('} else if (!requireHighlightState && child.style.cursor === "pointer") {')
    this.indent++
    this.emit('items.push(child)')
    this.indent--
    this.emit('} else {')
    this.indent++
    this.emit('// Recurse into child containers')
    this.emit('items.push(...findItems(child, requireHighlightState))')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.emit('return items')
    this.indent--
    this.emit('}')
    this.emit('// First try to find items with _stateStyles.highlighted')
    this.emit('let items = findItems(container, true)')
    this.emit('// Fall back to cursor: pointer if no highlighted items found')
    this.emit('if (!items.length) items = findItems(container, false)')
    this.emit('return items')
    this.indent--
    this.emit('},')
    this.emit('')

    // Add selectHighlighted
    this.emit('selectHighlighted(container) {')
    this.indent++
    this.emit('if (!container) return')
    this.emit('const items = this.getHighlightableItems(container)')
    this.emit('const highlighted = items.find(el => el.dataset.highlighted === "true")')
    this.emit('if (highlighted) this.select(highlighted)')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('activate(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('el.dataset.active = "true"')
    this.emit('this.applyState(el, "active")')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('deactivate(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('delete el.dataset.active')
    this.emit('this.removeState(el, "active")')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('applyState(el, state) {')
    this.indent++
    this.emit('if (!el._stateStyles || !el._stateStyles[state]) return')
    this.emit('Object.assign(el.style, el._stateStyles[state])')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('removeState(el, state) {')
    this.indent++
    this.emit('if (!el._baseStyles) return')
    this.emit('Object.assign(el.style, el._baseStyles)')
    this.indent--
    this.emit('},')
    this.emit('')

    // setState - switch to a named state
    this.emit('setState(el, stateName) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('')
    this.emit('// Store base styles on first state change')
    this.emit('if (!el._baseStyles && el._stateStyles) {')
    this.indent++
    this.emit('el._baseStyles = {}')
    this.emit('const stateProps = new Set()')
    this.emit('for (const state of Object.values(el._stateStyles)) {')
    this.indent++
    this.emit('for (const prop of Object.keys(state)) stateProps.add(prop)')
    this.indent--
    this.emit('}')
    this.emit('for (const prop of stateProps) {')
    this.indent++
    this.emit('el._baseStyles[prop] = el.style[prop] || ""')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Restore base styles first')
    this.emit('if (el._baseStyles) Object.assign(el.style, el._baseStyles)')
    this.emit('')
    this.emit('// Apply new state')
    this.emit('el.dataset.state = stateName')
    this.emit("if (stateName !== 'default' && el._stateStyles && el._stateStyles[stateName]) {")
    this.indent++
    this.emit('Object.assign(el.style, el._stateStyles[stateName])')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Update visibility of children based on new state')
    this.emit('this.updateVisibility(el)')
    this.indent--
    this.emit('},')
    this.emit('')

    // toggleState - toggle between two states
    this.emit('toggleState(el, state1, state2) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit("state2 = state2 || 'default'")
    this.emit('const current = el.dataset.state || state2')
    this.emit('const next = current === state1 ? state2 : state1')
    this.emit('this.setState(el, next)')
    this.indent--
    this.emit('},')
    this.emit('')

    // updateVisibility - update children based on visibleWhen
    this.emit('updateVisibility(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('const state = el.dataset.state')
    this.emit('// Find children with _visibleWhen')
    this.emit('const children = el.querySelectorAll("[data-mirror-id]")')
    this.emit('children.forEach(child => {')
    this.indent++
    this.emit('if (child._visibleWhen) {')
    this.indent++
    this.emit('// Simple state match or evaluate condition')
    this.emit('const condition = child._visibleWhen')
    this.emit('let visible = false')
    this.emit('if (condition.includes("&&") || condition.includes("||")) {')
    this.indent++
    this.emit('// Complex condition - evaluate with state as context')
    this.emit('try {')
    this.indent++
    this.emit('const open = state === "open"')
    this.emit('const closed = state === "closed"')
    this.emit('const expanded = state === "expanded"')
    this.emit('const collapsed = state === "collapsed"')
    this.emit('visible = eval(condition)')
    this.indent--
    this.emit('} catch (e) { visible = false }')
    this.indent--
    this.emit('} else {')
    this.indent++
    this.emit('// Simple state name match')
    this.emit('visible = state === condition')
    this.indent--
    this.emit('}')
    this.emit('child.style.display = visible ? "" : "none"')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('},')
    this.emit('')

    // navigate - navigate to a target component (for Nav routing)
    this.emit('navigate(targetName, clickedElement) {')
    this.indent++
    this.emit('if (!targetName) return')
    this.emit('')
    this.emit('// Find the target component by name')
    this.emit('const target = document.querySelector(`[data-component="${targetName}"]`)')
    this.emit('if (!target) return')
    this.emit('')
    this.emit('// Show target, hide siblings')
    this.emit('if (target.parentElement) {')
    this.indent++
    this.emit('Array.from(target.parentElement.children).forEach(sibling => {')
    this.indent++
    this.emit('if (sibling.dataset && sibling.dataset.component) {')
    this.indent++
    this.emit('sibling.style.display = sibling === target ? "" : "none"')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Update selected state in Nav container')
    this.emit('this.updateNavSelection(clickedElement)')
    this.indent--
    this.emit('},')
    this.emit('')

    // updateNavSelection - sync selected state for all nav items
    this.emit('updateNavSelection(clickedElement) {')
    this.indent++
    this.emit('if (!clickedElement) return')
    this.emit('')
    this.emit('// Find the Nav container')
    this.emit('const nav = clickedElement.closest("nav")')
    this.emit('if (!nav) return')
    this.emit('')
    this.emit('// Find all elements with route in this nav')
    this.emit('const navItems = nav.querySelectorAll("[data-route]")')
    this.emit('navItems.forEach(item => {')
    this.indent++
    this.emit('if (item === clickedElement) {')
    this.indent++
    this.emit('item.dataset.selected = "true"')
    this.emit('this.applyState(item, "selected")')
    this.indent--
    this.emit('} else {')
    this.indent++
    this.emit('delete item.dataset.selected')
    this.emit('this.removeState(item, "selected")')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('},')
    this.emit('')

    // navigateToPage - load and render a page from file
    this.emit('// Navigate to page (load .mirror file)')
    this.emit('navigateToPage(pageName, clickedElement) {')
    this.indent++
    this.emit('if (!pageName) return')
    this.emit('')
    this.emit('// Construct filename (support paths like admin/users)')
    this.emit('const filename = pageName.endsWith(".mirror") ? pageName : pageName + ".mirror"')
    this.emit('')
    this.emit('// Get readFile from options or window')
    this.emit('const readFile = this._readFile || window._mirrorReadFile')
    this.emit('if (!readFile) {')
    this.indent++
    this.emit('console.warn("No readFile callback available for page navigation")')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Load file content')
    this.emit('const content = readFile(filename)')
    this.emit('if (!content) {')
    this.indent++
    this.emit('console.warn(`Page not found: ${filename}`)')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Compile the page (Mirror must be available globally)')
    this.emit('if (typeof Mirror === "undefined" || !Mirror.compile) {')
    this.indent++
    this.emit('console.warn("Mirror compiler not available for dynamic page loading")')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('try {')
    this.indent++
    this.emit('const pageCode = Mirror.compile(content, { readFile })')
    this.emit('')
    this.emit('// Find page container')
    this.emit('const container = this.getPageContainer()')
    this.emit('if (!container) {')
    this.indent++
    this.emit('console.warn("No page container found for rendering")')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Clear and render new page')
    this.emit('container.innerHTML = ""')
    this.emit('const execCode = pageCode.replace("export function createUI", "function createUI")')
    this.emit('const fn = new Function(execCode + "\\nreturn createUI();")')
    this.emit('const ui = fn()')
    this.emit('if (ui && ui.root) {')
    this.indent++
    this.emit('// Append children of root, not root itself')
    this.emit('while (ui.root.firstChild) {')
    this.indent++
    this.emit('container.appendChild(ui.root.firstChild)')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('} catch (err) {')
    this.indent++
    this.emit('console.error(`Failed to load page ${filename}:`, err)')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Update selected state')
    this.emit('this.updateNavSelection(clickedElement)')
    this.indent--
    this.emit('},')
    this.emit('')

    // getPageContainer - find the container for page content
    this.emit('// Get container for page content')
    this.emit('getPageContainer() {')
    this.indent++
    this.emit('// First try named page container')
    this.emit('let container = document.querySelector("[data-page-container]")')
    this.emit('if (container) return container')
    this.emit('')
    this.emit('// Then try named instance "PageContent" or "Content"')
    this.emit('container = document.querySelector("[data-instance-name=\\"PageContent\\"]")')
    this.emit('if (container) return container')
    this.emit('container = document.querySelector("[data-instance-name=\\"Content\\"]")')
    this.emit('if (container) return container')
    this.emit('')
    this.emit('// Fallback: first sibling of nav that is not nav')
    this.emit('const nav = document.querySelector("nav")')
    this.emit('if (nav && nav.parentElement) {')
    this.indent++
    this.emit('for (const sibling of nav.parentElement.children) {')
    this.indent++
    this.emit('if (sibling !== nav && sibling.tagName !== "NAV") {')
    this.indent++
    this.emit('return sibling')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('return null')
    this.indent--
    this.emit('},')
    this.emit('')

    // updateSelectionBinding - update the selection variable when an item is selected
    this.emit('updateSelectionBinding(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// Find parent with _selectionBinding')
    this.emit('let parent = el.parentElement')
    this.emit('while (parent) {')
    this.indent++
    this.emit('if (parent._selectionBinding) {')
    this.indent++
    this.emit('// Get the text content of the selected element')
    this.emit('const value = el.textContent?.trim() || ""')
    this.emit('// Store in global state')
    this.emit('const varName = parent._selectionBinding')
    this.emit('window._mirrorState = window._mirrorState || {}')
    this.emit('window._mirrorState[varName] = value')
    this.emit('// Update all bound elements')
    this.emit('this.updateBoundElements(varName, value)')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('parent = parent.parentElement')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    // updateBoundElements - update all elements bound to a variable
    this.emit('updateBoundElements(varName, value) {')
    this.indent++
    this.emit('// Find all elements with _textBinding')
    this.emit('document.querySelectorAll("[data-mirror-id]").forEach(el => {')
    this.indent++
    this.emit('if (el._textBinding === varName) {')
    this.indent++
    this.emit('// Simple update - just set the text')
    this.emit('el.textContent = value || el._textPlaceholder || ""')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('})')
    this.indent--
    this.emit('},')
    this.emit('')

    // destroy - cleanup handlers to prevent memory leaks
    this.emit('destroy(el) {')
    this.indent++
    this.emit('if (!el) return')
    this.emit('// Remove click-outside handler')
    this.emit('if (el._clickOutsideHandler) {')
    this.indent++
    this.emit("document.removeEventListener('click', el._clickOutsideHandler)")
    this.emit('delete el._clickOutsideHandler')
    this.indent--
    this.emit('}')
    this.emit('// Recursively destroy children')
    this.emit('if (el.children) {')
    this.indent++
    this.emit('Array.from(el.children).forEach(child => this.destroy(child))')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')
    this.emit('')

    // loadIcon - fetch Lucide SVG and inject into element
    this.emit('// Load Lucide icon from CDN')
    this.emit('async loadIcon(el, iconName) {')
    this.indent++
    this.emit('if (!el || !iconName) return')
    this.emit('')
    this.emit('// Get icon properties from data attributes')
    this.emit("const size = el.dataset.iconSize || '24'")
    this.emit('const color = el.dataset.iconColor || "currentColor"')
    this.emit("const strokeWidth = el.dataset.iconWeight || '2'")
    this.emit('')
    this.emit('try {')
    this.indent++
    this.emit('const url = `https://unpkg.com/lucide-static/icons/${iconName}.svg`')
    this.emit('const res = await fetch(url)')
    this.emit('if (!res.ok) {')
    this.indent++
    this.emit('console.warn(`Icon "${iconName}" not found`)')
    this.emit('el.textContent = iconName')
    this.emit('return')
    this.indent--
    this.emit('}')
    this.emit('const svgText = await res.text()')
    this.emit('el.innerHTML = svgText')
    this.emit('')
    this.emit("const svg = el.querySelector('svg')")
    this.emit('if (svg) {')
    this.indent++
    this.emit("svg.style.width = size + 'px'")
    this.emit("svg.style.height = size + 'px'")
    this.emit('svg.style.color = color')
    this.emit("svg.setAttribute('stroke-width', strokeWidth)")
    this.emit("svg.style.display = 'block'")
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('} catch (err) {')
    this.indent++
    this.emit('console.warn(`Failed to load icon "${iconName}":`, err)')
    this.emit('el.textContent = iconName')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')

    this.indent--
    this.emit('}')
    this.emit('')
  }

  private sanitizeVarName(id: string): string {
    return id.replace(/-/g, '_')
  }

  private escapeString(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
  }

  private mapKeyName(key: string): string {
    const mapping: Record<string, string> = {
      'escape': 'Escape',
      'enter': 'Enter',
      'tab': 'Tab',
      'space': ' ',
      'arrow-up': 'ArrowUp',
      'arrow-down': 'ArrowDown',
      'arrow-left': 'ArrowLeft',
      'arrow-right': 'ArrowRight',
      'backspace': 'Backspace',
      'delete': 'Delete',
    }
    return mapping[key] || key
  }

  private groupByState(styles: IRStyle[]): Record<string, IRStyle[]> {
    const result: Record<string, IRStyle[]> = {}
    for (const style of styles) {
      const state = style.state || 'default'
      if (!result[state]) result[state] = []
      result[state].push(style)
    }
    return result
  }

  private collectNamedNodes(nodes: IRNode[]): IRNode[] {
    const result: IRNode[] = []
    for (const node of nodes) {
      if (node.instanceName) {
        result.push(node)
      }
      result.push(...this.collectNamedNodes(node.children))
    }
    return result
  }

  private emitInitialization(): void {
    const namedNodes = this.collectNamedNodes(this.ir.nodes)

    this.emit('// ============================================')
    this.emit('// Auto-initialization (Mirror + JavaScript)')
    this.emit('// ============================================')
    this.emit('')

    // Create UI instance
    this.emit('const _ui = createUI()')
    this.emit('')

    // Expose named instances as global variables
    if (namedNodes.length > 0) {
      this.emit('// Named instance proxies')
      for (const node of namedNodes) {
        this.emit(`const ${node.instanceName} = _ui.${node.instanceName}`)
      }
      this.emit('')
    }

    // Global update function
    this.emit('// Global update function')
    this.emit('function update() { _ui.update() }')
    this.emit('')

    // User JavaScript
    this.emit('// User JavaScript')
    if (this.javascript) {
      // Emit the JavaScript code as-is, preserving formatting
      for (const line of this.javascript.code.split('\n')) {
        this.emitRaw(line)
      }
    }
    this.emit('')

    // Auto-mount to body
    this.emit('// Mount to document')
    this.emit('document.body.appendChild(_ui.root)')
  }
}
