/**
 * Mirror DOM Backend
 *
 * Generates pure JavaScript DOM manipulation code.
 * Flagship backend - no framework dependencies.
 */

import type { AST } from '../parser/ast'
import { toIR } from '../ir'

/**
 * Generate DOM manipulation JavaScript code from Mirror AST
 *
 * Output: ES module with factory function
 *
 * @example
 * ```javascript
 * import createUI from "./app.mirror.js"
 *
 * const ui = createUI()
 * ui.header.text = "Hello"
 * ui.saveBtn.onclick = () => { ... }
 * ui.render("#root")
 * ```
 */
export function generateDOM(ast: AST): string {
  const ir = toIR(ast)

  const lines: string[] = [
    '// Generated by Mirror Compiler',
    '// Do not edit manually',
    '',
    'export default function createUI() {',
    '  const _elements = {}',
    ''
  ]

  // Generate DOM creation
  for (const node of ir.nodes) {
    lines.push(`  // ${node.name || node.tag}`)
    lines.push(`  _elements['${node.id}'] = document.createElement('${node.tag}')`)

    // Apply styles
    for (const style of node.styles) {
      const state = style.state ? `.${style.state}` : ''
      lines.push(`  // TODO: Apply style ${style.property}${state}: ${style.value}`)
    }

    lines.push('')
  }

  // Generate reactive interface
  lines.push('  // Reactive interface')
  lines.push('  return {')

  for (const node of ir.nodes) {
    if (node.instanceName) {
      lines.push(`    ${node.instanceName}: {`)
      lines.push(`      get text() { return _elements['${node.id}'].textContent },`)
      lines.push(`      set text(v) { _elements['${node.id}'].textContent = v },`)
      lines.push(`      set onclick(fn) { _elements['${node.id}'].addEventListener('click', fn) },`)
      lines.push(`      _el: _elements['${node.id}']`)
      lines.push('    },')
    }
  }

  lines.push('    render(target) {')
  lines.push('      const el = typeof target === "string" ? document.querySelector(target) : target || document.body')
  lines.push('      // TODO: Append root element')
  lines.push('    }')
  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}
