/**
 * Mirror React Backend
 *
 * Generates React component code.
 * For adoption in existing React projects.
 */

import type { AST } from '../parser/ast'

/**
 * Generate React component code from Mirror AST
 *
 * TODO: Implement React code generation
 */
export function generateReact(ast: AST): string {
  const lines: string[] = [
    '// Generated by Mirror Compiler (React Backend)',
    '// Do not edit manually',
    '',
    'import React from "react"',
    '',
    '// TODO: Implement React component generation',
    'export default function App() {',
    '  return <div>TODO: Generated UI</div>',
    '}',
    ''
  ]

  return lines.join('\n')
}
