/**
 * Mirror DOM Backend
 *
 * Generates pure JavaScript DOM manipulation code.
 * Flagship backend - no framework dependencies.
 */

import type { AST, JavaScriptBlock } from '../parser/ast'
import { toIR } from '../ir'
import type { IR, IRNode, IRStyle, IREvent, IRAction, IREach, IRConditional, IRAnimation, IRZagNode } from '../ir/types'
import { isIRZagNode } from '../ir/types'
import { DOM_RUNTIME_CODE } from '../runtime/dom-runtime-string'

/**
 * Generate DOM manipulation JavaScript code from Mirror AST
 *
 * Output: ES module with factory function
 *
 * @example
 * ```javascript
 * import { createUI } from "./app.mirror.js"
 *
 * const ui = createUI()
 * ui.header.text = "Hello"
 * ui.saveBtn.onclick = () => { ... }
 * document.body.appendChild(ui.root)
 * ```
 */
export function generateDOM(ast: AST): string {
  const ir = toIR(ast)
  const generator = new DOMGenerator(ir, ast.javascript)
  return generator.generate()
}

class DOMGenerator {
  private ir: IR
  private javascript?: JavaScriptBlock
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR, javascript?: JavaScriptBlock) {
    this.ir = ir
    this.javascript = javascript
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitCreateUI()
    this.emitRuntime()
    this.emitAnimations()

    // If there's JavaScript, emit initialization with named instance exposure
    if (this.javascript) {
      this.emitInitialization()
    }

    return this.lines.join('\n')
  }

  private emitAnimations(): void {
    if (this.ir.animations.length === 0) return

    this.emit('// Register animations')
    for (const animation of this.ir.animations) {
      this.emitAnimationRegistration(animation)
    }
    this.emit('')
  }

  private emitAnimationRegistration(animation: IRAnimation): void {
    this.emit(`_runtime.registerAnimation({`)
    this.indent++
    this.emit(`name: "${animation.name}",`)
    this.emit(`easing: "${animation.easing}",`)
    if (animation.duration) {
      this.emit(`duration: ${animation.duration},`)
    }
    if (animation.roles && animation.roles.length > 0) {
      this.emit(`roles: ${JSON.stringify(animation.roles)},`)
    }
    this.emit(`keyframes: [`)
    this.indent++
    for (const keyframe of animation.keyframes) {
      this.emit(`{`)
      this.indent++
      this.emit(`time: ${keyframe.time},`)
      this.emit(`properties: [`)
      this.indent++
      for (const prop of keyframe.properties) {
        this.emit(`{ property: "${prop.property}", value: "${prop.value}"${prop.target ? `, target: "${prop.target}"` : ''} },`)
      }
      this.indent--
      this.emit(`],`)
      this.indent--
      this.emit(`},`)
    }
    this.indent--
    this.emit(`],`)
    this.indent--
    this.emit(`})`)
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitRaw(line: string): void {
    this.lines.push(line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (DOM Backend)')
    this.emit('// Do not edit manually')
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('const tokens = {')
    this.indent++
    for (const token of this.ir.tokens) {
      const value = typeof token.value === 'string' ? `"${token.value}"` : token.value
      // Strip $ prefix and convert dots to hyphens for consistency with CSS variables
      const tokenKey = (token.name.startsWith('$') ? token.name.slice(1) : token.name)
        .replace(/\./g, '-')
      this.emit(`"${tokenKey}": ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitStyles(): void {
    this.emit('// Inject CSS styles')
    this.emit("const _style = document.createElement('style')")
    this.emit('_style.textContent = `')

    // CSS Variables
    if (this.ir.tokens.length > 0) {
      this.emit(':root {')
      this.indent++
      for (const token of this.ir.tokens) {
        let value = token.value
        // Strip $ prefix and convert dots to hyphens for valid CSS variable name
        // e.g., $primary.bg -> primary-bg
        const cssVarName = (token.name.startsWith('$') ? token.name.slice(1) : token.name)
          .replace(/\./g, '-')

        // Add px unit for numeric spacing/sizing tokens
        // These are tokens with names ending in .pad, .gap, .rad, .margin, .size
        const needsPx = /\.(pad|gap|rad|radius|margin|size)$/.test(token.name)
        if (needsPx && typeof value === 'number') {
          value = `${value}px`
        } else if (needsPx && typeof value === 'string' && /^\d+$/.test(value)) {
          value = `${value}px`
        }

        this.emit(`--${cssVarName}: ${value};`)
      }
      this.indent--
      this.emit('}')
      this.emit('')
    }

    // Base reset
    this.emit('.mirror-root * {')
    this.emit('  box-sizing: border-box;')
    this.emit('}')

    // Emit CSS for system states (hover, focus, active, disabled)
    this.emitSystemStateCSS()

    this.emit('`')
    this.emit('document.head.appendChild(_style)')
    this.emit('')
  }

  private emitSystemStateCSS(): void {
    // Collect all system states from nodes
    const systemStates = ['hover', 'focus', 'active', 'disabled']

    for (const node of this.ir.nodes) {
      this.emitNodeStateCSS(node, systemStates)
    }
  }

  private emitNodeStateCSS(node: IRNode, systemStates: string[]): void {
    const stateStyles = node.styles.filter(s => s.state && systemStates.includes(s.state))

    if (stateStyles.length > 0) {
      const byState = this.groupByState(stateStyles)

      for (const [state, styles] of Object.entries(byState)) {
        const pseudoClass = state === 'disabled' ? '[disabled]' : `:${state}`
        this.emit('')
        this.emit(`[data-mirror-id="${node.id}"]${pseudoClass} {`)
        this.indent++
        for (const style of styles) {
          this.emit(`${style.property}: ${style.value} !important;`)
        }
        this.indent--
        this.emit('}')
      }
    }

    // Recurse into children
    for (const child of node.children) {
      this.emitNodeStateCSS(child, systemStates)
    }
  }

  private emitCreateUI(): void {
    this.emit('export function createUI(data = {}) {')
    this.indent++

    this.emit('const _elements = {}')
    this.emit('const _state = { ...data }')
    this.emit('const _listeners = new Map()')
    this.emit('')

    // Generate root container
    this.emit('// Root container')
    this.emit("const _root = document.createElement('div')")
    this.emit("_root.className = 'mirror-root'")
    this.emit('')

    // Inject CSS (variables + system state styles)
    this.emitStyles()

    // Generate each node (first node is the main root)
    let isFirstNode = true
    for (const node of this.ir.nodes) {
      this.emitNode(node, '_root', isFirstNode)
      isFirstNode = false
    }

    this.emit('')
    this.emitPublicAPI()

    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitNode(node: IRNode, parentVar: string, isMainRoot = false): void {
    // Handle Zag components
    if (isIRZagNode(node)) {
      this.emitZagComponent(node, parentVar)
      return
    }

    // Handle each loop nodes
    if (node.each) {
      this.emitEachLoop(node.each, parentVar)
      return
    }

    // Handle conditional nodes
    if (node.conditional) {
      this.emitConditional(node.conditional, parentVar)
      return
    }

    const varName = this.sanitizeVarName(node.id)

    this.emit(`// ${node.name || node.tag}`)
    this.emit(`const ${varName} = document.createElement('${node.tag}')`)
    this.emit(`_elements['${node.id}'] = ${varName}`)
    this.emit(`${varName}.dataset.mirrorId = '${node.id}'`)
    // Mark main root element (cannot be moved via drag-drop)
    if (isMainRoot) {
      this.emit(`${varName}.dataset.mirrorRoot = 'true'`)
    }
    // Component name for breadcrumb navigation
    if (node.name) {
      this.emit(`${varName}.dataset.mirrorName = '${node.name}'`)
    }

    // Instance name for external access
    if (node.instanceName) {
      this.emit(`_elements['${node.instanceName}'] = ${varName}`)
    }

    // Detect if this is an icon or slot element (based on primitive type)
    const isIcon = node.primitive === 'icon'
    const isSlot = node.primitive === 'slot'
    let iconName: string | null = null

    // Set HTML properties
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(prop.value)}"` : prop.value
        // For icons, store the name for loading instead of setting textContent
        if (isIcon && typeof prop.value === 'string') {
          iconName = prop.value
        } else if (isSlot) {
          // Skip textContent for slots - we create a label element instead below
        } else {
          this.emit(`${varName}.textContent = ${value}`)
        }
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(String(prop.value))}"` : prop.value
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Load icon from CDN if this is an icon element
    if (isIcon && iconName) {
      this.emit(`// Load Lucide icon`)
      this.emit(`_runtime.loadIcon(${varName}, "${this.escapeString(iconName)}")`)
    }

    // Handle Slot primitive - visual placeholder for drag & drop
    if (isSlot) {
      // Get slot label from textContent property
      const labelProp = node.properties.find(p => p.name === 'textContent')
      const slotLabel = labelProp ? String(labelProp.value) : 'Slot'

      this.emit(`// Slot placeholder`)
      this.emit(`${varName}.dataset.mirrorSlot = 'true'`)
      this.emit(`${varName}.dataset.slotLabel = "${this.escapeString(slotLabel)}"`)
      this.emit(`${varName}.classList.add('mirror-slot')`)

      // Create label element
      this.emit(`const ${varName}_label = document.createElement('span')`)
      this.emit(`${varName}_label.className = 'mirror-slot-label'`)
      this.emit(`${varName}_label.textContent = "${this.escapeString(slotLabel)}"`)
      this.emit(`${varName}.appendChild(${varName}_label)`)
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        this.emit(`'${style.property}': '${style.value}',`)
      }
      this.indent--
      this.emit('})')
    }

    // Set data-layout for drop strategy detection
    // This is the primary way to identify layout type in the DOM
    if (node.layoutType) {
      this.emit(`${varName}.dataset.layout = '${node.layoutType}'`)
    }

    // Mark abs containers (fallback for older IR or when layoutType not set)
    // We detect this by checking if the element has position: relative but NOT flex/grid display
    // (flex containers also need position: relative for stacked layouts, so we need to be careful)
    const hasPositionRelative = baseStyles.some(s => s.property === 'position' && s.value === 'relative')
    const hasFlexDisplay = baseStyles.some(s => s.property === 'display' && (s.value === 'flex' || s.value === 'grid'))
    if (hasPositionRelative && !hasFlexDisplay && !node.layoutType) {
      this.emit(`${varName}.dataset.mirrorAbs = 'true'`)
    }

    // Store state styles for runtime (excluding CSS-handled system states)
    const cssStates = new Set(['hover', 'focus', 'active', 'disabled'])
    const behaviorStyles = node.styles.filter(s => s.state && !cssStates.has(s.state))
    if (behaviorStyles.length > 0) {
      this.emit(`${varName}._stateStyles = {`)
      this.indent++
      const byState = this.groupByState(behaviorStyles)
      for (const [state, styles] of Object.entries(byState)) {
        this.emit(`'${state}': {`)
        this.indent++
        for (const style of styles) {
          this.emit(`'${style.property}': '${style.value}',`)
        }
        this.indent--
        this.emit('},')
      }
      this.indent--
      this.emit('}')
    }

    // Initial state
    if (node.initialState) {
      this.emit(`${varName}.dataset.state = '${node.initialState}'`)
      this.emit(`${varName}._initialState = '${node.initialState}'`)
    }

    // Visible when state condition
    if (node.visibleWhen) {
      this.emit(`${varName}._visibleWhen = '${node.visibleWhen}'`)
      this.emit(`// Initially hidden until parent state matches`)
      this.emit(`${varName}.style.display = 'none'`)
    }

    // Selection binding
    if (node.selection) {
      const selectionVar = node.selection.startsWith('$') ? node.selection.slice(1) : node.selection
      this.emit(`${varName}._selectionBinding = '${selectionVar}'`)
    }

    // Component name (for navigation targets)
    if (node.name) {
      this.emit(`${varName}.dataset.component = '${node.name}'`)
    }

    // Route (for navigation)
    if (node.route) {
      this.emit(`${varName}.dataset.route = '${node.route}'`)
    }

    // Add event listeners
    // Check if there are keyboard events and make element focusable
    const hasKeyboardEvents = node.events.some(e => e.key || e.name === 'keydown' || e.name === 'keyup')
    if (hasKeyboardEvents) {
      this.emit(`${varName}.setAttribute('tabindex', '0')`)
    }
    for (const event of node.events) {
      this.emitEventListener(varName, event)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitNode(child, varName)
    }

    // Auto-set parent to relative if this element is absolute positioned
    // Only if parent doesn't already have position/layout set
    const hasPositionAbsolute = baseStyles.some(s => s.property === 'position' && s.value === 'absolute')
    if (hasPositionAbsolute && parentVar !== '_root') {
      this.emit(`// Auto-set parent to relative for absolute child`)
      this.emit(`if (${parentVar}.style.position !== 'relative' && ${parentVar}.style.position !== 'absolute' && ${parentVar}.style.position !== 'fixed') {`)
      this.indent++
      this.emit(`${parentVar}.style.position = 'relative'`)
      // Only set mirrorAbs if parent doesn't have explicit data-layout
      this.emit(`if (!${parentVar}.dataset.layout) ${parentVar}.dataset.mirrorAbs = 'true'`)
      this.indent--
      this.emit(`}`)
    }

    // Append to parent
    this.emit(`${parentVar}.appendChild(${varName})`)
    this.emit('')
  }

  private emitEachLoop(each: IREach, parentVar: string): void {
    const containerId = this.sanitizeVarName(each.id)
    // Strip $ prefix for valid JavaScript variable names
    const itemVar = each.itemVar.startsWith('$') ? each.itemVar.slice(1) : each.itemVar
    const collection = each.collection.startsWith('$') ? each.collection.slice(1) : each.collection

    this.emit(`// Each loop: ${itemVar} in ${collection}`)
    this.emit(`const ${containerId}_container = document.createElement('div')`)
    this.emit(`${containerId}_container.dataset.eachContainer = '${each.id}'`)
    this.emit('')

    // Store template factory for runtime updates
    this.emit(`_elements['${each.id}'] = ${containerId}_container`)
    this.emit(`${containerId}_container._eachConfig = {`)
    this.indent++
    this.emit(`itemVar: '${itemVar}',`)
    this.emit(`collection: '${collection}',`)
    if (each.filter) {
      this.emit(`filter: ${JSON.stringify(each.filter)},`)
    }
    this.emit(`renderItem: (${itemVar}, index) => {`)
    this.indent++

    // Create a container for each item
    this.emit(`const itemContainer = document.createElement('div')`)
    this.emit(`itemContainer.dataset.eachItem = index`)

    // Render template nodes
    for (const templateNode of each.template) {
      this.emitEachTemplateNode(templateNode, 'itemContainer', itemVar)
    }

    this.emit(`return itemContainer`)
    this.indent--
    this.emit('},')
    this.indent--
    this.emit('}')
    this.emit('')

    // Initial render with data
    this.emit(`// Initial render`)
    this.emit(`const ${collection}Data = data['${collection}'] || []`)
    if (each.filter) {
      this.emit(`const ${collection}Filtered = ${collection}Data.filter(${itemVar} => ${each.filter})`)
      this.emit(`${collection}Filtered.forEach((${itemVar}, index) => {`)
    } else {
      this.emit(`${collection}Data.forEach((${itemVar}, index) => {`)
    }
    this.indent++
    this.emit(`${containerId}_container.appendChild(${containerId}_container._eachConfig.renderItem(${itemVar}, index))`)
    this.indent--
    this.emit('})')
    this.emit('')

    this.emit(`${parentVar}.appendChild(${containerId}_container)`)
    this.emit('')
  }

  private emitConditional(cond: IRConditional, parentVar: string): void {
    const containerId = this.sanitizeVarName(cond.id)

    this.emit(`// Conditional`)
    this.emit(`const ${containerId}_container = document.createElement('div')`)
    this.emit(`${containerId}_container.dataset.conditionalId = '${cond.id}'`)
    this.emit(`_elements['${cond.id}'] = ${containerId}_container`)
    this.emit('')

    // Store conditional config for reactive updates
    this.emit(`${containerId}_container._conditionalConfig = {`)
    this.indent++
    this.emit(`condition: () => ${cond.condition},`)
    this.emit(`renderThen: () => {`)
    this.indent++
    this.emit(`const fragment = document.createDocumentFragment()`)
    for (const node of cond.then) {
      this.emitConditionalTemplateNode(node, 'fragment')
    }
    this.emit(`return fragment`)
    this.indent--
    this.emit(`},`)
    if (cond.else && cond.else.length > 0) {
      this.emit(`renderElse: () => {`)
      this.indent++
      this.emit(`const fragment = document.createDocumentFragment()`)
      for (const node of cond.else) {
        this.emitConditionalTemplateNode(node, 'fragment')
      }
      this.emit(`return fragment`)
      this.indent--
      this.emit(`},`)
    }
    this.indent--
    this.emit(`}`)
    this.emit('')

    // Initial render based on condition
    this.emit(`// Initial conditional render`)
    this.emit(`if (${cond.condition}) {`)
    this.indent++
    this.emit(`${containerId}_container.appendChild(${containerId}_container._conditionalConfig.renderThen())`)
    this.indent--
    if (cond.else && cond.else.length > 0) {
      this.emit(`} else {`)
      this.indent++
      this.emit(`${containerId}_container.appendChild(${containerId}_container._conditionalConfig.renderElse())`)
      this.indent--
    }
    this.emit(`}`)
    this.emit('')

    this.emit(`${parentVar}.appendChild(${containerId}_container)`)
    this.emit('')
  }

  private emitZagComponent(node: IRZagNode, parentVar: string): void {
    const varName = this.sanitizeVarName(node.id)

    this.emit(`// Zag Component: ${node.name} (${node.zagType})`)
    this.emit(`const ${varName} = document.createElement('div')`)
    this.emit(`_elements['${node.id}'] = ${varName}`)
    this.emit(`${varName}.dataset.mirrorId = '${node.id}'`)
    this.emit(`${varName}.dataset.zagComponent = '${node.zagType}'`)
    if (node.name) {
      this.emit(`${varName}.dataset.mirrorName = '${node.name}'`)
    }

    // Emit machine configuration
    this.emit(`${varName}._zagConfig = {`)
    this.indent++
    this.emit(`type: '${node.zagType}',`)
    this.emit(`id: '${node.id}',`)
    this.emit(`machineConfig: ${JSON.stringify(node.machineConfig)},`)

    // Emit slot definitions
    this.emit(`slots: {`)
    this.indent++
    for (const [slotName, slot] of Object.entries(node.slots)) {
      this.emit(`'${slotName}': {`)
      this.indent++
      this.emit(`apiMethod: '${slot.apiMethod}',`)
      this.emit(`element: '${slot.element}',`)
      this.emit(`portal: ${slot.portal || false},`)
      this.emit(`styles: ${JSON.stringify(slot.styles)},`)
      this.indent--
      this.emit(`},`)
    }
    this.indent--
    this.emit(`},`)

    // Emit items
    this.emit(`items: ${JSON.stringify(node.items)},`)
    this.indent--
    this.emit(`}`)
    this.emit('')

    // Create slot elements
    for (const [slotName, slot] of Object.entries(node.slots)) {
      const slotVar = `${varName}_${slotName.toLowerCase()}`
      this.emit(`// Slot: ${slotName}`)
      this.emit(`const ${slotVar} = document.createElement('${slot.element}')`)
      this.emit(`${slotVar}.dataset.slot = '${slotName}'`)
      this.emit(`${slotVar}.dataset.mirrorSlot = '${node.id}-${slotName}'`)

      // Apply base styles and mark as styled to prevent runtime defaults
      if (slot.styles.length > 0) {
        this.emit(`${slotVar}.setAttribute('data-styled', 'true')`)
        this.emit(`Object.assign(${slotVar}.style, {`)
        this.indent++
        for (const style of slot.styles) {
          this.emit(`'${style.property}': '${style.value}',`)
        }
        this.indent--
        this.emit('})')
      }

      // Append to root
      // Note: Even portal elements are appended initially - the runtime
      // can relocate them to a portal container if needed
      this.emit(`${varName}.appendChild(${slotVar})`)
      this.emit('')
    }

    // Create item elements for Content slot
    if (node.items.length > 0) {
      const contentSlotVar = `${varName}_content`
      this.emit(`// Items`)
      for (let i = 0; i < node.items.length; i++) {
        const item = node.items[i]
        const itemVar = `${varName}_item${i}`
        this.emit(`const ${itemVar} = document.createElement('div')`)
        this.emit(`${itemVar}.dataset.mirrorItem = '${item.value}'`)
        if (item.disabled) {
          this.emit(`${itemVar}.dataset.disabled = 'true'`)
        }
        // Apply item layout properties if present
        if (item.properties && item.properties.length > 0) {
          for (const prop of item.properties) {
            const propName = prop.name
            // Handle layout properties
            if (propName === 'ver' || propName === 'vertical') {
              this.emit(`${itemVar}.style.display = 'flex'`)
              this.emit(`${itemVar}.style.flexDirection = 'column'`)
            } else if (propName === 'hor' || propName === 'horizontal') {
              this.emit(`${itemVar}.style.display = 'flex'`)
              this.emit(`${itemVar}.style.flexDirection = 'row'`)
            } else if (propName === 'gap' || propName === 'g') {
              const gapValue = prop.values[0]
              this.emit(`${itemVar}.style.gap = '${gapValue}px'`)
            } else if (propName === 'pad' || propName === 'p' || propName === 'padding') {
              const padValues = prop.values
              if (padValues.length === 1) {
                this.emit(`${itemVar}.style.padding = '${padValues[0]}px'`)
              } else if (padValues.length === 2) {
                this.emit(`${itemVar}.style.padding = '${padValues[0]}px ${padValues[1]}px'`)
              } else if (padValues.length === 4) {
                this.emit(`${itemVar}.style.padding = '${padValues[0]}px ${padValues[1]}px ${padValues[2]}px ${padValues[3]}px'`)
              }
            } else if (propName === 'spread') {
              this.emit(`${itemVar}.style.display = 'flex'`)
              this.emit(`${itemVar}.style.justifyContent = 'space-between'`)
            } else if (propName === 'center') {
              this.emit(`${itemVar}.style.display = 'flex'`)
              this.emit(`${itemVar}.style.alignItems = 'center'`)
              this.emit(`${itemVar}.style.justifyContent = 'center'`)
            }
          }
        }
        // Render children if present, otherwise use label as text
        if (item.children && item.children.length > 0) {
          // Default to horizontal layout with centered alignment if no explicit layout
          const hasLayoutProp = item.properties?.some((p: any) =>
            ['ver', 'hor', 'vertical', 'horizontal', 'spread', 'center'].includes(p.name)
          )
          if (!hasLayoutProp) {
            this.emit(`${itemVar}.style.display = 'flex'`)
            this.emit(`${itemVar}.style.alignItems = 'center'`)
            this.emit(`${itemVar}.style.gap = '8px'`)
          }
          for (const child of item.children) {
            this.emitNode(child, itemVar)
          }
        } else {
          this.emit(`${itemVar}.textContent = '${this.escapeString(item.label)}'`)
        }
        this.emit(`${contentSlotVar}.appendChild(${itemVar})`)
      }
      this.emit('')
    }

    // Append to parent
    this.emit(`${parentVar}.appendChild(${varName})`)
    this.emit('')

    // Initialize Zag component via runtime
    this.emit(`// Initialize Zag machine`)
    this.emit(`if (typeof _runtime !== 'undefined' && _runtime.initZagComponent) {`)
    this.indent++
    this.emit(`_runtime.initZagComponent(${varName})`)
    this.indent--
    this.emit(`}`)
    this.emit('')
  }

  private emitConditionalTemplateNode(node: IRNode, parentVar: string): void {
    // Handle nested conditionals
    if (node.conditional) {
      const nestedId = this.sanitizeVarName(node.conditional.id)
      this.emit(`// Nested conditional`)
      this.emit(`const ${nestedId}_nested = document.createElement('div')`)
      this.emit(`if (${node.conditional.condition}) {`)
      this.indent++
      for (const child of node.conditional.then) {
        this.emitConditionalTemplateNode(child, `${nestedId}_nested`)
      }
      this.indent--
      if (node.conditional.else && node.conditional.else.length > 0) {
        this.emit(`} else {`)
        this.indent++
        for (const child of node.conditional.else) {
          this.emitConditionalTemplateNode(child, `${nestedId}_nested`)
        }
        this.indent--
      }
      this.emit(`}`)
      this.emit(`${parentVar}.appendChild(${nestedId}_nested)`)
      return
    }

    // Handle each loops inside conditionals
    if (node.each) {
      this.emitEachLoop(node.each, parentVar)
      return
    }

    const varName = this.sanitizeVarName(node.id) + '_cond'

    this.emit(`const ${varName} = document.createElement('${node.tag}')`)
    this.emit(`${varName}.dataset.mirrorId = '${node.id}'`)
    if (node.name) {
      this.emit(`${varName}.dataset.mirrorName = '${node.name}'`)
    }

    // Set HTML properties
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(prop.value)}"` : prop.value
        this.emit(`${varName}.textContent = ${value}`)
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = typeof prop.value === 'string' ? `"${this.escapeString(String(prop.value))}"` : prop.value
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        this.emit(`'${style.property}': '${style.value}',`)
      }
      this.indent--
      this.emit('})')
    }

    // Add event listeners
    for (const event of node.events) {
      this.emitEventListener(varName, event)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitConditionalTemplateNode(child, varName)
    }

    this.emit(`${parentVar}.appendChild(${varName})`)
  }

  private emitEachTemplateNode(node: IRNode, parentVar: string, itemVar: string): void {
    const varName = this.sanitizeVarName(node.id) + '_tpl'

    this.emit(`const ${varName} = document.createElement('${node.tag}')`)
    // Index appended for uniqueness: node-5[0], node-5[1], etc.
    this.emit(`${varName}.dataset.mirrorId = '${node.id}[' + index + ']'`)
    if (node.name) {
      this.emit(`${varName}.dataset.mirrorName = '${node.name}'`)
    }

    // Set HTML properties (with data binding)
    for (const prop of node.properties) {
      if (prop.name === 'textContent') {
        const value = this.resolveTemplateValue(prop.value, itemVar)
        this.emit(`${varName}.textContent = ${value}`)
      } else if (prop.name === 'disabled' || prop.name === 'hidden') {
        this.emit(`${varName}.${prop.name} = ${prop.value}`)
      } else {
        const value = this.resolveTemplateValue(prop.value, itemVar)
        this.emit(`${varName}.setAttribute('${prop.name}', ${value})`)
      }
    }

    // Apply base styles
    const baseStyles = node.styles.filter(s => !s.state)
    if (baseStyles.length > 0) {
      this.emit(`Object.assign(${varName}.style, {`)
      this.indent++
      for (const style of baseStyles) {
        const value = this.resolveTemplateStyleValue(style.value, itemVar)
        this.emit(`'${style.property}': ${value},`)
      }
      this.indent--
      this.emit('})')
    }

    // Add event listeners
    for (const event of node.events) {
      this.emitTemplateEventListener(varName, event, itemVar)
    }

    // Recursively emit children
    for (const child of node.children) {
      this.emitEachTemplateNode(child, varName, itemVar)
    }

    this.emit(`${parentVar}.appendChild(${varName})`)
  }

  private resolveTemplateValue(value: string | number | boolean, itemVar: string): string {
    if (typeof value === 'string') {
      // Check if value contains item variable reference like $task.title
      if (value.includes(`$${itemVar}.`) || value.includes(`\${${itemVar}.`)) {
        // Convert $task.title to task.title
        const resolved = value.replace(new RegExp(`\\$${itemVar}\\.`, 'g'), `${itemVar}.`)
        return resolved
      }
      // Check for plain item reference $task -> task
      if (value === `$${itemVar}`) {
        return itemVar
      }
      return `"${this.escapeString(String(value))}"`
    }
    return String(value)
  }

  private resolveTemplateStyleValue(value: string, itemVar: string): string {
    // Check if value contains item variable reference
    if (value.includes(`$${itemVar}.`) || value.includes(`\${${itemVar}.`)) {
      const resolved = value.replace(new RegExp(`\\$${itemVar}\\.`, 'g'), `${itemVar}.`)
      return resolved
    }
    return `'${value}'`
  }

  private emitTemplateEventListener(varName: string, event: IREvent, itemVar: string): void {
    const eventName = event.name

    this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
    this.indent++
    for (const action of event.actions) {
      this.emitTemplateAction(action, varName, itemVar)
    }
    this.indent--
    this.emit('})')
  }

  private emitTemplateAction(action: IRAction, currentVar: string, itemVar: string): void {
    const target = action.target || 'self'

    switch (action.type) {
      case 'toggle':
        this.emit(`_runtime.toggle(_elements['${target}'] || ${currentVar})`)
        break
      case 'select':
        this.emit(`_runtime.select(${currentVar})`)
        break
      case 'assign':
        // Handle assign $selected to $item
        if (action.args && action.args[0] === `$${itemVar}`) {
          const stateVar = target.startsWith('$') ? target.slice(1) : target
          this.emit(`_state['${stateVar}'] = ${itemVar}`)
          this.emit(`api.update()`)
        }
        break
      default:
        this.emit(`// TODO: Template action '${action.type}' not implemented`)
    }
  }

  private emitEventListener(varName: string, event: IREvent): void {
    const eventName = event.name

    // Handle enter/exit events with IntersectionObserver
    if (eventName === 'enter' || eventName === 'exit') {
      this.emitEnterExitObserver(varName, event, eventName === 'enter')
      return
    }

    // Handle hover event specially - needs both mouseenter and mouseleave
    if (eventName === 'mouseenter') {
      const hasHighlight = event.actions.some(a => a.type === 'highlight')
      if (hasHighlight) {
        this.emit(`${varName}.addEventListener('mouseenter', (e) => {`)
        this.indent++
        for (const action of event.actions) {
          this.emitAction(action, varName)
        }
        this.indent--
        this.emit('})')
        // Add mouseleave to clear highlight
        this.emit(`${varName}.addEventListener('mouseleave', (e) => {`)
        this.indent++
        this.emit(`_runtime.unhighlight(${varName})`)
        this.indent--
        this.emit('})')
        return
      }
    }

    // Handle click-outside event specially
    if (eventName === 'click-outside') {
      this.emit(`// Click outside handler`)
      this.emit(`const ${varName}_clickOutsideHandler = (e) => {`)
      this.indent++
      this.emit(`if (!${varName}.contains(e.target)) {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('}')
      this.indent--
      this.emit('}')
      this.emit(`document.addEventListener('click', ${varName}_clickOutsideHandler)`)
      this.emit(`${varName}._clickOutsideHandler = ${varName}_clickOutsideHandler`)
      return
    }

    // Handle keyboard events with specific keys
    if (event.key) {
      this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
      this.indent++
      this.emit(`if (e.key === '${this.mapKeyName(event.key)}') {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('}')
      this.indent--
      this.emit('})')
    } else {
      this.emit(`${varName}.addEventListener('${eventName}', (e) => {`)
      this.indent++
      for (const action of event.actions) {
        this.emitAction(action, varName)
      }
      this.indent--
      this.emit('})')
    }
  }

  private emitEnterExitObserver(varName: string, event: IREvent, isEnter: boolean): void {
    // Generate a unique callback function for this observer
    const callbackName = `${varName}_${isEnter ? 'enter' : 'exit'}`

    this.emit(`// ${isEnter ? 'Enter' : 'Exit'} viewport observer`)
    this.emit(`const ${callbackName}Callback = () => {`)
    this.indent++
    for (const action of event.actions) {
      this.emitAction(action, varName)
    }
    this.indent--
    this.emit(`}`)

    if (isEnter) {
      // Store enter callback for observer setup
      this.emit(`${varName}._enterCallback = ${callbackName}Callback`)
    } else {
      // Store exit callback for observer setup
      this.emit(`${varName}._exitCallback = ${callbackName}Callback`)
    }

    // Set up observer (only once when we have at least one callback)
    this.emit(`if (!${varName}._enterExitObserver) {`)
    this.indent++
    this.emit(`_runtime.setupEnterExitObserver(${varName}, ${varName}._enterCallback, ${varName}._exitCallback)`)
    this.indent--
    this.emit(`}`)
  }

  private emitAction(action: IRAction, currentVar: string): void {
    const target = action.target || 'self'

    // Known built-in actions
    const builtinActions = new Set([
      'toggle', 'show', 'hide', 'select', 'deselect', 'highlight',
      'activate', 'deactivate', 'call', 'assign', 'page', 'open', 'close',
      'filter', 'validate', 'reset', 'focus', 'alert', 'clear-selection',
      'deactivate-siblings', 'toggle-state', 'set-state', 'change', 'navigate',
      'animate'
    ])

    switch (action.type) {
      case 'toggle':
        this.emit(`_runtime.toggle(_elements['${target}'] || ${currentVar})`)
        break
      case 'show':
        this.emit(`_runtime.show(_elements['${target}'] || ${currentVar})`)
        break
      case 'hide':
        this.emit(`_runtime.hide(_elements['${target}'] || ${currentVar})`)
        break
      case 'close':
        // close sets state to "closed" for toggle elements, otherwise hides
        this.emit(`_runtime.close(_elements['${target}'] || ${currentVar})`)
        break
      case 'select':
        if (target === 'highlighted') {
          this.emit(`_runtime.selectHighlighted(${currentVar})`)
        } else {
          this.emit(`_runtime.select(_elements['${target}'] || ${currentVar})`)
        }
        break
      case 'deselect':
        this.emit(`_runtime.deselect(_elements['${target}'] || ${currentVar})`)
        break
      case 'highlight':
        if (target === 'next') {
          this.emit(`_runtime.highlightNext(${currentVar})`)
        } else if (target === 'prev') {
          this.emit(`_runtime.highlightPrev(${currentVar})`)
        } else if (target === 'first') {
          this.emit(`_runtime.highlightFirst(${currentVar})`)
        } else if (target === 'last') {
          this.emit(`_runtime.highlightLast(${currentVar})`)
        } else {
          this.emit(`_runtime.highlight(_elements['${target}'] || ${currentVar})`)
        }
        break
      case 'activate':
        this.emit(`_runtime.activate(_elements['${target}'] || ${currentVar})`)
        break
      case 'deactivate':
        this.emit(`_runtime.deactivate(_elements['${target}'] || ${currentVar})`)
        break
      case 'toggle-state':
        // toggle-state Target or toggle-state Target stateName
        const stateArg = action.args?.[0] || 'on'
        this.emit(`_runtime.toggleState(_elements['${target}'] || ${currentVar}, '${stateArg}')`)
        break
      case 'set-state':
        // set-state Target stateName
        const newState = action.args?.[0] || 'default'
        this.emit(`_runtime.setState(_elements['${target}'] || ${currentVar}, '${newState}')`)
        break
      case 'call':
        const fnName = action.target || ''
        const args = action.args?.map(a => `"${a}"`).join(', ') || ''
        this.emit(`if (typeof ${fnName} === 'function') ${fnName}(${args})`)
        break
      case 'navigate':
        // Navigate to a target component or page
        // Lowercase = page route (load file), Uppercase = component route
        const isPageRoute = /^[a-z]/.test(target)
        if (isPageRoute) {
          this.emit(`_runtime.navigateToPage('${target}', ${currentVar})`)
        } else {
          this.emit(`_runtime.navigate('${target}', ${currentVar})`)
        }
        break
      case 'animate':
        // Animate action: animate AnimationName or animate AnimationName target1, target2
        const animationName = action.target || ''
        if (action.args && action.args.length > 0) {
          // Multiple targets specified
          const targets = action.args.map(t => `_elements['${t}']`).join(', ')
          // Check for stagger option
          const staggerMatch = action.args.find(a => a.startsWith('stagger'))
          if (staggerMatch) {
            const staggerValue = staggerMatch.replace('stagger', '').trim() || '100'
            const elemTargets = action.args.filter(a => !a.startsWith('stagger')).map(t => `_elements['${t}']`).join(', ')
            this.emit(`_runtime.animate('${animationName}', [${elemTargets}], { stagger: ${staggerValue} })`)
          } else {
            this.emit(`_runtime.animate('${animationName}', [${targets}])`)
          }
        } else {
          // Animate self
          this.emit(`_runtime.animate('${animationName}', ${currentVar})`)
        }
        break
      default:
        // Unknown action = treat as direct function call
        // This allows: onclick addTask -> calls addTask()
        if (!builtinActions.has(action.type)) {
          const funcName = action.type
          const funcArgs = action.target ? `"${action.target}"` : ''
          this.emit(`if (typeof ${funcName} === 'function') ${funcName}(${funcArgs})`)
        } else {
          this.emit(`// TODO: Action '${action.type}' not implemented`)
        }
    }
  }

  private emitPublicAPI(): void {
    this.emit('// Public API')
    this.emit('const api = {')
    this.indent++

    this.emit('root: _root,')
    this.emit('')

    // Generate accessors for named instances
    const namedNodes = this.collectNamedNodes(this.ir.nodes)
    for (const node of namedNodes) {
      this.emit(`get ${node.instanceName}() {`)
      this.indent++
      this.emit(`return _runtime.wrap(_elements['${node.instanceName}'])`)
      this.indent--
      this.emit('},')
    }

    this.emit('')
    this.emit('// State management')
    this.emit('setState(key, value) {')
    this.indent++
    this.emit('_state[key] = value')
    this.emit('this.update()')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('getState(key) {')
    this.indent++
    this.emit('return _state[key]')
    this.indent--
    this.emit('},')
    this.emit('')

    this.emit('update() {')
    this.indent++
    this.emit('// Re-render each loops based on state changes')
    this.emit("for (const el of _root.querySelectorAll('[data-each-container]')) {")
    this.indent++
    this.emit('if (el._eachConfig) {')
    this.indent++
    this.emit('const { collection, renderItem, filter } = el._eachConfig')
    this.emit('const items = _state[collection] || []')
    this.emit('const filtered = filter ? items.filter(item => eval(filter)) : items')
    this.emit('el.innerHTML = ""')
    this.emit('filtered.forEach((item, index) => el.appendChild(renderItem(item, index)))')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// Re-render conditionals based on state changes')
    this.emit("for (const el of _root.querySelectorAll('[data-conditional-id]')) {")
    this.indent++
    this.emit('if (el._conditionalConfig) {')
    this.indent++
    this.emit('const { condition, renderThen, renderElse } = el._conditionalConfig')
    this.emit('el.innerHTML = ""')
    this.emit('if (condition()) {')
    this.indent++
    this.emit('el.appendChild(renderThen())')
    this.indent--
    this.emit('} else if (renderElse) {')
    this.indent++
    this.emit('el.appendChild(renderElse())')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('}')
    this.indent--
    this.emit('},')

    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('return api')
  }


  private emitRuntime(): void {
    // Emit the pre-built runtime code from separate module
    // This replaces ~778 lines of inline code generation
    this.emitRaw(DOM_RUNTIME_CODE)
    this.emit('')
  }

  private sanitizeVarName(id: string): string {
    return id.replace(/-/g, '_')
  }

  private escapeString(str: string): string {
    return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')
  }

  private mapKeyName(key: string): string {
    const mapping: Record<string, string> = {
      'escape': 'Escape',
      'enter': 'Enter',
      'tab': 'Tab',
      'space': ' ',
      'arrow-up': 'ArrowUp',
      'arrow-down': 'ArrowDown',
      'arrow-left': 'ArrowLeft',
      'arrow-right': 'ArrowRight',
      'backspace': 'Backspace',
      'delete': 'Delete',
    }
    return mapping[key] || key
  }

  private groupByState(styles: IRStyle[]): Record<string, IRStyle[]> {
    const result: Record<string, IRStyle[]> = {}
    for (const style of styles) {
      const state = style.state || 'default'
      if (!result[state]) result[state] = []
      result[state].push(style)
    }
    return result
  }

  private collectNamedNodes(nodes: IRNode[]): IRNode[] {
    const result: IRNode[] = []
    for (const node of nodes) {
      if (node.instanceName) {
        result.push(node)
      }
      result.push(...this.collectNamedNodes(node.children))
    }
    return result
  }

  private emitInitialization(): void {
    const namedNodes = this.collectNamedNodes(this.ir.nodes)

    this.emit('// ============================================')
    this.emit('// Auto-initialization (Mirror + JavaScript)')
    this.emit('// ============================================')
    this.emit('')

    // Create UI instance
    this.emit('const _ui = createUI()')
    this.emit('')

    // Expose named instances as global variables
    if (namedNodes.length > 0) {
      this.emit('// Named instance proxies')
      for (const node of namedNodes) {
        this.emit(`const ${node.instanceName} = _ui.${node.instanceName}`)
      }
      this.emit('')
    }

    // Global update function
    this.emit('// Global update function')
    this.emit('function update() { _ui.update() }')
    this.emit('')

    // User JavaScript
    this.emit('// User JavaScript')
    if (this.javascript) {
      // Emit the JavaScript code as-is, preserving formatting
      for (const line of this.javascript.code.split('\n')) {
        this.emitRaw(line)
      }
    }
    this.emit('')

    // Auto-mount to body
    this.emit('// Mount to document')
    this.emit('document.body.appendChild(_ui.root)')
  }
}
