/**
 * Mirror Framework Backend
 *
 * Generates M() function calls that use the Mirror Runtime.
 * Output is idiomatic JavaScript that mirrors Mirror DSL 1:1.
 *
 * This backend enables:
 * 1. LLM-generated code that's identical to compiler output
 * 2. Deterministic reverse translation via M.toMirror()
 * 3. Smaller bundle size (runtime is separate)
 */

import type { AST } from '../parser/ast'
import { toIR } from '../ir'
import type { IR, IRNode, IRStyle, IREvent, IRAction, IREach, IRConditional } from '../ir/types'

/**
 * Generate M() framework calls from Mirror AST
 *
 * @example Output:
 * ```javascript
 * import { M } from 'mirror-runtime'
 *
 * export const ui = M('Box', { bg: '#1a1a23', pad: 16 }, [
 *   M('Text', 'Hello', { weight: 'bold' })
 * ])
 *
 * export function mount(container) {
 *   return M.render(ui, container)
 * }
 * ```
 */
export function generateFramework(ast: AST): string {
  const ir = toIR(ast)
  const generator = new FrameworkGenerator(ir)
  return generator.generate()
}

class FrameworkGenerator {
  private ir: IR
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR) {
    this.ir = ir
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitComponents()
    this.emitUI()
    this.emitMount()

    return this.lines.join('\n')
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitRaw(line: string): void {
    this.lines.push(line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (Framework Backend)')
    this.emit('// This code uses the Mirror Runtime for rendering')
    this.emit('')
    this.emit("import { M } from 'mirror-runtime'")
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('export const tokens = {')
    this.indent++
    for (const token of this.ir.tokens) {
      const value = typeof token.value === 'string' ? `'${token.value}'` : token.value
      this.emit(`'${token.name}': ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitComponents(): void {
    // Component definitions would be extracted from AST
    // For now, we skip this as components are resolved during IR transformation
  }

  private emitUI(): void {
    this.emit('// UI Tree')

    if (this.ir.nodes.length === 1) {
      // Single root node
      this.emit('export const ui = ' + this.nodeToM(this.ir.nodes[0]))
    } else if (this.ir.nodes.length > 1) {
      // Multiple root nodes - wrap in Box
      this.emit('export const ui = M(\'Box\', [')
      this.indent++
      for (let i = 0; i < this.ir.nodes.length; i++) {
        const comma = i < this.ir.nodes.length - 1 ? ',' : ''
        this.emit(this.nodeToM(this.ir.nodes[i]) + comma)
      }
      this.indent--
      this.emit('])')
    } else {
      this.emit('export const ui = M(\'Box\')')
    }

    this.emit('')
  }

  private emitMount(): void {
    this.emit('/**')
    this.emit(' * Mount UI to a container element')
    this.emit(' * @param {HTMLElement} container - The container to mount to')
    this.emit(' * @returns {MirrorUI} - UI controller with get(), destroy() methods')
    this.emit(' */')
    this.emit('export function mount(container) {')
    this.indent++
    this.emit('return M.render(ui, container)')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// For reverse translation to Mirror DSL:')
    this.emit('// console.log(M.toMirror(ui))')
  }

  /**
   * Convert IR node to M() call string
   */
  private nodeToM(node: IRNode): string {
    // Handle each loop
    if (node.each) {
      return this.eachToM(node.each)
    }

    // Handle conditional
    if (node.conditional) {
      return this.conditionalToM(node.conditional)
    }

    const parts: string[] = []

    // Type
    const type = this.getNodeType(node)
    parts.push(`'${type}'`)

    // Content (for Text, Icon, Button, Link)
    const content = this.getContent(node)

    // Props
    const props = this.nodeToProps(node)
    const propsStr = this.propsToString(props)

    // Children
    const children = node.children.map(c => this.nodeToM(c))
    const hasChildren = children.length > 0

    // Build M() call
    if (content && propsStr && hasChildren) {
      // M('Text', 'content', { props }, [children])
      return `M(${parts[0]}, '${this.escapeString(content)}', ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content && propsStr) {
      // M('Text', 'content', { props })
      return `M(${parts[0]}, '${this.escapeString(content)}', ${propsStr})`
    } else if (content && hasChildren) {
      // M('Text', 'content', [children])
      return `M(${parts[0]}, '${this.escapeString(content)}', [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content) {
      // M('Text', 'content')
      return `M(${parts[0]}, '${this.escapeString(content)}')`
    } else if (propsStr && hasChildren) {
      // M('Box', { props }, [children])
      return `M(${parts[0]}, ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (propsStr) {
      // M('Box', { props })
      return `M(${parts[0]}, ${propsStr})`
    } else if (hasChildren) {
      // M('Box', [children])
      return `M(${parts[0]}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else {
      // M('Box')
      return `M(${parts[0]})`
    }
  }

  private eachToM(each: IREach): string {
    const template = each.template.map(n => this.nodeToM(n))
    const templateStr = `[\n${this.indentLines(template.join(',\n'))}\n${this.currentIndent()}]`

    if (each.filter) {
      return `M.each('${each.itemVar}', '${each.collection}', ${templateStr}, '${each.filter}')`
    }
    return `M.each('${each.itemVar}', '${each.collection}', ${templateStr})`
  }

  private conditionalToM(cond: IRConditional): string {
    const thenBranch = cond.then.map(n => this.nodeToM(n))
    const thenStr = `[\n${this.indentLines(thenBranch.join(',\n'))}\n${this.currentIndent()}]`

    if (cond.else && cond.else.length > 0) {
      const elseBranch = cond.else.map(n => this.nodeToM(n))
      const elseStr = `[\n${this.indentLines(elseBranch.join(',\n'))}\n${this.currentIndent()}]`
      return `M.if('${cond.condition}', ${thenStr}, ${elseStr})`
    }

    return `M.if('${cond.condition}', ${thenStr})`
  }

  /**
   * Get the Mirror type name for a node
   */
  private getNodeType(node: IRNode): string {
    // Use component name if available, otherwise map tag to type
    if (node.name && node.name !== node.tag) {
      return node.name
    }

    // Map HTML tags back to Mirror primitives
    const tagToType: Record<string, string> = {
      div: 'Box',
      span: 'Text',
      button: 'Button',
      input: 'Input',
      textarea: 'Textarea',
      img: 'Image',
      a: 'Link',
    }

    // Check if it's an icon (by primitive type)
    if (node.primitive === 'icon') {
      return 'Icon'
    }

    return tagToType[node.tag] || node.name || 'Box'
  }

  /**
   * Extract content from node (for Text, Icon, Button, Link)
   */
  private getContent(node: IRNode): string | null {
    const textContent = node.properties.find(p => p.name === 'textContent')
    if (textContent && typeof textContent.value === 'string') {
      return textContent.value
    }
    return null
  }

  /**
   * Convert node styles, events, and properties to props object
   */
  private nodeToProps(node: IRNode): Record<string, any> {
    const props: Record<string, any> = {}

    // Instance name
    if (node.instanceName) {
      props.named = node.instanceName
    }

    // Initial state
    if (node.initialState) {
      props.state = node.initialState
    }

    // Visible when
    if (node.visibleWhen) {
      props['visible-when'] = node.visibleWhen
    }

    // Route
    if (node.route) {
      props.route = node.route
    }

    // Selection
    if (node.selection) {
      props.selection = node.selection
    }

    // Convert IR styles to props
    this.stylesToProps(node.styles, props)

    // Convert IR events to props
    this.eventsToProps(node.events, props)

    // Add HTML properties (except textContent which is handled as content)
    for (const prop of node.properties) {
      if (prop.name !== 'textContent') {
        if (prop.name === 'placeholder' || prop.name === 'href' || prop.name === 'src' || prop.name === 'type') {
          props[prop.name] = prop.value
        } else if (prop.name === 'hidden' || prop.name === 'disabled') {
          props[prop.name] = true
        } else if (prop.name.startsWith('data-icon-')) {
          // Convert data-icon-* to icon properties
          const iconProp = prop.name.replace('data-icon-', '')
          if (iconProp === 'size') props.is = prop.value
          else if (iconProp === 'color') props.ic = prop.value
          else if (iconProp === 'weight') props.iw = prop.value
        }
      }
    }

    return props
  }

  /**
   * Convert IR styles to Mirror props
   */
  private stylesToProps(styles: IRStyle[], props: Record<string, any>): void {
    // Group styles by state
    const baseStyles = styles.filter(s => !s.state)
    const stateStyles = styles.filter(s => s.state)

    // Check for flex: 1 1 0% pattern (used for w full / h full)
    const hasFlexFull = baseStyles.some(s => s.property === 'flex' && (s.value === '1 1 0%' || s.value === '1'))
    const hasMinWidth0 = baseStyles.some(s => s.property === 'min-width' && s.value === '0')
    const hasMinHeight0 = baseStyles.some(s => s.property === 'min-height' && s.value === '0')

    // Convert flex: 1 1 0% + min-width: 0 to w: 'full'
    if (hasFlexFull && hasMinWidth0) {
      props.w = 'full'
    }
    // Convert flex: 1 1 0% + min-height: 0 to h: 'full'
    if (hasFlexFull && hasMinHeight0) {
      props.h = 'full'
    }

    // Convert base styles to props
    for (const style of baseStyles) {
      // Skip flex and min-width/min-height that were handled above
      if (hasFlexFull && hasMinWidth0 && (style.property === 'flex' || style.property === 'min-width')) continue
      if (hasFlexFull && hasMinHeight0 && (style.property === 'flex' || style.property === 'min-height')) continue

      const mirrorProp = this.cssPropToMirrorProp(style.property, style.value)
      if (mirrorProp) {
        props[mirrorProp.name] = mirrorProp.value
      }
    }

    // Convert state styles to states object
    if (stateStyles.length > 0) {
      const states: Record<string, Record<string, any>> = {}

      for (const style of stateStyles) {
        if (!states[style.state!]) {
          states[style.state!] = {}
        }
        const mirrorProp = this.cssPropToMirrorProp(style.property, style.value)
        if (mirrorProp) {
          states[style.state!][mirrorProp.name] = mirrorProp.value
        }
      }

      props.states = states
    }
  }

  /**
   * Map CSS property/value back to Mirror property
   */
  private cssPropToMirrorProp(prop: string, value: string): { name: string; value: any } | null {
    // Layout
    if (prop === 'display' && value === 'flex') return null // Implicit
    if (prop === 'flex-direction' && value === 'row') return { name: 'hor', value: true }
    if (prop === 'flex-direction' && value === 'column') return null // Default
    if (prop === 'gap') return { name: 'gap', value: this.parsePxValue(value) }
    if (prop === 'justify-content' && value === 'space-between') return { name: 'spread', value: true }
    if (prop === 'flex-wrap' && value === 'wrap') return { name: 'wrap', value: true }

    // Alignment
    if (prop === 'justify-content' && value === 'center') return { name: 'center', value: true }
    if (prop === 'align-items' && value === 'center') return { name: 'center', value: true }

    // Sizing
    if (prop === 'width') {
      if (value === '100%') return { name: 'w', value: 'full' }
      if (value === 'fit-content') return { name: 'w', value: 'hug' }
      return { name: 'w', value: this.parsePxValue(value) }
    }
    if (prop === 'height') {
      if (value === '100%') return { name: 'h', value: 'full' }
      if (value === 'fit-content') return { name: 'h', value: 'hug' }
      return { name: 'h', value: this.parsePxValue(value) }
    }
    if (prop === 'min-width') return { name: 'minw', value: this.parsePxValue(value) }
    if (prop === 'max-width') return { name: 'maxw', value: this.parsePxValue(value) }
    if (prop === 'min-height') return { name: 'minh', value: this.parsePxValue(value) }
    if (prop === 'max-height') return { name: 'maxh', value: this.parsePxValue(value) }

    // Spacing
    if (prop === 'padding') return { name: 'pad', value: this.parsePxValue(value) }
    if (prop === 'margin') return { name: 'margin', value: this.parsePxValue(value) }

    // Colors
    if (prop === 'background' || prop === 'background-color') return { name: 'bg', value: value }
    if (prop === 'color') return { name: 'col', value: value }
    if (prop === 'border-color') return { name: 'boc', value: value }

    // Border
    if (prop === 'border') return { name: 'bor', value: value }
    if (prop === 'border-radius') return { name: 'rad', value: this.parsePxValue(value) }

    // Typography
    if (prop === 'font-size') return { name: 'font-size', value: this.parsePxValue(value) }
    if (prop === 'font-weight') {
      // Convert numeric weights back to keywords for readability
      const weightKeywords: Record<string, string> = {
        '100': 'thin', '300': 'light', '400': 'normal',
        '500': 'medium', '600': 'semibold', '700': 'bold', '900': 'black'
      }
      return { name: 'weight', value: weightKeywords[value] || value }
    }
    if (prop === 'line-height') return { name: 'line', value: value }
    if (prop === 'font-family') return { name: 'font', value: value }
    if (prop === 'text-align') return { name: 'text-align', value: value }
    if (prop === 'font-style' && value === 'italic') return { name: 'italic', value: true }
    if (prop === 'text-decoration' && value === 'underline') return { name: 'underline', value: true }
    if (prop === 'text-transform' && value === 'uppercase') return { name: 'uppercase', value: true }
    if (prop === 'text-transform' && value === 'lowercase') return { name: 'lowercase', value: true }

    // Visual
    if (prop === 'opacity') return { name: 'opacity', value: parseFloat(value) }
    if (prop === 'box-shadow') return { name: 'shadow', value: value }
    if (prop === 'cursor') return { name: 'cursor', value: value }
    if (prop === 'z-index') return { name: 'z', value: parseInt(value) }

    // Scroll
    if (prop === 'overflow-y' && value === 'auto') return { name: 'scroll', value: true }
    if (prop === 'overflow-x' && value === 'auto') return { name: 'scroll-hor', value: true }
    if (prop === 'overflow' && value === 'hidden') return { name: 'clip', value: true }

    // Display
    if (prop === 'display' && value === 'none') return { name: 'hidden', value: true }
    if (prop === 'display' && value === 'grid') return null // Handled separately

    // Grid
    if (prop === 'grid-template-columns') {
      // Parse repeat(N, 1fr) -> grid N
      const match = value.match(/repeat\((\d+), 1fr\)/)
      if (match) return { name: 'grid', value: parseInt(match[1]) }
      return { name: 'grid', value: value }
    }

    // Flex shorthand - handled in stylesToProps for w full / h full detection
    if (prop === 'flex') return null

    // Flex grow (often combined with width: 100%)
    if (prop === 'flex-grow') return null // Implicit with w full

    return null
  }

  /**
   * Convert IR events to Mirror props
   */
  private eventsToProps(events: IREvent[], props: Record<string, any>): void {
    for (const event of events) {
      const actions = event.actions.map(a => this.actionToString(a))
      const actionValue = actions.length === 1 ? actions[0] : actions

      if (event.key) {
        // Keyboard event: 'onkeydown escape': 'close'
        props[`onkeydown ${event.key}`] = actionValue
      } else {
        // Regular event: onclick: 'toggle'
        const eventName = `on${event.name}`
        props[eventName] = actionValue
      }
    }
  }

  /**
   * Convert IR action to action string
   */
  private actionToString(action: IRAction): string {
    if (action.target) {
      return `${action.type} ${action.target}`
    }
    return action.type
  }

  /**
   * Convert props object to string
   */
  private propsToString(props: Record<string, any>): string {
    const entries = Object.entries(props)
    if (entries.length === 0) return ''

    const parts: string[] = []

    for (const [key, value] of entries) {
      if (key === 'states') {
        // States need special formatting
        parts.push(`states: ${this.statesToString(value)}`)
      } else if (typeof value === 'string') {
        // Use single quotes for strings, but handle keys with special chars
        if (key.includes(' ') || key.includes('-')) {
          parts.push(`'${key}': '${value}'`)
        } else {
          parts.push(`${key}: '${value}'`)
        }
      } else if (typeof value === 'boolean') {
        parts.push(`${key}: ${value}`)
      } else if (typeof value === 'number') {
        parts.push(`${key}: ${value}`)
      } else if (Array.isArray(value)) {
        const arrayStr = value.map(v => typeof v === 'string' ? `'${v}'` : v).join(', ')
        parts.push(`${key}: [${arrayStr}]`)
      } else {
        parts.push(`${key}: ${JSON.stringify(value)}`)
      }
    }

    return `{ ${parts.join(', ')} }`
  }

  /**
   * Convert states object to string
   */
  private statesToString(states: Record<string, Record<string, any>>): string {
    const parts: string[] = []

    for (const [stateName, stateProps] of Object.entries(states)) {
      const propParts: string[] = []
      for (const [key, value] of Object.entries(stateProps)) {
        if (typeof value === 'string') {
          propParts.push(`${key}: '${value}'`)
        } else {
          propParts.push(`${key}: ${value}`)
        }
      }
      parts.push(`${stateName}: { ${propParts.join(', ')} }`)
    }

    return `{ ${parts.join(', ')} }`
  }

  /**
   * Parse px values to numbers
   */
  private parsePxValue(value: string): string | number {
    if (value.endsWith('px')) {
      const num = parseInt(value)
      if (!isNaN(num)) return num
    }
    return value
  }

  private escapeString(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  }

  private currentIndent(): string {
    return '  '.repeat(this.indent)
  }

  private indentLines(text: string): string {
    const indent = '  '.repeat(this.indent + 1)
    return text.split('\n').map(line => indent + line).join('\n')
  }
}
