/**
 * JSON AST → Mirror DSL Converter
 *
 * Converts JSON AST (as generated by LLMs) to Mirror DSL code.
 * This enables LLMs to generate UI by outputting structured JSON
 * which we then convert to our DSL.
 */

import type { ASTNode, EventHandler, ActionStatement, ConditionExpr } from '../parser/types'

const INDENT = '  '

/**
 * Convert a JSON AST to Mirror DSL code
 */
export function jsonToMirror(input: { nodes: ASTNode[] } | ASTNode[]): string {
  const nodes = Array.isArray(input) ? input : input.nodes
  return nodes.map(node => nodeToMirror(node, 0)).join('\n')
}

/**
 * Convert a single ASTNode to Mirror DSL
 */
function nodeToMirror(node: ASTNode, depth: number): string {
  const indent = INDENT.repeat(depth)
  const lines: string[] = []

  // Build the main line: Name instanceName: properties "content"
  let mainLine = indent

  // Component name
  mainLine += node.name

  // Instance name (Input Email:)
  if (node.instanceName) {
    mainLine += ` ${node.instanceName}:`
  }

  // Properties
  const propsStr = propertiesToMirror(node.properties as Record<string, string | number | boolean>)
  if (propsStr) {
    mainLine += ` ${propsStr}`
  }

  // Inline content (if no children)
  if (node.content && node.children.length === 0) {
    mainLine += ` "${escapeString(node.content)}"`
  }

  lines.push(mainLine)

  // Event handlers as child lines
  if (node.eventHandlers && node.eventHandlers.length > 0) {
    for (const handler of node.eventHandlers) {
      lines.push(eventHandlerToMirror(handler, depth + 1))
    }
  }

  // Content as child (if has other children)
  if (node.content && node.children.length > 0) {
    lines.push(`${INDENT.repeat(depth + 1)}"${escapeString(node.content)}"`)
  }

  // Children
  for (const child of node.children) {
    lines.push(nodeToMirror(child, depth + 1))
  }

  return lines.join('\n')
}

/**
 * Property name mapping from common/CSS names to Mirror DSL
 */
const PROP_ALIASES: Record<string, string> = {
  'color': 'col',
  'padding': 'pad',
  'margin': 'mar',
  'radius': 'rad',
  'background': 'col',
  'border-radius': 'rad',
  'font-size': 'size',
  'font-weight': 'weight',
  'border-color': 'boc',
  'border-width': 'bor',
}

/**
 * Properties that always need quoted string values
 * (because the parser expects them as string literals)
 */
const ALWAYS_QUOTE_PROPS = new Set(['icon', 'placeholder', 'type', 'src'])

/**
 * Special property conversions (e.g., pad-x → pad l-r)
 */
function convertSpecialProperty(key: string, value: string | number | boolean): [string, string | number | boolean] | null {
  if (key === 'pad-x' && typeof value === 'number') {
    return ['pad', `l-r ${value}`]
  }
  if (key === 'pad-y' && typeof value === 'number') {
    return ['pad', `u-d ${value}`]
  }
  if (key === 'mar-x' && typeof value === 'number') {
    return ['mar', `l-r ${value}`]
  }
  if (key === 'mar-y' && typeof value === 'number') {
    return ['mar', `u-d ${value}`]
  }
  return null
}

/**
 * Convert properties object to Mirror DSL string
 */
function propertiesToMirror(properties: Record<string, string | number | boolean>): string {
  const parts: string[] = []

  for (const [originalKey, value] of Object.entries(properties)) {
    // Map CSS/common names to Mirror names
    const key = PROP_ALIASES[originalKey] || originalKey

    // Handle special conversions
    const special = convertSpecialProperty(key, value)
    if (special) {
      parts.push(`${special[0]} ${special[1]}`)
      continue
    }

    if (value === true) {
      // Boolean true: just the key (e.g., "ver", "hidden")
      parts.push(key)
    } else if (value === false) {
      // Boolean false: skip (default)
      continue
    } else if (typeof value === 'string') {
      // String value - determine if quotes are needed
      const needsQuotes = ALWAYS_QUOTE_PROPS.has(key) ||
                          value.includes(' ') ||
                          value.includes('@') ||
                          value.includes('.') ||
                          value.includes('/') ||
                          value.includes(':') ||
                          value.includes('•') ||
                          /[^a-zA-Z0-9#$_-]/.test(value)

      if (value.startsWith('#') || value.startsWith('$')) {
        // Color or variable: no quotes
        parts.push(`${key} ${value}`)
      } else if (needsQuotes) {
        // Complex value: needs quotes
        parts.push(`${key} "${escapeString(value)}"`)
      } else {
        // Simple alphanumeric value: no quotes
        parts.push(`${key} ${value}`)
      }
    } else if (typeof value === 'number') {
      // Number value
      parts.push(`${key} ${value}`)
    }
  }

  return parts.join(' ')
}

/**
 * Convert event handler to Mirror DSL
 */
function eventHandlerToMirror(handler: EventHandler, depth: number): string {
  const indent = INDENT.repeat(depth)
  const actionsStr = handler.actions
    .map(action => actionToMirror(action))
    .join(' ')

  return `${indent}${handler.event} ${actionsStr}`
}

/**
 * Convert a condition expression to Mirror DSL string
 */
function conditionToMirror(cond: ConditionExpr): string {
  switch (cond.type) {
    case 'var':
      return `$${cond.name}`
    case 'not':
      return `not ${conditionToMirror(cond.operand!)}`
    case 'and':
      return `${conditionToMirror(cond.left!)} and ${conditionToMirror(cond.right!)}`
    case 'or':
      return `${conditionToMirror(cond.left!)} or ${conditionToMirror(cond.right!)}`
    case 'comparison':
      return `${conditionToMirror(cond.left!)} ${cond.operator} ${cond.value}`
    default:
      return ''
  }
}

/**
 * Convert action to Mirror DSL
 */
function actionToMirror(action: ActionStatement | { condition?: ConditionExpr; thenActions?: ActionStatement[]; elseActions?: ActionStatement[] }): string {
  // Handle conditionals
  if ('condition' in action && action.condition) {
    const condStr = conditionToMirror(action.condition)
    const thenStr = (action.thenActions || []).map(a => actionToMirror(a)).filter(Boolean).join(', ')
    const elseStr = (action.elseActions || []).map(a => actionToMirror(a)).filter(Boolean).join(', ')

    if (elseStr) {
      return `if ${condStr} then ${thenStr} else ${elseStr}`
    }
    return `if ${condStr} then ${thenStr}`
  }

  const stmt = action as ActionStatement
  const parts: string[] = [stmt.type]

  if (stmt.target) {
    parts.push(stmt.target)
  }

  if (stmt.toState) {
    parts.push('to', stmt.toState)
  }

  if (stmt.position) {
    parts.push(stmt.position)
  }

  if (stmt.animation) {
    parts.push(stmt.animation)
  }

  if (stmt.duration) {
    parts.push(String(stmt.duration))
  }

  if (stmt.property && stmt.value !== undefined) {
    parts.push(`${stmt.property} ${stmt.value}`)
  }

  return parts.join(' ')
}

/**
 * Escape special characters in strings
 */
function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/**
 * Simplified JSON schema for LLM prompts
 * Uses Mirror DSL property names directly
 */
export const LLM_SCHEMA = `
// WICHTIG: Verwende immer $token-namen statt hardcoded Werte!
// Beispiel: "$color-primary" statt "#3B82F6", "$space-md" statt "12"

interface ASTNode {
  type: "component"
  name: string                    // Box, Text, Button, Card, Input, Image, etc.
  instanceName?: string           // Named instance: Input Email: → instanceName: "Email"
  properties: {
    // Layout
    ver?: boolean                 // Vertical layout (column)
    hor?: boolean                 // Horizontal layout (row) - default
    gap?: string | number         // "$space-md" oder Zahl
    pad?: string | number         // "$space-lg" oder Zahl
    "pad-x"?: string | number
    "pad-y"?: string | number

    // Size
    w?: number | "full"
    h?: number | "full"

    // Styling - IMMER TOKENS VERWENDEN!
    bg?: string                   // "$color-surface", "$color-primary"
    col?: string                  // "$color-text", "$color-text-muted"
    rad?: string | number         // "$radius-md", "$radius-lg"
    bor?: number                  // Border width (1, 2)
    boc?: string                  // "$color-border"
    shadow?: string               // "$shadow-md", "$shadow-lg"

    // Typography - TOKENS!
    size?: string | number        // "$size-base", "$size-lg", "$size-xl"
    weight?: string | number      // "$weight-medium", "$weight-bold"

    // Alignment
    "hor-l"?: boolean
    "hor-cen"?: boolean
    "hor-r"?: boolean
    "ver-t"?: boolean
    "ver-cen"?: boolean
    "ver-b"?: boolean

    // Input
    placeholder?: string
    type?: string                 // "password", "email"

    // Image
    src?: string

    // Icon
    icon?: string                 // Lucide: "plus", "search", "user", "mail"

    hidden?: boolean
  }
  content?: string
  children?: ASTNode[]
  eventHandlers?: {
    event: string                 // "onclick"
    actions: {
      type: string                // "page", "open", "close", "toggle"
      target?: string
    }[]
  }[]
}
`

export default jsonToMirror
