/**
 * LLM → JavaScript → Mirror Generator
 *
 * This module provides a new generation pathway:
 * 1. LLM generates JavaScript using our Builder API
 * 2. We evaluate the JS to get a JsNode tree
 * 3. We transform the tree to Mirror DSL
 *
 * Benefits:
 * - LLM already knows JavaScript perfectly
 * - No syntax errors (JS parser validates)
 * - Deterministic transformation (no AI involved)
 * - Easy to debug and test
 */

import { jsToMirror } from './js-to-mirror'
import { JS_BUILDER_PROMPT } from './llm-js-prompt'
import type { JsNode, JsDefinition, JsToken } from './js-builder'

// Import all builder functions for evaluation context
import * as JsBuilder from './js-builder'

// =============================================================================
// TYPES
// =============================================================================

export interface GenerationResult {
  success: boolean
  mirror?: string
  jsCode?: string
  error?: string
  parseError?: string
}

// =============================================================================
// MAIN GENERATOR
// =============================================================================

/**
 * Generate Mirror DSL from LLM JavaScript output
 *
 * @param jsCode - JavaScript code generated by the LLM
 * @returns Mirror DSL code or error
 */
export function generateFromJs(jsCode: string): GenerationResult {
  try {
    // Clean up the JS code
    const cleanedJs = cleanJsCode(jsCode)

    // Evaluate the JS to get the node tree
    const result = evaluateJsBuilder(cleanedJs)

    if (!result.success) {
      return {
        success: false,
        jsCode: cleanedJs,
        parseError: result.error
      }
    }

    // Transform to Mirror DSL
    const mirror = jsToMirror(result.nodes!)

    return {
      success: true,
      mirror,
      jsCode: cleanedJs
    }
  } catch (error) {
    return {
      success: false,
      jsCode,
      error: error instanceof Error ? error.message : String(error)
    }
  }
}

// =============================================================================
// JS CODE CLEANING
// =============================================================================

/**
 * Clean up LLM-generated JavaScript code
 */
function cleanJsCode(code: string): string {
  let cleaned = code.trim()

  // Extract code from markdown fence (ignore everything after closing fence)
  const fenceMatch = cleaned.match(/```(?:javascript|js)?\s*([\s\S]*?)```/)
  if (fenceMatch) {
    cleaned = fenceMatch[1]
  } else {
    // No fence found - try to extract just the code part
    // Stop at lines that look like explanations (start with letter, no code syntax)
    const lines = cleaned.split('\n')
    const codeLines: string[] = []
    let inCode = false

    for (const line of lines) {
      const trimmed = line.trim()

      // Skip empty lines at start
      if (!inCode && !trimmed) continue

      // Code indicators
      const isCodeLine = (
        trimmed.startsWith('//') ||
        trimmed.match(/^[A-Z][a-zA-Z]*\s*\(/) ||  // Component call
        trimmed.match(/^[a-z]+\s*\(/) ||           // Helper call (row, col)
        trimmed.match(/^[\[\{\}\]\),]/) ||         // Brackets
        trimmed.match(/^\s/) ||                     // Indented
        trimmed === ''
      )

      if (isCodeLine || inCode) {
        inCode = true
        // Stop if we hit an explanation line (not indented = not code continuation)
        const notIndented = !line.startsWith(' ') && !line.startsWith('\t')
        if (trimmed && notIndented) {
          // Pattern 1: Numbered list (1. something, 2. something)
          if (trimmed.match(/^\d+\.\s/)) {
            break
          }
          // Pattern 2: Starts with "This", "Here", "Das", "Hier", etc. (common explanation starters)
          // Also matches "Note:" with colon
          if (trimmed.match(/^(This|Here|That|Note|Das|Hier|Dies)[\s:]/i)) {
            break
          }
          // Pattern 3: Capital letter + lowercase + space, NOT a component call
          if (trimmed.match(/^[A-Z][a-z]+\s/) &&
              !trimmed.match(/^[A-Z][a-zA-Z]*\s*\(/)) {
            break
          }
        }
        codeLines.push(line)
      }
    }
    cleaned = codeLines.join('\n')
  }

  // Remove any "export" statements
  cleaned = cleaned.replace(/^export\s+/gm, '')

  // Remove any comments at the start
  cleaned = cleaned.replace(/^\/\/.*\n/gm, '')

  return cleaned.trim()
}

// =============================================================================
// JS EVALUATION
// =============================================================================

interface EvalResult {
  success: boolean
  nodes?: (JsNode | JsDefinition | JsToken)[]
  error?: string
}

/**
 * Safely evaluate JS Builder code
 */
function evaluateJsBuilder(code: string): EvalResult {
  try {
    // Create evaluation context with all builder functions
    const context = {
      // Components
      Box: JsBuilder.Box,
      Row: JsBuilder.Row,
      Column: JsBuilder.Column,
      Stack: JsBuilder.Stack,
      Grid: JsBuilder.Grid,
      Text: JsBuilder.Text,
      Title: JsBuilder.Title,
      Label: JsBuilder.Label,
      Paragraph: JsBuilder.Paragraph,
      Button: JsBuilder.Button,
      Link: JsBuilder.Link,
      Input: JsBuilder.Input,
      Textarea: JsBuilder.Textarea,
      Checkbox: JsBuilder.Checkbox,
      Select: JsBuilder.Select,
      Dropdown: JsBuilder.Dropdown,
      Image: JsBuilder.Image,
      Icon: JsBuilder.Icon,
      Avatar: JsBuilder.Avatar,
      Card: JsBuilder.Card,
      Panel: JsBuilder.Panel,
      Section: JsBuilder.Section,
      Header: JsBuilder.Header,
      Footer: JsBuilder.Footer,
      Sidebar: JsBuilder.Sidebar,
      Nav: JsBuilder.Nav,
      Menu: JsBuilder.Menu,
      Dialog: JsBuilder.Dialog,
      Modal: JsBuilder.Modal,
      Tooltip: JsBuilder.Tooltip,
      Popup: JsBuilder.Popup,
      Alert: JsBuilder.Alert,
      Badge: JsBuilder.Badge,
      Tag: JsBuilder.Tag,
      Toast: JsBuilder.Toast,
      List: JsBuilder.List,
      Item: JsBuilder.Item,
      Table: JsBuilder.Table,

      // Additional components (common LLM outputs)
      Logo: JsBuilder.Logo,
      Accordion: JsBuilder.Accordion,
      Layout: JsBuilder.Layout,
      Form: JsBuilder.Form,
      Container: JsBuilder.Container,
      Divider: JsBuilder.Divider,
      Spacer: JsBuilder.Spacer,
      Progress: JsBuilder.Progress,
      Slider: JsBuilder.Slider,
      Switch: JsBuilder.Switch,
      Radio: JsBuilder.Radio,
      Tabs: JsBuilder.Tabs,
      Tab: JsBuilder.Tab,
      TabPanel: JsBuilder.TabPanel,
      Breadcrumb: JsBuilder.Breadcrumb,
      Pagination: JsBuilder.Pagination,
      Spinner: JsBuilder.Spinner,
      Skeleton: JsBuilder.Skeleton,

      // Actions
      show: JsBuilder.show,
      hide: JsBuilder.hide,
      toggle: JsBuilder.toggle,
      open: JsBuilder.open,
      close: JsBuilder.close,
      page: JsBuilder.page,
      assign: JsBuilder.assign,
      change: JsBuilder.change,
      highlight: JsBuilder.highlight,
      select: JsBuilder.select,
      validate: JsBuilder.validate,
      action: JsBuilder.action,

      // Helpers
      state: JsBuilder.state,
      define: JsBuilder.define,
      token: JsBuilder.token,
      slot: JsBuilder.slot,
      component: JsBuilder.component,
      row: JsBuilder.row,
      col: JsBuilder.col,
      center: JsBuilder.center,
      item: JsBuilder.item,
      when: JsBuilder.when,
      each: JsBuilder.each,
    }

    // Build the function body
    // Wrap in array if it's a single expression
    const wrappedCode = code.includes('\n') && !code.trim().startsWith('[')
      ? `return [${code}]`
      : `return ${code}`

    // Create a function with the context variables
    const contextKeys = Object.keys(context)
    const contextValues = Object.values(context)

    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const fn = new Function(...contextKeys, wrappedCode)
    const result = fn(...contextValues)

    // Normalize to array
    const nodes = Array.isArray(result) ? result : [result]

    return { success: true, nodes }
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    }
  }
}

// =============================================================================
// LLM INTEGRATION (placeholder for actual API call)
// =============================================================================

/**
 * Call LLM with JS Builder prompt
 *
 * This is a placeholder - integrate with your actual LLM API
 */
export async function generateWithJsBuilder(
  userPrompt: string,
  _callLLM: (systemPrompt: string, userPrompt: string) => Promise<string>
): Promise<GenerationResult> {
  try {
    // Call LLM with JS Builder system prompt
    const jsCode = await _callLLM(JS_BUILDER_PROMPT, userPrompt)

    // Transform JS to Mirror
    return generateFromJs(jsCode)
  } catch (error) {
    return {
      success: false,
      error: error instanceof Error ? error.message : String(error)
    }
  }
}

// =============================================================================
// EXPORTS
// =============================================================================

export { JS_BUILDER_PROMPT }
