/**
 * Generate reference.html from structured JSON
 * Run with: npx tsx scripts/generate-reference.ts
 *
 * Reads docs/reference.json (generated by extract-parser-docs.ts)
 * and produces a styled HTML reference page.
 */

import { readFileSync, writeFileSync } from 'fs'

// ============================================================================
// TYPES (matching extract-parser-docs.ts output)
// ============================================================================

interface DocItem {
  name: string
  description: string
  syntax?: string
  example?: string
}

interface Subsection {
  id: string
  title: string
  description?: string
  items?: DocItem[]
  syntax?: string[]
  examples?: string[]
}

interface Section {
  id: string
  title: string
  description?: string
  items?: DocItem[]
  subsections?: Subsection[]
}

interface Reference {
  version: string
  generatedAt: string
  generatedFrom: string[]
  sections: Section[]
}

// ============================================================================
// HTML GENERATION
// ============================================================================

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

function highlightSyntax(code: string): string {
  return escapeHtml(code)
    // Comments
    .replace(/(\/\/.*)/g, '<span class="comment">$1</span>')
    // Strings
    .replace(/(".*?")/g, '<span class="string">$1</span>')
    // Tokens ($name)
    .replace(/(\$[\w.-]+)/g, '<span class="token">$1</span>')
    // Colors (#hex)
    .replace(/(#[A-Fa-f0-9]{3,8})/g, '<span class="value">$1</span>')
    // Numbers (standalone)
    .replace(/\b(\d+(?:\.\d+)?(?:px|%|ms|s)?)\b/g, '<span class="value">$1</span>')
    // Keywords
    .replace(/\b(if|else|then|each|in|where|and|or|not|state|hover|focus|active|disabled|onclick|onhover|onchange|oninput|onkeydown|onkeyup|show|hide|open|close|toggle|page|assign|to|data|events|animate)\b/g, '<span class="keyword">$1</span>')
    // Components (PascalCase at start or after whitespace/newline)
    .replace(/(^|[\s{(])([A-Z][A-Za-z0-9]*)/gm, '$1<span class="component">$2</span>')
    // Properties before colon
    .replace(/([a-z][\w-]*)\s*:/g, '<span class="property">$1</span>:')
}

function generateItems(items: DocItem[]): string {
  if (!items || items.length === 0) return ''

  const rows = items.map(item => {
    const name = escapeHtml(item.name)
    const desc = escapeHtml(item.description)
    return `          <tr>
            <td><code>${name}</code></td>
            <td>${desc}</td>
          </tr>`
  }).join('\n')

  return `        <table>
          <tr><th>Name</th><th>Beschreibung</th></tr>
${rows}
        </table>`
}

function generateSyntax(syntax: string[]): string {
  if (!syntax || syntax.length === 0) return ''

  const code = syntax.map(s => highlightSyntax(s)).join('\n')
  return `        <pre>${code}</pre>`
}

function generateExamples(examples: Array<string | { code: string }>): string {
  if (!examples || examples.length === 0) return ''

  const code = examples.map(e => {
    const codeStr = typeof e === 'string' ? e : e.code
    return highlightSyntax(codeStr)
  }).join('\n\n')
  return `        <div class="example-label">Beispiel:</div>
        <pre>${code}</pre>`
}

function generateSubsection(sub: Subsection): string {
  const parts: string[] = []

  parts.push(`      <h4 id="${sub.id}">${escapeHtml(sub.title)}</h4>`)

  if (sub.description) {
    parts.push(`      <p>${escapeHtml(sub.description)}</p>`)
  }

  if (sub.syntax && sub.syntax.length > 0) {
    parts.push(generateSyntax(sub.syntax))
  }

  if (sub.items && sub.items.length > 0) {
    parts.push(generateItems(sub.items))
  }

  if (sub.examples && sub.examples.length > 0) {
    parts.push(generateExamples(sub.examples))
  }

  return parts.join('\n')
}

function generateSection(section: Section, index: number): string {
  const parts: string[] = []

  parts.push(`    <section class="section" id="${section.id}">`)
  parts.push(`      <h2><span class="section-number">${index + 1}.</span> ${escapeHtml(section.title)}</h2>`)

  if (section.description) {
    parts.push(`      <p class="section-desc">${escapeHtml(section.description)}</p>`)
  }

  if (section.subsections) {
    for (const sub of section.subsections) {
      parts.push(generateSubsection(sub))
    }
  }

  parts.push(`    </section>`)
  parts.push(`    <div class="divider"></div>`)

  return parts.join('\n')
}

function generateNav(sections: Section[]): string {
  const items = sections.map((s, i) => {
    const subsLinks = s.subsections?.map(sub =>
      `        <a href="#${sub.id}">${escapeHtml(sub.title)}</a>`
    ).join('\n') || ''

    return `      <div class="nav-section">
        <a href="#${s.id}" class="nav-title">${i + 1}. ${escapeHtml(s.title)}</a>
${subsLinks}
      </div>`
  }).join('\n')

  return `    <nav class="sidebar">
${items}
    </nav>`
}

// ============================================================================
// CSS STYLES
// ============================================================================

const CSS_STYLES = `
    :root {
      --color-bg: #111;
      --color-bg-darker: #0a0a0a;
      --color-surface: #1a1a1a;
      --color-border: #222;
      --color-text: #999;
      --color-text-muted: #555;
      --color-text-light: #666;
      --color-text-bright: #bbb;
      --color-text-heading: #ddd;
      --color-accent: #3B82F6;

      --syntax-comment: #555;
      --syntax-component: #7a7;
      --syntax-property: #888;
      --syntax-value: #b96;
      --syntax-string: #a88;
      --syntax-keyword: #88a;
      --syntax-token: #8aa;

      --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      --font-mono: 'SF Mono', 'Consolas', 'Monaco', monospace;

      --content-width: 800px;
      --sidebar-width: 220px;
    }

    * { margin: 0; padding: 0; box-sizing: border-box; }

    body {
      font-family: var(--font-sans);
      background: var(--color-bg);
      color: var(--color-text);
      line-height: 1.7;
      font-size: 14px;
    }

    .layout {
      display: flex;
      max-width: calc(var(--content-width) + var(--sidebar-width) + 48px);
      margin: 0 auto;
      padding: 48px 24px;
      gap: 48px;
    }

    .sidebar {
      position: sticky;
      top: 48px;
      width: var(--sidebar-width);
      height: fit-content;
      flex-shrink: 0;
    }

    .sidebar a {
      display: block;
      color: var(--color-text-muted);
      text-decoration: none;
      padding: 4px 0;
      font-size: 12px;
      transition: color 0.15s;
    }

    .sidebar a:hover { color: var(--color-text-bright); }
    .sidebar a.nav-title {
      color: var(--color-text-light);
      font-weight: 500;
      margin-top: 16px;
      font-size: 13px;
    }
    .sidebar a.nav-title:first-child { margin-top: 0; }

    .content {
      flex: 1;
      max-width: var(--content-width);
      min-width: 0;
    }

    h1 {
      font-size: 42px;
      font-weight: 400;
      color: #eee;
      margin-bottom: 8px;
      letter-spacing: -1px;
    }

    .subtitle {
      color: var(--color-text-light);
      margin-bottom: 32px;
    }

    .meta {
      font-size: 11px;
      color: var(--color-text-muted);
      margin-bottom: 48px;
      padding-bottom: 24px;
      border-bottom: 1px solid var(--color-border);
    }

    h2 {
      font-size: 20px;
      font-weight: 500;
      color: var(--color-text-heading);
      margin: 48px 0 16px;
    }

    h2:first-of-type { margin-top: 0; }

    .section-number {
      color: var(--color-text-muted);
      margin-right: 8px;
    }

    .section-desc {
      color: var(--color-text-light);
      margin-bottom: 16px;
    }

    h4 {
      font-size: 14px;
      font-weight: 500;
      color: var(--color-text-bright);
      margin: 32px 0 12px;
    }

    p { margin-bottom: 12px; }

    pre, code {
      font-family: var(--font-mono);
      font-size: 12px;
    }

    pre {
      background: var(--color-bg-darker);
      border: 1px solid var(--color-border);
      padding: 16px;
      overflow-x: auto;
      margin: 12px 0;
      line-height: 1.6;
      border-radius: 4px;
    }

    code {
      background: var(--color-surface);
      padding: 2px 6px;
      border-radius: 3px;
    }

    pre code {
      background: none;
      padding: 0;
    }

    .comment { color: var(--syntax-comment); }
    .component { color: var(--syntax-component); }
    .property { color: var(--syntax-property); }
    .value { color: var(--syntax-value); }
    .string { color: var(--syntax-string); }
    .keyword { color: var(--syntax-keyword); }
    .token { color: var(--syntax-token); }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 12px 0;
    }

    th, td {
      padding: 8px 12px;
      text-align: left;
      border-bottom: 1px solid var(--color-border);
    }

    th {
      font-weight: 500;
      color: var(--color-text-light);
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    td:first-child { white-space: nowrap; }
    td code { font-size: 11px; }
    tr:last-child td { border-bottom: none; }

    .example-label {
      font-size: 11px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
      color: var(--color-text-muted);
      margin: 16px 0 8px;
    }

    .divider {
      height: 1px;
      background: var(--color-border);
      margin: 48px 0;
    }

    .footer {
      margin-top: 48px;
      padding-top: 24px;
      border-top: 1px solid var(--color-border);
      font-size: 12px;
      color: var(--color-text-muted);
    }

    @media (max-width: 900px) {
      .layout { flex-direction: column; gap: 24px; }
      .sidebar {
        position: static;
        width: 100%;
        display: flex;
        flex-wrap: wrap;
        gap: 8px 16px;
      }
      .nav-section { display: flex; gap: 8px; align-items: baseline; }
      .sidebar a { padding: 2px 0; }
      .sidebar a.nav-title { margin-top: 0; }
    }
`

// ============================================================================
// MAIN
// ============================================================================

function generateHTML(reference: Reference): string {
  const sections = reference.sections.map((s, i) => generateSection(s, i)).join('\n\n')
  const nav = generateNav(reference.sections)

  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mirror v${reference.version} – Referenz</title>
  <style>${CSS_STYLES}</style>
</head>
<body>
  <div class="layout">
${nav}

    <main class="content">
      <h1>Mirror Referenz</h1>
      <p class="subtitle">UI-Beschreibungssprache für Prototyping</p>
      <p class="meta">Version ${reference.version} · Generiert: ${reference.generatedAt.split('T')[0]}</p>

${sections}

      <footer class="footer">
        <p>Mirror Referenz v${reference.version}</p>
        <p>Generiert aus: ${reference.generatedFrom.length} Parser-Dateien</p>
      </footer>
    </main>
  </div>
</body>
</html>
`
}

// Main
const jsonPath = './docs/reference.json'
const htmlPath = './docs/reference.html'

const json = readFileSync(jsonPath, 'utf-8')
const reference: Reference = JSON.parse(json)

const html = generateHTML(reference)
writeFileSync(htmlPath, html)

console.log(`Generated ${htmlPath}`)
console.log(`  ${reference.sections.length} sections`)
console.log(`  ${reference.sections.reduce((sum, s) => sum + (s.subsections?.length || 0), 0)} subsections`)
