/**
 * Mirror Framework Backend
 *
 * Generates M() function calls that use the Mirror Runtime.
 * Output is idiomatic JavaScript that mirrors Mirror DSL 1:1.
 *
 * This backend enables:
 * 1. LLM-generated code that's identical to compiler output
 * 2. Deterministic reverse translation via M.toMirror()
 * 3. Smaller bundle size (runtime is separate)
 */

import type { AST } from '../parser/ast'
import { toIR } from '../ir'
import { isLayoutPrimitive } from '../schema/dsl'
import { flexToNineZone, flexToSingleAxisCenter } from '../schema/layout-defaults'
import type { IR, IRNode, IRStyle, IREvent, IRAction, IREach, IRConditional } from '../ir/types'
import { ANIMATION_SHORTHAND } from './animations'

/**
 * Reverse `mirror-X 0.3s ease forwards` strings back to the `anim X`
 * keyword. Pre-built from the shared shorthand map so any future
 * keyword stays in sync automatically.
 */
const ANIMATION_REVERSE: Record<string, string> = Object.fromEntries(
  Object.entries(ANIMATION_SHORTHAND).map(([keyword, css]) => [css, keyword])
)

const TAG_TO_TYPE: Record<string, string> = {
  div: 'Box',
  span: 'Text',
  button: 'Button',
  input: 'Input',
  textarea: 'Textarea',
  img: 'Image',
  a: 'Link',
}

/**
 * Generate M() framework calls from Mirror AST
 *
 * @example Output:
 * ```javascript
 * import { M } from 'mirror-runtime'
 *
 * export const ui = M('Box', { bg: '#1a1a23', pad: 16 }, [
 *   M('Text', 'Hello', { weight: 'bold' })
 * ])
 *
 * export function mount(container) {
 *   return M.render(ui, container)
 * }
 * ```
 */
export function generateFramework(ast: AST): string {
  const ir = toIR(ast)
  const generator = new FrameworkGenerator(ir)
  return generator.generate()
}

/**
 * Convert an IR data-value (nested object, list, or scalar) to a JS literal
 * the M(...) runtime can iterate at render time. Mirrors the React backend's
 * `dataAttributesToJSObject` semantics — nested objects round-trip as object
 * literals, bare-list forms as arrays, scalars as quoted/raw values.
 */
function dataValueToJS(value: unknown): string {
  if (value === null) return 'null'
  if (Array.isArray(value)) {
    return '[' + value.map(v => dataValueToJS(v)).join(', ') + ']'
  }
  if (typeof value === 'object' && value !== null) {
    // Skip data-references (`__ref: true` markers) — their resolution
    // happens at runtime; emit as a plain placeholder string for now.
    if ('__ref' in value && (value as { __ref: boolean }).__ref) {
      const ref = value as unknown as { collection: string; entry: string }
      return JSON.stringify(`$${ref.collection}.${ref.entry}`)
    }
    const entries = Object.entries(value as Record<string, unknown>).map(
      ([k, v]) => `${JSON.stringify(k)}: ${dataValueToJS(v)}`
    )
    return '{ ' + entries.join(', ') + ' }'
  }
  return JSON.stringify(value)
}

class FrameworkGenerator {
  private ir: IR
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR) {
    this.ir = ir
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitCustomIcons()
    this.emitComponents()
    this.emitUI()
    this.emitMount()

    return this.lines.join('\n')
  }

  /**
   * Slice 51 V-2: emit `M.registerIcon(...)` calls for `$icons:` entries.
   * Pre-Slice-51 the Framework backend silently dropped Custom-Icons —
   * `Icon "myicon"` would compile to `M('Icon', 'myicon', { is: '24' })`
   * which the runtime tried to fetch from Lucide-CDN (404). The mirror-
   * runtime package exposes `M.registerIcon` (re-exported from
   * `compiler/runtime/icons.ts`), so emitting registration calls here
   * gives Framework targets the same custom-icon pipeline as DOM.
   */
  private emitCustomIcons(): void {
    if (!this.ir.icons || this.ir.icons.length === 0) return
    this.emit('// Custom Icons')
    for (const icon of this.ir.icons) {
      const viewBox = icon.viewBox || '0 0 24 24'
      const escapedPath = icon.path.replace(/"/g, '\\"')
      this.emit(`M.registerIcon('${icon.name}', "${escapedPath}", '${viewBox}')`)
    }
    this.emit('')
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (Framework Backend)')
    this.emit('// This code uses the Mirror Runtime for rendering')
    this.emit('')
    this.emit("import { M } from 'mirror-runtime'")
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    // Drop property-sets (no `value`, no `data`) — they're expanded inline
    // at the IR layer, so emitting `'cardstyle': undefined` is just noise.
    const valueTokens = this.ir.tokens.filter(t => t.value !== undefined || t.data !== undefined)
    if (valueTokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('export const tokens = {')
    this.indent++
    for (const token of valueTokens) {
      // Nested data objects (`tasks: { t1: {...}, t2: {...} }`) and bare-list
      // forms (`colors: [red, blue]`) need a real JS literal — without it the
      // runtime can't iterate them via `each task in $tasks` / `$colors.count`.
      if (token.data !== undefined) {
        this.emit(`'${token.name}': ${dataValueToJS(token.data)},`)
        continue
      }
      const value = typeof token.value === 'string' ? `'${token.value}'` : token.value
      this.emit(`'${token.name}': ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitComponents(): void {
    // Component definitions would be extracted from AST
    // For now, we skip this as components are resolved during IR transformation
  }

  private emitUI(): void {
    this.emit('// UI Tree')

    if (this.ir.nodes.length === 1) {
      // Single root node
      this.emit('export const ui = ' + this.nodeToM(this.ir.nodes[0]))
    } else if (this.ir.nodes.length > 1) {
      // Multiple root nodes - wrap in Box
      this.emit("export const ui = M('Box', [")
      this.indent++
      for (let i = 0; i < this.ir.nodes.length; i++) {
        const comma = i < this.ir.nodes.length - 1 ? ',' : ''
        this.emit(this.nodeToM(this.ir.nodes[i]) + comma)
      }
      this.indent--
      this.emit('])')
    } else {
      this.emit("export const ui = M('Box')")
    }

    this.emit('')
  }

  private emitMount(): void {
    this.emit('/**')
    this.emit(' * Mount UI to a container element')
    this.emit(' * @param {HTMLElement} container - The container to mount to')
    this.emit(' * @returns {MirrorUI} - UI controller with get() method')
    this.emit(' */')
    this.emit('export function mount(container) {')
    this.indent++
    this.emit('return M.render(ui, container)')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// For reverse translation to Mirror DSL:')
    this.emit('// console.log(M.toMirror(ui))')
  }

  /**
   * Convert IR node to M() call string
   */
  private nodeToM(node: IRNode): string {
    // Handle each loop
    if (node.each) {
      return this.eachToM(node.each)
    }

    // Handle conditional
    if (node.conditional) {
      return this.conditionalToM(node.conditional)
    }

    const parts: string[] = []

    // Type
    const type = this.getNodeType(node)
    parts.push(`'${type}'`)

    // Content (for Text, Icon, Button, Link)
    const content = this.getContent(node)

    // Props
    const props = this.nodeToProps(node)
    const propsStr = this.propsToString(props)

    // Children
    const children = node.children.map(c => this.nodeToM(c))
    const hasChildren = children.length > 0

    // Build M() call
    if (content && propsStr && hasChildren) {
      // M('Text', 'content', { props }, [children])
      return `M(${parts[0]}, '${this.escapeString(content)}', ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content && propsStr) {
      // M('Text', 'content', { props })
      return `M(${parts[0]}, '${this.escapeString(content)}', ${propsStr})`
    } else if (content && hasChildren) {
      // M('Text', 'content', [children])
      return `M(${parts[0]}, '${this.escapeString(content)}', [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content) {
      // M('Text', 'content')
      return `M(${parts[0]}, '${this.escapeString(content)}')`
    } else if (propsStr && hasChildren) {
      // M('Box', { props }, [children])
      return `M(${parts[0]}, ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (propsStr) {
      // M('Box', { props })
      return `M(${parts[0]}, ${propsStr})`
    } else if (hasChildren) {
      // M('Box', [children])
      return `M(${parts[0]}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else {
      // M('Box')
      return `M(${parts[0]})`
    }
  }

  private eachToM(each: IREach): string {
    const template = each.template.map(n => this.nodeToM(n))
    const templateStr = `[\n${this.indentLines(template.join(',\n'))}\n${this.currentIndent()}]`

    if (each.filter) {
      return `M.each('${each.itemVar}', '${each.collection}', ${templateStr}, '${each.filter}')`
    }
    return `M.each('${each.itemVar}', '${each.collection}', ${templateStr})`
  }

  private conditionalToM(cond: IRConditional): string {
    const thenBranch = cond.then.map(n => this.nodeToM(n))
    const thenStr = `[\n${this.indentLines(thenBranch.join(',\n'))}\n${this.currentIndent()}]`

    if (cond.else && cond.else.length > 0) {
      const elseBranch = cond.else.map(n => this.nodeToM(n))
      const elseStr = `[\n${this.indentLines(elseBranch.join(',\n'))}\n${this.currentIndent()}]`
      return `M.if('${cond.condition}', ${thenStr}, ${elseStr})`
    }

    return `M.if('${cond.condition}', ${thenStr})`
  }

  private getNodeType(node: IRNode): string {
    if (node.name && node.name !== node.tag) return node.name
    if (node.primitive === 'icon') return 'Icon'
    return TAG_TO_TYPE[node.tag] || node.name || 'Box'
  }

  /**
   * Extract content from node (for Text, Icon, Button, Link).
   *
   * Layout primitives (Frame/Box, Spacer/Divider, Table family) don't
   * carry positional text content — Slice 1 W112. Skip the content here
   * so the framework backend doesn't emit `M('Frame', 'hello')` while
   * DOM and React both refuse to render the literal.
   */
  private getContent(node: IRNode): string | null {
    if (node.name && isLayoutPrimitive(node.name)) return null
    const textContent = node.properties.find(p => p.name === 'textContent')
    if (textContent && typeof textContent.value === 'string') {
      return textContent.value
    }
    return null
  }

  /**
   * Convert node styles, events, and properties to props object
   */
  private nodeToProps(node: IRNode): Record<string, any> {
    const props: Record<string, any> = {}

    // Instance name
    if (node.instanceName) {
      props.named = node.instanceName
    }

    // Initial state
    if (node.initialState) {
      props.state = node.initialState
    }

    // Visible when
    if (node.visibleWhen) {
      props['visible-when'] = node.visibleWhen
    }

    // Route
    if (node.route) {
      props.route = node.route
    }

    // Selection
    if (node.selection) {
      props.selection = node.selection
    }

    // Convert IR styles to props
    this.stylesToProps(node.styles, props)

    // Convert IR events to props
    this.eventsToProps(node.events, props)

    // Add HTML properties (except textContent which is handled as content)
    for (const prop of node.properties) {
      if (prop.name !== 'textContent') {
        if (
          prop.name === 'placeholder' ||
          prop.name === 'href' ||
          prop.name === 'src' ||
          prop.name === 'type'
        ) {
          props[prop.name] = prop.value
        } else if (prop.name === 'hidden' || prop.name === 'disabled') {
          props[prop.name] = true
        } else if (prop.name.startsWith('data-icon-')) {
          // Convert data-icon-* to icon properties
          const iconProp = prop.name.replace('data-icon-', '')
          if (iconProp === 'size') props.is = prop.value
          else if (iconProp === 'color') props.ic = prop.value
          else if (iconProp === 'weight') props.iw = prop.value
          else if (iconProp === 'fill') props.fill = prop.value === 'true' || prop.value === true
        } else if (
          // Chart-specific properties carry the data binding + render
          // hints (`chartType`, `data`, `fill`, `tension`, `title`,
          // `xLabel`, `yLabel`, `min`/`max`, `step`, `colors`). The
          // Mirror runtime needs them on the M-prop bag to wire up
          // Chart.js. Pre-fix every chart compiled to
          // `M('Line', { w: 350, h: 180 })` with no data — the runtime
          // had nothing to bind.
          node.primitive === 'chart' &&
          (prop.name === 'chartType' ||
            prop.name === 'data' ||
            prop.name === 'fill' ||
            prop.name === 'tension' ||
            prop.name === 'title' ||
            prop.name === 'xLabel' ||
            prop.name === 'yLabel' ||
            prop.name === 'min' ||
            prop.name === 'max' ||
            prop.name === 'step' ||
            prop.name === 'colors')
        ) {
          props[prop.name] = prop.value
        }
      }
    }

    // Slice 50 V-3: Icon-Reverse-Map Suppression. Wenn Icon UND data-icon-*
    // Attribute vorhanden sind, sind die korrespondierenden CSS-Reverses
    // (`width→w`, `height→h`, `color→col`) Doubletten — der User hat
    // ursprünglich `is`/`ic`/`iw`/`fill` geschrieben, nicht beide Wege.
    // Pre-fix emittierte Framework `{ w: 24, h: 24, col: '#f00', is: '24',
    // ic: '#f00' }` — round-trip-lossy weil Re-Compile beide Wege liest.
    if (node.primitive === 'icon') {
      if (props.is !== undefined) {
        delete props.w
        delete props.h
      }
      if (props.ic !== undefined) {
        delete props.col
      }
      if (props.iw !== undefined) {
        // V-4 hat font-weight CSS-Emit unterdrückt — diese Suppression ist
        // defensiv für Pfade die das doch noch durchlassen würden.
        delete props.weight
      }
    }

    // Token-leak guard. Some IR-paths (icon-color `ic $accent`, state-
    // block `selected: { boc: $accent }`, `col $primary` when
    // `primary.col` is undefined) pass an unresolved `$...` literal
    // through to this Framework prop bag. The DOM backend silently
    // drops the corresponding CSS rule; mirror that here by stripping
    // *style-shaped* props whose value is a raw `$<id>` literal.
    //
    // Style-shaped means CSS color/size/border/etc. — the props that
    // round-trip through `cssPropToMirrorProp`. Runtime-data bindings
    // (chart `data: '$data'`, route, `visible-when`, named-instance,
    // event handlers, M.each collection refs) intentionally carry
    // `$ref` strings the mirror-runtime resolves at render time and
    // must NOT be stripped.
    const STYLE_PROPS_TO_GUARD = new Set([
      'bg',
      'col',
      'boc',
      'ic',
      'iw',
      'fs',
      'gap',
      'rad',
      'pad',
      'mar',
      'w',
      'h',
      'minw',
      'minh',
      'maxw',
      'maxh',
      'opacity',
      'shadow',
    ])
    const isUnresolvedToken = (v: unknown): v is string =>
      typeof v === 'string' && /^\$[A-Za-z_][\w.-]*$/.test(v)
    for (const k of Object.keys(props)) {
      if (STYLE_PROPS_TO_GUARD.has(k) && isUnresolvedToken(props[k])) {
        delete props[k]
      }
    }
    if (props.states && typeof props.states === 'object') {
      for (const stateName of Object.keys(props.states)) {
        const stateProps = props.states[stateName] as Record<string, unknown>
        if (stateProps && typeof stateProps === 'object') {
          for (const k of Object.keys(stateProps)) {
            if (STYLE_PROPS_TO_GUARD.has(k) && isUnresolvedToken(stateProps[k])) {
              delete stateProps[k]
            }
          }
          if (Object.keys(stateProps).length === 0) {
            delete (props.states as Record<string, unknown>)[stateName]
          }
        }
      }
      if (Object.keys(props.states).length === 0) delete props.states
    }

    return props
  }

  /**
   * Convert IR styles to Mirror props
   */
  private stylesToProps(styles: IRStyle[], props: Record<string, any>): void {
    // Group styles by state
    const baseStyles = styles.filter(s => !s.state)
    const stateStyles = styles.filter(s => s.state)

    // Check for flex: 1 1 0% pattern (used for w full / h full)
    const hasFlexFull = baseStyles.some(
      s => s.property === 'flex' && (s.value === '1 1 0%' || s.value === '1')
    )
    const hasMinWidth0 = baseStyles.some(s => s.property === 'min-width' && s.value === '0')
    const hasMinHeight0 = baseStyles.some(s => s.property === 'min-height' && s.value === '0')

    // Convert flex: 1 1 0% + min-width: 0 to w: 'full'
    if (hasFlexFull && hasMinWidth0) {
      props.w = 'full'
    }
    // Convert flex: 1 1 0% + min-height: 0 to h: 'full'
    if (hasFlexFull && hasMinHeight0) {
      props.h = 'full'
    }

    // Slice 6 V-3: pre-detect grid-column-end / grid-row-end so we can
    // suppress their `width: 100%` / `height: 100%` companions emitted by
    // the IR property-transformer (`property-transformer.ts:436, 451`).
    // Without this, the per-style mapper writes `w: 'full'` from `width:
    // 100%` AFTER our `grid-column-end: span N → w: N` mapping, so the
    // span-count gets clobbered. Mark companions for skip in the loop
    // below.
    const hasGridColSpan = baseStyles.some(
      s => s.property === 'grid-column-end' && /^span\s+(\d+|var\(--[^)]+\))$/.test(s.value)
    )
    const hasGridRowSpan = baseStyles.some(
      s => s.property === 'grid-row-end' && /^span\s+(\d+|var\(--[^)]+\))$/.test(s.value)
    )

    // Slice 4 V-2: detect 9-zone combination BEFORE the per-style loop
    // and emit the alias instead of two individual `justify-content` /
    // `align-items` mappings. Without this the per-style mapper either
    // dropped `flex-start`/`flex-end` entirely (→ `(no props)` for `tl`/
    // `tr`/`bl`/`br`) or collapsed any `center` axis to a bare
    // `center: true` (→ ambiguous for `tc`/`cl`/`cr`/`bc`).
    const justify = baseStyles.find(s => s.property === 'justify-content')?.value
    const align = baseStyles.find(s => s.property === 'align-items')?.value
    const direction =
      baseStyles.find(s => s.property === 'flex-direction')?.value === 'row' ? 'row' : 'column'
    const consumedAlignmentStyles = new Set<string>()
    if (justify && align && justify !== 'space-between') {
      const zone = flexToNineZone(justify, align, direction)
      if (zone) {
        props[zone] = true
        consumedAlignmentStyles.add('justify-content')
        consumedAlignmentStyles.add('align-items')
      }
    }
    // Slice 5 V-4: single-axis center detection. Fires when EXACTLY ONE
    // axis is `center` AND the other is unset — that's the unique IR
    // signature of `hor-center` / `ver-center` (the orthogonal axis is
    // omitted entirely, vs. `tc`/`cl`/etc. which set both). Without this
    // the per-style fallback collapses single `justify:center` /
    // `align:center` to a bare `center: true`, which compiles to BOTH
    // axes — round-trip-lossy.
    if (!consumedAlignmentStyles.has('justify-content') && justify === 'center' && !align) {
      const keyword = flexToSingleAxisCenter('justify-content', direction)
      if (keyword) {
        props[keyword] = true
        consumedAlignmentStyles.add('justify-content')
      }
    }
    if (!consumedAlignmentStyles.has('align-items') && align === 'center' && !justify) {
      const keyword = flexToSingleAxisCenter('align-items', direction)
      if (keyword) {
        props[keyword] = true
        consumedAlignmentStyles.add('align-items')
      }
    }

    // `align top|bottom|left|right` reverse mapping. The IR's layout-
    // transformer collapses these to a single-axis flex value
    // (`align-items: flex-end`, `justify-content: flex-start`, etc.)
    // depending on direction. Pre-2026-05-10 the Framework reverse-
    // mapper had no branch — single-axis flex-start/flex-end values
    // dropped as "default" or were collapsed to nothing. Now we map
    // them back to `align <value>` strings the Mirror parser accepts.
    //
    // direction=row:
    //   align-items: flex-start  → `align top`
    //   align-items: flex-end    → `align bottom`
    //   justify-content: flex-end → `align right`
    //   (justify-content: flex-start is the default — drop)
    // direction=column:
    //   align-items: flex-end    → `align right`
    //   align-items: flex-start  → drop (default)
    //   justify-content: flex-start → `align top`
    //   justify-content: flex-end   → `align bottom`
    if (!consumedAlignmentStyles.has('align-items') && align && align !== 'center') {
      let keyword: string | null = null
      if (direction === 'row') {
        if (align === 'flex-end') keyword = 'bottom'
        // align-items: flex-start is the default; round-trip from
        // explicit `align top` would need provenance the IR doesn't
        // carry. Skip to avoid emitting noisy `align: 'top'` on every
        // default-aligned row.
      } else {
        if (align === 'flex-end') keyword = 'right'
      }
      if (keyword) {
        props.align = keyword
        consumedAlignmentStyles.add('align-items')
      }
    }
    if (
      !consumedAlignmentStyles.has('justify-content') &&
      justify &&
      justify !== 'center' &&
      justify !== 'space-between'
    ) {
      let keyword: string | null = null
      if (direction === 'row') {
        if (justify === 'flex-end') keyword = 'right'
      } else {
        if (justify === 'flex-end') keyword = 'bottom'
        if (justify === 'flex-start') keyword = 'top'
      }
      if (keyword) {
        props.align = keyword
        consumedAlignmentStyles.add('justify-content')
      }
    }

    // Convert base styles to props
    for (const style of baseStyles) {
      // Skip flex and min-width/min-height that were handled above
      if (
        hasFlexFull &&
        hasMinWidth0 &&
        (style.property === 'flex' || style.property === 'min-width')
      )
        continue
      if (
        hasFlexFull &&
        hasMinHeight0 &&
        (style.property === 'flex' || style.property === 'min-height')
      )
        continue

      // Slice 4 V-2: skip the alignment styles already consumed by the
      // 9-zone alias above so we don't double-emit `tl: true` plus a
      // bare `center: true`.
      if (consumedAlignmentStyles.has(style.property)) continue

      // Slice 6 V-3: skip width: 100% / height: 100% companions of grid-
      // span — the `grid-column-end`/`grid-row-end` mapping below already
      // emits `w: N` / `h: N`, the 100% would clobber that.
      if (hasGridColSpan && style.property === 'width' && style.value === '100%') continue
      if (hasGridRowSpan && style.property === 'height' && style.value === '100%') continue

      const mirrorProp = this.cssPropToMirrorProp(style.property, style.value)
      if (mirrorProp) {
        props[mirrorProp.name] = mirrorProp.value
      }
    }

    // Convert state styles to states object
    if (stateStyles.length > 0) {
      const states: Record<string, Record<string, any>> = {}

      for (const style of stateStyles) {
        if (!states[style.state!]) {
          states[style.state!] = {}
        }
        const mirrorProp = this.cssPropToMirrorProp(style.property, style.value)
        if (mirrorProp) {
          states[style.state!][mirrorProp.name] = mirrorProp.value
        }
      }

      props.states = states
    }
  }

  /**
   * Map CSS property/value back to Mirror property
   */
  private cssPropToMirrorProp(
    prop: string,
    value: string
  ): { name: string; value: string | number | boolean } | null {
    // Layout
    if (prop === 'display' && value === 'flex') return null // Implicit
    if (prop === 'flex-direction' && value === 'row') return { name: 'hor', value: true }
    if (prop === 'flex-direction' && value === 'column') return null // Default
    if (prop === 'gap') return { name: 'gap', value: this.parsePxValue(value) }
    // Slice 2 V-5: gap-x → column-gap, gap-y → row-gap (Aliases gx/gy
    // map to the same CSS in the IR layout-transformer). Without these
    // branches, Framework export silently dropped both axes.
    if (prop === 'column-gap') return { name: 'gap-x', value: this.parsePxValue(value) }
    if (prop === 'row-gap') return { name: 'gap-y', value: this.parsePxValue(value) }
    if (prop === 'justify-content' && value === 'space-between')
      return { name: 'spread', value: true }
    if (prop === 'flex-wrap' && value === 'wrap') return { name: 'wrap', value: true }

    // Alignment
    if (prop === 'justify-content' && value === 'center') return { name: 'center', value: true }
    if (prop === 'align-items' && value === 'center') return { name: 'center', value: true }
    // Cross-axis baseline alignment for mixed-size text rows.
    // Pre-2026-05-10 dropped silently from Framework export.
    if (prop === 'align-items' && value === 'baseline') {
      return { name: 'ver-baseline', value: true }
    }

    // Sizing
    if (prop === 'width') {
      if (value === '100%') return { name: 'w', value: 'full' }
      if (value === 'fit-content') return { name: 'w', value: 'hug' }
      return { name: 'w', value: this.parsePxValue(value) }
    }
    if (prop === 'height') {
      if (value === '100%') return { name: 'h', value: 'full' }
      if (value === 'fit-content') return { name: 'h', value: 'hug' }
      return { name: 'h', value: this.parsePxValue(value) }
    }
    if (prop === 'min-width') return { name: 'minw', value: this.parsePxValue(value) }
    if (prop === 'max-width') return { name: 'maxw', value: this.parsePxValue(value) }
    if (prop === 'min-height') return { name: 'minh', value: this.parsePxValue(value) }
    if (prop === 'max-height') return { name: 'maxh', value: this.parsePxValue(value) }

    // Spacing
    if (prop === 'padding') return { name: 'pad', value: this.parsePxValue(value) }
    if (prop === 'margin') return { name: 'margin', value: this.parsePxValue(value) }

    // Colors
    if (prop === 'background' || prop === 'background-color') return { name: 'bg', value: value }
    if (prop === 'color') return { name: 'col', value: value }
    if (prop === 'border-color') return { name: 'boc', value: value }

    // Border
    if (prop === 'border') return { name: 'bor', value: value }
    if (prop === 'border-radius') return { name: 'rad', value: this.parsePxValue(value) }

    // Typography
    // Prefer Mirror's short alias (`fs`) over the CSS-name form so the
    // round-tripped M(...) bag uses bare-identifier keys (`fs: 14`)
    // instead of quoted hyphenated keys (`'font-size': 14`).
    if (prop === 'font-size') return { name: 'fs', value: this.parsePxValue(value) }
    if (prop === 'font-weight') {
      // Convert numeric weights back to keywords for readability
      const weightKeywords: Record<string, string> = {
        '100': 'thin',
        '300': 'light',
        '400': 'normal',
        '500': 'medium',
        '600': 'semibold',
        '700': 'bold',
        '900': 'black',
      }
      return { name: 'weight', value: weightKeywords[value] || value }
    }
    if (prop === 'line-height') return { name: 'line', value: value }
    if (prop === 'font-family') return { name: 'font', value: value }
    // Letter-spacing: IR emits `Nem`. Reverse to `tracking N` (the
    // documented Mirror keyword). Pre-2026-05-10 the prop dropped
    // silently from Framework round-trips.
    if (prop === 'letter-spacing') {
      const m = value.match(/^(-?\d+(?:\.\d+)?)em$/)
      if (m) return { name: 'tracking', value: parseFloat(m[1]) }
      return { name: 'tracking', value: value }
    }
    if (prop === 'text-align') return { name: 'text-align', value: value }
    if (prop === 'font-style' && value === 'italic') return { name: 'italic', value: true }
    if (prop === 'text-decoration' && value === 'underline')
      return { name: 'underline', value: true }
    if (prop === 'text-transform' && value === 'uppercase')
      return { name: 'uppercase', value: true }
    if (prop === 'text-transform' && value === 'lowercase')
      return { name: 'lowercase', value: true }

    // Visual
    if (prop === 'opacity') return { name: 'opacity', value: parseFloat(value) }
    if (prop === 'box-shadow') return { name: 'shadow', value: value }
    if (prop === 'cursor') return { name: 'cursor', value: value }
    if (prop === 'z-index') return { name: 'z', value: parseInt(value) }

    // Aspect ratio. The IR's property-transformer maps `aspect square` →
    // `aspect-ratio: 1`, `aspect video` → `aspect-ratio: 16/9`,
    // `aspect <num>` → `aspect-ratio: <num>`. Pre-2026-05-10 the
    // Framework had no reverse mapping and dropped the prop entirely.
    if (prop === 'aspect-ratio') {
      if (value === '1' || value === '1 / 1') return { name: 'aspect', value: 'square' }
      if (value === '16 / 9' || value === '16/9') return { name: 'aspect', value: 'video' }
      // Numeric / arbitrary ratio passes through verbatim.
      return { name: 'aspect', value: value }
    }

    // Filter / backdrop-filter. `blur N` and `backdrop-blur N` are the
    // documented shorthands; the IR emits `filter: blur(Npx)` /
    // `backdrop-filter: blur(Npx)` (plus `-webkit-backdrop-filter` for
    // Safari). Reverse-map both back to the Mirror keyword. The
    // `-webkit-` prefix is dropped since the unprefixed form already
    // round-trips.
    if (prop === '-webkit-backdrop-filter') return null
    if (prop === 'backdrop-filter') {
      const m = value.match(/^blur\((\d+(?:\.\d+)?)px\)$/)
      if (m) return { name: 'backdrop-blur', value: parseFloat(m[1]) }
      return { name: 'backdrop-filter', value: value }
    }
    if (prop === 'filter') {
      const m = value.match(/^blur\((\d+(?:\.\d+)?)px\)$/)
      if (m) return { name: 'blur', value: parseFloat(m[1]) }
      return { name: 'filter', value: value }
    }

    // Scroll
    if (prop === 'overflow-y' && value === 'auto') return { name: 'scroll', value: true }
    if (prop === 'overflow-x' && value === 'auto') return { name: 'scroll-hor', value: true }
    if (prop === 'overflow' && value === 'hidden') return { name: 'clip', value: true }

    // Display
    if (prop === 'display' && value === 'none') return { name: 'hidden', value: true }
    if (prop === 'display' && value === 'grid') return null // Handled separately

    // Grid container
    if (prop === 'grid-template-columns') {
      // Parse repeat(N, 1fr) -> grid N
      const match = value.match(/repeat\((\d+), 1fr\)/)
      if (match) return { name: 'grid', value: parseInt(match[1]) }
      return { name: 'grid', value: value }
    }
    if (prop === 'grid-auto-rows') return { name: 'row-height', value: this.parsePxValue(value) }
    if (prop === 'grid-auto-flow' && value === 'dense') return { name: 'dense', value: true }
    // Slice 6 V-3: grid-child positioning. Reverse-mapping for `x N`/`y N`/
    // `w N`/`h N` in grid-parent context. The `width: 100%` / `height: 100%`
    // companions emitted alongside `grid-column-end: span N` are dropped
    // (they're a DOM-only artefact — Mirror DSL has just `w N`).
    // Slice 7 V-1: token-resolved values arrive as `var(--name-x)` strings.
    // Pass them through verbatim — the M-runtime resolves CSS-vars at render
    // time. Without this branch `parseInt('var(...)') = NaN` clobbered the
    // round-trip.
    if (prop === 'grid-column-start') {
      return { name: 'x', value: value.startsWith('var(') ? value : parseInt(value) }
    }
    if (prop === 'grid-row-start') {
      return { name: 'y', value: value.startsWith('var(') ? value : parseInt(value) }
    }
    if (prop === 'grid-column-end') {
      const m = value.match(/^span\s+(\d+)$/)
      if (m) return { name: 'w', value: parseInt(m[1]) }
      const v = value.match(/^span\s+(var\(--[^)]+\))$/)
      if (v) return { name: 'w', value: v[1] }
      return null
    }
    if (prop === 'grid-row-end') {
      const m = value.match(/^span\s+(\d+)$/)
      if (m) return { name: 'h', value: parseInt(m[1]) }
      const v = value.match(/^span\s+(var\(--[^)]+\))$/)
      if (v) return { name: 'h', value: v[1] }
      return null
    }

    // Slice 6 V-2 / non-grid: `position: absolute` from `x`/`y` outside grid.
    // The IR emits `position: absolute` plus `left: Npx` / `top: Npx`. The
    // Framework reverse-mapper currently has no `position` branch, so we
    // map `left`/`top` directly back to `x`/`y` and drop the `position:
    // absolute` hint (Mirror's `x`/`y` implies absolute positioning).
    if (prop === 'position' && value === 'absolute') return null
    if (prop === 'position' && value === 'fixed') return { name: 'fixed', value: true }
    if (prop === 'position' && value === 'relative') return { name: 'relative', value: true }
    if (prop === 'left') return { name: 'x', value: this.parsePxValue(value) }
    if (prop === 'top') return { name: 'y', value: this.parsePxValue(value) }

    // Transforms — `rotate Ndeg` and `scale N` produce a `transform:`
    // string. Pre-2026-05-10 there was no reverse mapping so both
    // dropped from Framework export entirely.
    if (prop === 'transform') {
      const r = value.match(/^rotate\((-?\d+(?:\.\d+)?)deg\)$/)
      if (r) return { name: 'rotate', value: parseFloat(r[1]) }
      const s = value.match(/^scale\((-?\d+(?:\.\d+)?)\)$/)
      if (s) return { name: 'scale', value: parseFloat(s[1]) }
      // Combined transforms (`rotate(45deg) scale(1.2)`) round-trip as a
      // raw `transform:` string; users who wrote the shorthand get
      // separate properties anyway.
      return { name: 'transform', value: value }
    }

    // Directional borders — `bor-l N` / `bor-r N` / `bor-t N` / `bor-b N`.
    // The IR emits `border-left: Npx solid currentColor`. Pre-fix all
    // four directionals dropped silently from Framework export.
    if (
      prop === 'border-left' ||
      prop === 'border-right' ||
      prop === 'border-top' ||
      prop === 'border-bottom'
    ) {
      const m = value.match(/^(\d+)px\s+solid/)
      const dir =
        prop === 'border-left'
          ? 'l'
          : prop === 'border-right'
            ? 'r'
            : prop === 'border-top'
              ? 't'
              : 'b'
      if (m) return { name: `bor-${dir}`, value: parseInt(m[1]) }
      return { name: `bor-${dir}`, value: value }
    }

    // `bor 0 0 1 0` produces `border-style: solid` + `border-width: 0 0 1px 0`.
    // Round-trip the multi-value form back into a `bor` shorthand.
    // `border-style: solid` alone is implicit when border-width is set —
    // drop it to avoid a stray `bor-style: 'solid'` in the M(...) bag.
    if (prop === 'border-style' && value === 'solid') return null
    if (prop === 'border-width') {
      const parts = value.trim().split(/\s+/)
      if (parts.length === 4) {
        const nums = parts.map(p => p.match(/^(\d+)px?$/)?.[1] ?? p)
        return { name: 'bor', value: nums.join(' ') }
      }
      const m = value.match(/^(\d+)px$/)
      if (m) return { name: 'bor', value: parseInt(m[1]) }
      return { name: 'bor', value: value }
    }

    // Flex shorthand - handled in stylesToProps for w full / h full detection
    if (prop === 'flex') return null

    // Flex grow (often combined with width: 100%)
    if (prop === 'flex-grow') return null // Implicit with w full

    // Animations: reverse `mirror-spin 1s linear infinite` → `anim spin`.
    // The IR property-transformer expanded `anim X` to a full CSS shorthand
    // via the shared `ANIMATION_SHORTHAND` map; we reverse-look-up so the
    // M(...) descriptor carries the original keyword (the runtime applies
    // its own `@keyframes mirror-X` rule). Unknown strings pass through —
    // authors can supply a custom `animation: …` value and have it
    // round-trip verbatim.
    if (prop === 'animation') {
      const keyword = ANIMATION_REVERSE[value]
      if (keyword) return { name: 'anim', value: keyword }
      return { name: 'anim', value }
    }

    return null
  }

  /**
   * Convert IR events to Mirror props
   */
  private eventsToProps(events: IREvent[], props: Record<string, any>): void {
    for (const event of events) {
      const actions = event.actions.map(a => this.actionToString(a))
      const actionValue = actions.length === 1 ? actions[0] : actions

      if (event.key) {
        // Keyboard event: 'onkeydown escape': 'close'
        props[`onkeydown ${event.key}`] = actionValue
      } else {
        // Regular event: onclick: 'toggle'
        const eventName = `on${event.name}`
        props[eventName] = actionValue
      }
    }
  }

  /**
   * Convert IR action to action string
   */
  private actionToString(action: IRAction): string {
    if (action.target) {
      return `${action.type} ${action.target}`
    }
    return action.type
  }

  /**
   * Convert props object to string
   */
  private propsToString(props: Record<string, any>): string {
    const entries = Object.entries(props)
    if (entries.length === 0) return ''

    const parts: string[] = []

    // Quote any key that isn't a valid bare JS identifier. Without this,
    // CSS-style hyphenated keys like `font-size` become illegal JS:
    //   `M('X', { font-size: 0 })` ← SyntaxError on the hyphen.
    const isValidIdent = (k: string) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k)
    const fmtKey = (k: string) => (isValidIdent(k) ? k : `'${k}'`)

    for (const [key, value] of entries) {
      const k = fmtKey(key)
      if (key === 'states') {
        // States need special formatting
        parts.push(`states: ${this.statesToString(value)}`)
      } else if (typeof value === 'string') {
        parts.push(`${k}: '${value}'`)
      } else if (typeof value === 'boolean') {
        parts.push(`${k}: ${value}`)
      } else if (typeof value === 'number') {
        parts.push(`${k}: ${value}`)
      } else if (Array.isArray(value)) {
        const arrayStr = value.map(v => (typeof v === 'string' ? `'${v}'` : v)).join(', ')
        parts.push(`${k}: [${arrayStr}]`)
      } else {
        parts.push(`${k}: ${JSON.stringify(value)}`)
      }
    }

    return `{ ${parts.join(', ')} }`
  }

  /**
   * Convert states object to string
   */
  private statesToString(states: Record<string, Record<string, any>>): string {
    const parts = Object.entries(states).map(([stateName, stateProps]) => {
      const propParts = Object.entries(stateProps).map(([key, value]) =>
        typeof value === 'string' ? `${key}: '${value}'` : `${key}: ${value}`
      )
      return `${stateName}: { ${propParts.join(', ')} }`
    })
    return `{ ${parts.join(', ')} }`
  }

  /**
   * Parse px values to numbers. Pass-through for CSS-vars (`var(--sp-gap)`)
   * and other already-CSS-shaped values — without that guard the value
   * occasionally got truncated by downstream string handling. Slice 2 V-3.
   *
   * Multi-value shorthand (`12px 8px`) is preserved as the original CSS
   * string — the M-runtime accepts space-separated values directly. Slice 2 V-7.
   *
   * Decimals (`12.5px`) preserved via parseFloat instead of parseInt — the
   * old `parseInt` truncated `12.5` to `12`. Slice 2 V-9.
   */
  private parsePxValue(value: string): string | number {
    if (value.startsWith('var(')) return value
    // Multi-value shorthand: keep as CSS string — the M-runtime understands
    // `gap: '12px 8px'` literally, no need to convert to a single number.
    if (/\s/.test(value.trim())) return value
    if (value.endsWith('px')) {
      const num = parseFloat(value)
      if (!isNaN(num)) return num
    }
    // Bare numeric strings (e.g. `'0'` from `left: 0` in stacked-overlay
    // children) — round-trip back to a number so the M(...) bag stays
    // numeric-typed and re-compile produces the same IR. Pre-2026-05-10
    // these emitted as quoted strings (`x: '0'` in M-prop bag).
    if (/^-?\d+(\.\d+)?$/.test(value.trim())) {
      return parseFloat(value)
    }
    return value
  }

  private escapeString(s: string): string {
    return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
  }

  private currentIndent(): string {
    return '  '.repeat(this.indent)
  }

  private indentLines(text: string): string {
    const indent = '  '.repeat(this.indent + 1)
    return text
      .split('\n')
      .map(line => indent + line)
      .join('\n')
  }
}
