/**
 * Mirror Framework Backend
 *
 * Generates M() function calls that use the Mirror Runtime.
 * Output is idiomatic JavaScript that mirrors Mirror DSL 1:1.
 *
 * This backend enables:
 * 1. LLM-generated code that's identical to compiler output
 * 2. Deterministic reverse translation via M.toMirror()
 * 3. Smaller bundle size (runtime is separate)
 */

import type { AST } from '../parser/ast'
import { toIR } from '../ir'
import type { IR } from '../ir/types'
import { dataValueToJS } from './framework/ops/helpers'
import { nodeToM } from './framework/ops/node-emit'

/**
 * Generate M() framework calls from Mirror AST
 *
 * @example Output:
 * ```javascript
 * import { M } from 'mirror-runtime'
 *
 * export const ui = M('Box', { bg: '#1a1a23', pad: 16 }, [
 *   M('Text', 'Hello', { weight: 'bold' })
 * ])
 *
 * export function mount(container) {
 *   return M.render(ui, container)
 * }
 * ```
 */
export function generateFramework(ast: AST): string {
  const ir = toIR(ast)
  const generator = new FrameworkGenerator(ir)
  return generator.generate()
}

class FrameworkGenerator {
  private ir: IR
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR) {
    this.ir = ir
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitCustomIcons()
    this.emitComponents()
    this.emitUI()
    this.emitMount()

    return this.lines.join('\n')
  }

  /**
   * Slice 51 V-2: emit `M.registerIcon(...)` calls for `$icons:` entries.
   * Pre-Slice-51 the Framework backend silently dropped Custom-Icons —
   * `Icon "myicon"` would compile to `M('Icon', 'myicon', { is: '24' })`
   * which the runtime tried to fetch from Lucide-CDN (404). The mirror-
   * runtime package exposes `M.registerIcon` (re-exported from
   * `compiler/runtime/icons.ts`), so emitting registration calls here
   * gives Framework targets the same custom-icon pipeline as DOM.
   */
  private emitCustomIcons(): void {
    if (!this.ir.icons || this.ir.icons.length === 0) return
    this.emit('// Custom Icons')
    for (const icon of this.ir.icons) {
      const viewBox = icon.viewBox || '0 0 24 24'
      const escapedPath = icon.path.replace(/"/g, '\\"')
      this.emit(`M.registerIcon('${icon.name}', "${escapedPath}", '${viewBox}')`)
    }
    this.emit('')
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (Framework Backend)')
    this.emit('// This code uses the Mirror Runtime for rendering')
    this.emit('')
    this.emit("import { M } from 'mirror-runtime'")
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    // Drop property-sets (no `value`, no `data`) — they're expanded inline
    // at the IR layer, so emitting `'cardstyle': undefined` is just noise.
    const valueTokens = this.ir.tokens.filter(t => t.value !== undefined || t.data !== undefined)
    if (valueTokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('export const tokens = {')
    this.indent++
    for (const token of valueTokens) {
      // Nested data objects (`tasks: { t1: {...}, t2: {...} }`) and bare-list
      // forms (`colors: [red, blue]`) need a real JS literal — without it the
      // runtime can't iterate them via `each task in $tasks` / `$colors.count`.
      if (token.data !== undefined) {
        this.emit(`'${token.name}': ${dataValueToJS(token.data)},`)
        continue
      }
      const value = typeof token.value === 'string' ? `'${token.value}'` : token.value
      this.emit(`'${token.name}': ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitComponents(): void {
    // Component definitions would be extracted from AST
    // For now, we skip this as components are resolved during IR transformation
  }

  private emitUI(): void {
    this.emit('// UI Tree')

    if (this.ir.nodes.length === 1) {
      // Single root node
      this.emit('export const ui = ' + nodeToM(this.ir.nodes[0], this.indent))
    } else if (this.ir.nodes.length > 1) {
      // Multiple root nodes - wrap in Box
      this.emit("export const ui = M('Box', [")
      this.indent++
      for (let i = 0; i < this.ir.nodes.length; i++) {
        const comma = i < this.ir.nodes.length - 1 ? ',' : ''
        this.emit(nodeToM(this.ir.nodes[i], this.indent) + comma)
      }
      this.indent--
      this.emit('])')
    } else {
      this.emit("export const ui = M('Box')")
    }

    this.emit('')
  }

  private emitMount(): void {
    this.emit('/**')
    this.emit(' * Mount UI to a container element')
    this.emit(' * @param {HTMLElement} container - The container to mount to')
    this.emit(' * @returns {MirrorUI} - UI controller with get() method')
    this.emit(' */')
    this.emit('export function mount(container) {')
    this.indent++
    this.emit('return M.render(ui, container)')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// For reverse translation to Mirror DSL:')
    this.emit('// console.log(M.toMirror(ui))')
  }
}
