/**
 * Mirror Framework Backend
 *
 * Generates M() function calls that use the Mirror Runtime.
 * Output is idiomatic JavaScript that mirrors Mirror DSL 1:1.
 *
 * This backend enables:
 * 1. LLM-generated code that's identical to compiler output
 * 2. Deterministic reverse translation via M.toMirror()
 * 3. Smaller bundle size (runtime is separate)
 */

import type { AST } from '../parser/ast'
import { toIR } from '../ir'
import type { IR, IRNode, IREach, IRConditional } from '../ir/types'
import { isLayoutPrimitive } from '../schema/dsl'
import { TAG_TO_TYPE, dataValueToJS, escapeString } from './framework/ops/helpers'
import { eventsToProps, stylesToProps } from './framework/ops/style-event'

/**
 * Generate M() framework calls from Mirror AST
 *
 * @example Output:
 * ```javascript
 * import { M } from 'mirror-runtime'
 *
 * export const ui = M('Box', { bg: '#1a1a23', pad: 16 }, [
 *   M('Text', 'Hello', { weight: 'bold' })
 * ])
 *
 * export function mount(container) {
 *   return M.render(ui, container)
 * }
 * ```
 */
export function generateFramework(ast: AST): string {
  const ir = toIR(ast)
  const generator = new FrameworkGenerator(ir)
  return generator.generate()
}

class FrameworkGenerator {
  private ir: IR
  private indent = 0
  private lines: string[] = []

  constructor(ir: IR) {
    this.ir = ir
  }

  generate(): string {
    this.emitHeader()
    this.emitTokens()
    this.emitCustomIcons()
    this.emitComponents()
    this.emitUI()
    this.emitMount()

    return this.lines.join('\n')
  }

  /**
   * Slice 51 V-2: emit `M.registerIcon(...)` calls for `$icons:` entries.
   * Pre-Slice-51 the Framework backend silently dropped Custom-Icons —
   * `Icon "myicon"` would compile to `M('Icon', 'myicon', { is: '24' })`
   * which the runtime tried to fetch from Lucide-CDN (404). The mirror-
   * runtime package exposes `M.registerIcon` (re-exported from
   * `compiler/runtime/icons.ts`), so emitting registration calls here
   * gives Framework targets the same custom-icon pipeline as DOM.
   */
  private emitCustomIcons(): void {
    if (!this.ir.icons || this.ir.icons.length === 0) return
    this.emit('// Custom Icons')
    for (const icon of this.ir.icons) {
      const viewBox = icon.viewBox || '0 0 24 24'
      const escapedPath = icon.path.replace(/"/g, '\\"')
      this.emit(`M.registerIcon('${icon.name}', "${escapedPath}", '${viewBox}')`)
    }
    this.emit('')
  }

  private emit(line: string): void {
    const indentation = '  '.repeat(this.indent)
    this.lines.push(indentation + line)
  }

  private emitHeader(): void {
    this.emit('// Generated by Mirror Compiler (Framework Backend)')
    this.emit('// This code uses the Mirror Runtime for rendering')
    this.emit('')
    this.emit("import { M } from 'mirror-runtime'")
    this.emit('')
  }

  private emitTokens(): void {
    if (this.ir.tokens.length === 0) return

    // Drop property-sets (no `value`, no `data`) — they're expanded inline
    // at the IR layer, so emitting `'cardstyle': undefined` is just noise.
    const valueTokens = this.ir.tokens.filter(t => t.value !== undefined || t.data !== undefined)
    if (valueTokens.length === 0) return

    this.emit('// Design Tokens')
    this.emit('export const tokens = {')
    this.indent++
    for (const token of valueTokens) {
      // Nested data objects (`tasks: { t1: {...}, t2: {...} }`) and bare-list
      // forms (`colors: [red, blue]`) need a real JS literal — without it the
      // runtime can't iterate them via `each task in $tasks` / `$colors.count`.
      if (token.data !== undefined) {
        this.emit(`'${token.name}': ${dataValueToJS(token.data)},`)
        continue
      }
      const value = typeof token.value === 'string' ? `'${token.value}'` : token.value
      this.emit(`'${token.name}': ${value},`)
    }
    this.indent--
    this.emit('}')
    this.emit('')
  }

  private emitComponents(): void {
    // Component definitions would be extracted from AST
    // For now, we skip this as components are resolved during IR transformation
  }

  private emitUI(): void {
    this.emit('// UI Tree')

    if (this.ir.nodes.length === 1) {
      // Single root node
      this.emit('export const ui = ' + this.nodeToM(this.ir.nodes[0]))
    } else if (this.ir.nodes.length > 1) {
      // Multiple root nodes - wrap in Box
      this.emit("export const ui = M('Box', [")
      this.indent++
      for (let i = 0; i < this.ir.nodes.length; i++) {
        const comma = i < this.ir.nodes.length - 1 ? ',' : ''
        this.emit(this.nodeToM(this.ir.nodes[i]) + comma)
      }
      this.indent--
      this.emit('])')
    } else {
      this.emit("export const ui = M('Box')")
    }

    this.emit('')
  }

  private emitMount(): void {
    this.emit('/**')
    this.emit(' * Mount UI to a container element')
    this.emit(' * @param {HTMLElement} container - The container to mount to')
    this.emit(' * @returns {MirrorUI} - UI controller with get() method')
    this.emit(' */')
    this.emit('export function mount(container) {')
    this.indent++
    this.emit('return M.render(ui, container)')
    this.indent--
    this.emit('}')
    this.emit('')
    this.emit('// For reverse translation to Mirror DSL:')
    this.emit('// console.log(M.toMirror(ui))')
  }

  /**
   * Convert IR node to M() call string
   */
  private nodeToM(node: IRNode): string {
    // Handle each loop
    if (node.each) {
      return this.eachToM(node.each)
    }

    // Handle conditional
    if (node.conditional) {
      return this.conditionalToM(node.conditional)
    }

    const parts: string[] = []

    // Type
    const type = this.getNodeType(node)
    parts.push(`'${type}'`)

    // Content (for Text, Icon, Button, Link)
    const content = this.getContent(node)

    // Props
    const props = this.nodeToProps(node)
    const propsStr = this.propsToString(props)

    // Children
    const children = node.children.map(c => this.nodeToM(c))
    const hasChildren = children.length > 0

    // Build M() call
    if (content && propsStr && hasChildren) {
      // M('Text', 'content', { props }, [children])
      return `M(${parts[0]}, '${escapeString(content)}', ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content && propsStr) {
      // M('Text', 'content', { props })
      return `M(${parts[0]}, '${escapeString(content)}', ${propsStr})`
    } else if (content && hasChildren) {
      // M('Text', 'content', [children])
      return `M(${parts[0]}, '${escapeString(content)}', [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (content) {
      // M('Text', 'content')
      return `M(${parts[0]}, '${escapeString(content)}')`
    } else if (propsStr && hasChildren) {
      // M('Box', { props }, [children])
      return `M(${parts[0]}, ${propsStr}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else if (propsStr) {
      // M('Box', { props })
      return `M(${parts[0]}, ${propsStr})`
    } else if (hasChildren) {
      // M('Box', [children])
      return `M(${parts[0]}, [\n${this.indentLines(children.join(',\n'))}\n${this.currentIndent()}])`
    } else {
      // M('Box')
      return `M(${parts[0]})`
    }
  }

  private eachToM(each: IREach): string {
    const template = each.template.map(n => this.nodeToM(n))
    const templateStr = `[\n${this.indentLines(template.join(',\n'))}\n${this.currentIndent()}]`

    if (each.filter) {
      return `M.each('${each.itemVar}', '${each.collection}', ${templateStr}, '${each.filter}')`
    }
    return `M.each('${each.itemVar}', '${each.collection}', ${templateStr})`
  }

  private conditionalToM(cond: IRConditional): string {
    const thenBranch = cond.then.map(n => this.nodeToM(n))
    const thenStr = `[\n${this.indentLines(thenBranch.join(',\n'))}\n${this.currentIndent()}]`

    if (cond.else && cond.else.length > 0) {
      const elseBranch = cond.else.map(n => this.nodeToM(n))
      const elseStr = `[\n${this.indentLines(elseBranch.join(',\n'))}\n${this.currentIndent()}]`
      return `M.if('${cond.condition}', ${thenStr}, ${elseStr})`
    }

    return `M.if('${cond.condition}', ${thenStr})`
  }

  private getNodeType(node: IRNode): string {
    if (node.name && node.name !== node.tag) return node.name
    if (node.primitive === 'icon') return 'Icon'
    return TAG_TO_TYPE[node.tag] || node.name || 'Box'
  }

  /**
   * Extract content from node (for Text, Icon, Button, Link).
   *
   * Layout primitives (Frame/Box, Spacer/Divider, Table family) don't
   * carry positional text content — Slice 1 W112. Skip the content here
   * so the framework backend doesn't emit `M('Frame', 'hello')` while
   * DOM and React both refuse to render the literal.
   */
  private getContent(node: IRNode): string | null {
    if (node.name && isLayoutPrimitive(node.name)) return null
    const textContent = node.properties.find(p => p.name === 'textContent')
    if (textContent && typeof textContent.value === 'string') {
      return textContent.value
    }
    return null
  }

  /**
   * Convert node styles, events, and properties to props object
   */
  private nodeToProps(node: IRNode): Record<string, any> {
    const props: Record<string, any> = {}

    // Instance name
    if (node.instanceName) {
      props.named = node.instanceName
    }

    // Initial state
    if (node.initialState) {
      props.state = node.initialState
    }

    // Visible when
    if (node.visibleWhen) {
      props['visible-when'] = node.visibleWhen
    }

    // Route
    if (node.route) {
      props.route = node.route
    }

    // Selection
    if (node.selection) {
      props.selection = node.selection
    }

    // Convert IR styles to props
    stylesToProps(node.styles, props)

    // Convert IR events to props
    eventsToProps(node.events, props)

    // Add HTML properties (except textContent which is handled as content)
    for (const prop of node.properties) {
      if (prop.name !== 'textContent') {
        if (
          prop.name === 'placeholder' ||
          prop.name === 'href' ||
          prop.name === 'src' ||
          prop.name === 'type'
        ) {
          props[prop.name] = prop.value
        } else if (prop.name === 'hidden' || prop.name === 'disabled') {
          props[prop.name] = true
        } else if (prop.name.startsWith('data-icon-')) {
          // Convert data-icon-* to icon properties
          const iconProp = prop.name.replace('data-icon-', '')
          if (iconProp === 'size') props.is = prop.value
          else if (iconProp === 'color') props.ic = prop.value
          else if (iconProp === 'weight') props.iw = prop.value
          else if (iconProp === 'fill') props.fill = prop.value === 'true' || prop.value === true
        } else if (
          // Chart-specific properties carry the data binding + render
          // hints (`chartType`, `data`, `fill`, `tension`, `title`,
          // `xLabel`, `yLabel`, `min`/`max`, `step`, `colors`). The
          // Mirror runtime needs them on the M-prop bag to wire up
          // Chart.js. Pre-fix every chart compiled to
          // `M('Line', { w: 350, h: 180 })` with no data — the runtime
          // had nothing to bind.
          node.primitive === 'chart' &&
          (prop.name === 'chartType' ||
            prop.name === 'data' ||
            prop.name === 'fill' ||
            prop.name === 'tension' ||
            prop.name === 'title' ||
            prop.name === 'xLabel' ||
            prop.name === 'yLabel' ||
            prop.name === 'min' ||
            prop.name === 'max' ||
            prop.name === 'step' ||
            prop.name === 'colors')
        ) {
          props[prop.name] = prop.value
        }
      }
    }

    // Slice 50 V-3: Icon-Reverse-Map Suppression. Wenn Icon UND data-icon-*
    // Attribute vorhanden sind, sind die korrespondierenden CSS-Reverses
    // (`width→w`, `height→h`, `color→col`) Doubletten — der User hat
    // ursprünglich `is`/`ic`/`iw`/`fill` geschrieben, nicht beide Wege.
    // Pre-fix emittierte Framework `{ w: 24, h: 24, col: '#f00', is: '24',
    // ic: '#f00' }` — round-trip-lossy weil Re-Compile beide Wege liest.
    if (node.primitive === 'icon') {
      if (props.is !== undefined) {
        delete props.w
        delete props.h
      }
      if (props.ic !== undefined) {
        delete props.col
      }
      if (props.iw !== undefined) {
        // V-4 hat font-weight CSS-Emit unterdrückt — diese Suppression ist
        // defensiv für Pfade die das doch noch durchlassen würden.
        delete props.weight
      }
    }

    // Token-leak guard. Some IR-paths (icon-color `ic $accent`, state-
    // block `selected: { boc: $accent }`, `col $primary` when
    // `primary.col` is undefined) pass an unresolved `$...` literal
    // through to this Framework prop bag. The DOM backend silently
    // drops the corresponding CSS rule; mirror that here by stripping
    // *style-shaped* props whose value is a raw `$<id>` literal.
    //
    // Style-shaped means CSS color/size/border/etc. — the props that
    // round-trip through `cssPropToMirrorProp`. Runtime-data bindings
    // (chart `data: '$data'`, route, `visible-when`, named-instance,
    // event handlers, M.each collection refs) intentionally carry
    // `$ref` strings the mirror-runtime resolves at render time and
    // must NOT be stripped.
    const STYLE_PROPS_TO_GUARD = new Set([
      'bg',
      'col',
      'boc',
      'ic',
      'iw',
      'fs',
      'gap',
      'rad',
      'pad',
      'mar',
      'w',
      'h',
      'minw',
      'minh',
      'maxw',
      'maxh',
      'opacity',
      'shadow',
    ])
    const isUnresolvedToken = (v: unknown): v is string =>
      typeof v === 'string' && /^\$[A-Za-z_][\w.-]*$/.test(v)
    for (const k of Object.keys(props)) {
      if (STYLE_PROPS_TO_GUARD.has(k) && isUnresolvedToken(props[k])) {
        delete props[k]
      }
    }
    if (props.states && typeof props.states === 'object') {
      for (const stateName of Object.keys(props.states)) {
        const stateProps = props.states[stateName] as Record<string, unknown>
        if (stateProps && typeof stateProps === 'object') {
          for (const k of Object.keys(stateProps)) {
            if (STYLE_PROPS_TO_GUARD.has(k) && isUnresolvedToken(stateProps[k])) {
              delete stateProps[k]
            }
          }
          if (Object.keys(stateProps).length === 0) {
            delete (props.states as Record<string, unknown>)[stateName]
          }
        }
      }
      if (Object.keys(props.states).length === 0) delete props.states
    }

    return props
  }

  /**
   * Convert props object to string
   */
  private propsToString(props: Record<string, any>): string {
    const entries = Object.entries(props)
    if (entries.length === 0) return ''

    const parts: string[] = []

    // Quote any key that isn't a valid bare JS identifier. Without this,
    // CSS-style hyphenated keys like `font-size` become illegal JS:
    //   `M('X', { font-size: 0 })` ← SyntaxError on the hyphen.
    const isValidIdent = (k: string) => /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(k)
    const fmtKey = (k: string) => (isValidIdent(k) ? k : `'${k}'`)

    for (const [key, value] of entries) {
      const k = fmtKey(key)
      if (key === 'states') {
        // States need special formatting
        parts.push(`states: ${this.statesToString(value)}`)
      } else if (typeof value === 'string') {
        parts.push(`${k}: '${value}'`)
      } else if (typeof value === 'boolean') {
        parts.push(`${k}: ${value}`)
      } else if (typeof value === 'number') {
        parts.push(`${k}: ${value}`)
      } else if (Array.isArray(value)) {
        const arrayStr = value.map(v => (typeof v === 'string' ? `'${v}'` : v)).join(', ')
        parts.push(`${k}: [${arrayStr}]`)
      } else {
        parts.push(`${k}: ${JSON.stringify(value)}`)
      }
    }

    return `{ ${parts.join(', ')} }`
  }

  /**
   * Convert states object to string
   */
  private statesToString(states: Record<string, Record<string, any>>): string {
    const parts = Object.entries(states).map(([stateName, stateProps]) => {
      const propParts = Object.entries(stateProps).map(([key, value]) =>
        typeof value === 'string' ? `${key}: '${value}'` : `${key}: ${value}`
      )
      return `${stateName}: { ${propParts.join(', ')} }`
    })
    return `{ ${parts.join(', ')} }`
  }

  private currentIndent(): string {
    return '  '.repeat(this.indent)
  }

  private indentLines(text: string): string {
    const indent = '  '.repeat(this.indent + 1)
    return text
      .split('\n')
      .map(line => indent + line)
      .join('\n')
  }
}
