/**
 * DOMGenerator ops — emit-static
 *
 * Extracted from compiler/backends/dom.ts. Functions take `this: DOMGenerator`
 * and are bound on the class via class-field assignment.
 */

import type { AST, JavaScriptBlock, TokenDefinition } from '../../../parser/ast'
import { toIR } from '../../../ir'
import type {
  IR,
  IRCanvas,
  IRNode,
  IRStyle,
  IREvent,
  IRAction,
  IREach,
  IRConditional,
  IRAnimation,
  IRZagNode,
  IRStateMachine,
  IRStateTransition,
  IRItem,
  IRProperty,
  IRSlot,
  IRItemProperty,
} from '../../../ir/types'
import { isIRZagNode } from '../../../ir/types'
import { DOM_RUNTIME_CODE } from '../../dom/runtime-template'
import type { DataFile } from '../../../parser/data-types'
import { dispatchZagEmitter } from '../../dom/zag-emitters'
import type { ZagEmitterContext } from '../../dom/base-emitter-context'
import { escapeJSString, cssPropertyToJS, generateVarName } from '../../dom/utils'
import { ZAG_SLOT_NAMES, type GenerateDOMOptions } from '../../dom/types'
import type { EmitterContext, DeferredWhenWatcher } from '../../dom/base-emitter-context'
import {
  emitStateMachine as emitStateMachineExtracted,
  emitDeferredWhenWatchers,
} from '../../dom/state-machine-emitter'
import type { StateMachineEmitterContext } from '../../dom/state-machine-emitter'
import {
  emitEachLoop as emitEachLoopExtracted,
  emitConditional as emitConditionalExtracted,
} from '../../dom/loop-emitter'
import type { LoopEmitterContext } from '../../dom/loop-emitter'
import {
  emitEventListener as emitEventListenerExtracted,
  emitTemplateEventListener as emitTemplateEventListenerExtracted,
  emitAction as emitActionExtracted,
  mapKeyName,
} from '../../dom/event-emitter'
import type { EventEmitterContext } from '../../dom/event-emitter'
import { emitTokens as emitTokensExtracted } from '../../dom/token-emitter'
import type { TokenEmitterContext } from '../../dom/token-emitter'
import { emitAnimations as emitAnimationsExtracted } from '../../dom/animation-emitter'
import type { AnimationEmitterContext } from '../../dom/animation-emitter'
import {
  emitElementCreation,
  emitProperties,
  emitIconSetup,
  emitSlotSetup,
  emitBaseStyles,
  emitContainerType,
  emitLayoutType,
  emitStateStyles,
  emitVisibleWhen,
  emitSelectionBinding,
  emitBindAttribute,
  emitComponentAttributes,
  emitRouteAttribute,
  emitKeyboardNav,
  emitLoopFocus,
  emitTypeahead,
  emitTriggerText,
  emitMask,
  emitValueBinding,
  emitAbsolutePositioning,
  emitAbsContainerMarker,
  emitAppendToParent,
} from '../../dom/node-emitter'
import type { NodeEmitterContext } from '../../dom/node-emitter'
import {
  collectNamedNodes as collectNamedNodesExtracted,
  emitPublicAPI as emitPublicAPIExtracted,
  emitInitialization as emitInitializationExtracted,
  emitAutoMount as emitAutoMountExtracted,
} from '../../dom/api-emitter'
import type { APIEmitterContext } from '../../dom/api-emitter'
import { emitChartSetup } from '../../dom/chart-emitter'
import type { ChartEmitterContext } from '../../dom/chart-emitter'
import { emitStyles as emitStylesExtracted } from '../../dom/style-emitter'
import type { StyleEmitterContext } from '../../dom/style-emitter'
import type { DOMGenerator } from '../../dom'

export function emitCustomIcons(this: DOMGenerator): void {
  if (!this.ir.icons || this.ir.icons.length === 0) return

  this.emit('')
  this.emit('// Custom Icons')
  for (const icon of this.ir.icons) {
    const viewBox = icon.viewBox || '0 0 24 24'
    // Escape any quotes in the path data
    const escapedPath = icon.path.replace(/"/g, '\\"')
    this.emit(`_runtime.registerIcon('${icon.name}', "${escapedPath}", '${viewBox}')`)
  }
}

export function emitAnimations(this: DOMGenerator): void {
  const ctx = this.createAnimationEmitterContext()
  emitAnimationsExtracted(ctx, this.ir.animations)
}

export function emitHeader(this: DOMGenerator): void {
  this.emit('// Generated by Mirror Compiler (DOM Backend)')
  this.emit('// Do not edit manually')
  this.emit('')
}

export function emitTokens(this: DOMGenerator): void {
  // Delegate to extracted token emitter
  const ctx = this.createTokenEmitterContext()
  emitTokensExtracted(ctx, {
    tokens: this.ir.tokens,
    dataFiles: this.dataFiles,
  })
}

export function emitPublicAPI(this: DOMGenerator): void {
  const ctx = this.createAPIEmitterContext()
  const namedNodes = this.collectNamedNodes(this.ir.nodes)
  emitPublicAPIExtracted(ctx, namedNodes)
}

export function emitRuntime(this: DOMGenerator): void {
  // Emit the pre-built runtime code from separate module
  // This replaces ~778 lines of inline code generation
  this.emitRaw(DOM_RUNTIME_CODE)
  this.emit('')

  // Register tokens in runtime for value functions (increment, decrement, set, reset)
  if (this.ir.tokens.length > 0) {
    this.emit('// Register tokens in runtime')
    for (const token of this.ir.tokens) {
      const tokenKey = (token.name.startsWith('$') ? token.name.slice(1) : token.name).replace(
        /\./g,
        '-'
      )
      // Handle numeric values - check if the string represents a number
      let value: string
      if (typeof token.value === 'number') {
        value = String(token.value)
      } else if (typeof token.value === 'string') {
        // Check if it's a numeric string
        const numVal = Number(token.value)
        if (!isNaN(numVal) && token.value.trim() !== '') {
          value = String(numVal)
        } else {
          // Use JSON.stringify for proper quote escaping. Without this, a
          // user value containing single quotes would break the outer
          // `'...'` wrapping (and could leak as JS via injection).
          value = JSON.stringify(token.value)
        }
      } else {
        value = String(token.value)
      }
      this.emit(`_runtime.registerToken('$${tokenKey}', ${value})`)
    }
    this.emit('')
  }
}
