/**
 * Webpage Direct-Manipulation Demo (full marketing page)
 *
 * Counterpart to webpage-build.ts: builds the SAME marketing page —
 * grid + 4 regions + header brand/nav/CTA + code-pane sidebar +
 * hero content + cards + 4-col footer — but through Studio's
 * direct-manipulation surfaces wherever feasible:
 *
 *   • Grid-cell drag            → drawInGrid       (4 regions)
 *   • Components panel drag     → dropFromPalette  (every primitive)
 *   • Inline editing            → inlineEdit       (every text/button)
 *   • Color picker              → pickColor        (key colors)
 *   • Property panel            → setProperty      (sizes, fs, weight)
 *
 * What stays as `execute`:
 *
 *   • The canvas + Stage shell line (typed once at the start — Mirror
 *     needs an explicit `canvas` directive and Studio has no surface
 *     to set the device preset).
 *   • Region-line layout updates (small 1-line replacements that set
 *     `hor, ver-center, spread, pad …, bor-b 1, boc …` — Studio's
 *     property panel exposes these as toggles/composites that the test
 *     runner's setProperty doesn't drive cleanly).
 *   • The code-pane Sidebar (~150 syntax-coloured spans generated by an
 *     inline tokenizer — too dense to drop one-by-one).
 *
 * The narrative arc is therefore: "draw regions → drop content into
 * them → name the pieces inline → polish a few colours". A user
 * watching this should be able to follow how a Mirror page assembles
 * without ever seeing me type Mirror DSL.
 */

import type { DemoScript } from '../types'
import { paletteHighlight } from '../fragments/palette'

// Mirror brand mark (assets/favicon.svg) base64-encoded — used in the
// Header brand and identical to webpage-build.ts so both demos render
// the same logo.
const LOGO_DATA_URL =
  'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgZmlsbD0ibm9uZSI+PHJlY3QgeD0iNCIgeT0iNCIgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiByeD0iNCIgZmlsbD0iIzIyNzFDMSIvPjxyZWN0IHg9IjEwIiB5PSIxMCIgd2lkdGg9IjE4IiBoZWlnaHQ9IjE4IiByeD0iNCIgZmlsbD0iIzVCQThGNSIvPjwvc3ZnPg=='

/**
 * Helper: emit an `execute` step that rewrites a single Mirror source
 * line in place. Used for region/container layout-prop updates that
 * the property-panel surface doesn't expose as plain inputs.
 */
function rewriteLine(opts: {
  matchPattern: string // RegExp source matching the target line (anchored ^)
  newLine: string
  comment: string
}): { action: 'execute'; comment: string; code: string } {
  return {
    action: 'execute',
    comment: opts.comment,
    code: `
      (() => {
        const e = window.editor;
        if (!e) throw new Error('no editor');
        const src = e.state.doc.toString();
        const re = new RegExp('${opts.matchPattern}', 'm');
        const m = src.match(re);
        if (!m) throw new Error('rewriteLine: no match for ${opts.matchPattern}');
        const startPos = m.index;
        const endPos = startPos + m[0].length;
        e.dispatch({ changes: { from: startPos, to: endPos, insert: ${JSON.stringify(opts.newLine)} } });
      })()
    `,
  }
}

export const demoScript: DemoScript = {
  name: 'Webpage Direct',
  description: 'Marketing-Page über Direktmanipulation: drawInGrid + Palette-Drops + Inline-Edit',
  config: {
    speed: 'normal',
    showKeystrokeOverlay: false,
    customTimings: {
      type: { charMs: 30, variance: 0.2, wordPauseMs: 0, linePauseMs: 80, thoughtPauseMs: 200 },
    },
  },
  steps: [
    // ===================================================================
    // Phase 1: Canvas + Stage Grid (only typed line)
    // ===================================================================
    { action: 'comment', text: 'Phase 1: Canvas + Stage' },
    { action: 'moveTo', target: '.cm-editor' },
    { action: 'click' },
    {
      action: 'type',
      text:
        'canvas desktop, bg #0f0f0f\n' +
        'Frame name Stage, w full, h full, grid 4 8, row-height 80, gap 8, pad 16, bg #1a1a1a',
      pauseAfter: { ' ': 0 },
      expectCode:
        'canvas desktop, bg #0f0f0f\n' +
        'Frame name Stage, w full, h full, grid 4 8, row-height 80, gap 8, pad 16, bg #1a1a1a',
    },
    {
      action: 'execute',
      comment: 'dismiss editor color picker (opened by hex literals)',
      code: 'window.hideColorPicker && window.hideColorPicker(); window.hideGlobalColorPicker && window.hideGlobalColorPicker()',
    },
    { action: 'wait', duration: 400 },

    // ===================================================================
    // Phase 2-5: Regionen über Grid-Cell-Drags aufziehen
    // ===================================================================
    { action: 'comment', text: 'Phase 2-5: 4 Regionen ins Grid zeichnen' },
    {
      action: 'drawInGrid',
      component: 'Frame',
      target: { byPath: 'Stage' },
      from: { x: 1, y: 1 },
      to: { x: 4, y: 1 },
      name: 'Header',
      comment: 'Header 4×1',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'drawInGrid',
      component: 'Frame',
      target: { byPath: 'Stage' },
      from: { x: 1, y: 2 },
      to: { x: 1, y: 7 },
      name: 'Sidebar',
      comment: 'Sidebar 1×6',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'drawInGrid',
      component: 'Frame',
      target: { byPath: 'Stage' },
      from: { x: 2, y: 2 },
      to: { x: 4, y: 7 },
      name: 'Content',
      comment: 'Content 3×6',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'drawInGrid',
      component: 'Frame',
      target: { byPath: 'Stage' },
      from: { x: 1, y: 8 },
      to: { x: 4, y: 8 },
      name: 'Footer',
      comment: 'Footer 4×1',
    },
    { action: 'wait', duration: 600 },
    {
      action: 'expectDom',
      comment: 'Stage hat 4 benannte Regionen',
      checks: [
        { selector: { byPath: 'Stage' }, childCount: 4 },
        { selector: { byPath: 'Header' }, tag: 'div' },
        { selector: { byPath: 'Sidebar' }, tag: 'div' },
        { selector: { byPath: 'Content' }, tag: 'div' },
        { selector: { byPath: 'Footer' }, tag: 'div' },
      ],
    },

    // ===================================================================
    // Phase 6: Header — Brand + Nav + CTA per Drops
    // ===================================================================
    { action: 'comment', text: 'Phase 6: Header — Brand + Nav + CTA' },
    // Layout-Update der Header-Region (1-Zeilen-Edit, weil Studio diese
    // Layout-Toggles nicht über setProperty exponiert)
    rewriteLine({
      matchPattern: '^  Frame name Header,[^\\\\n]*$',
      newLine:
        '  Frame name Header, bg #0a0a0a, x 1, y 1, w 4, h 1, hor, ver-center, spread, pad 0 32, bor-b 1, boc #18181b',
      comment: 'Header layout: hor, spread, ver-center, pad, border',
    }),
    { action: 'wait', duration: 500 },

    // --- Brand: Image-Logo + Text "Mirror" ---
    ...paletteHighlight('comp-image'),
    {
      action: 'dropFromPalette',
      component: 'Image',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 0 },
      comment: 'Logo-Image als erstes Header-Kind',
    },
    { action: 'wait', duration: 500 },
    rewriteLine({
      matchPattern: '^    Image[^\\\\n]*$',
      newLine: '    Image src "' + LOGO_DATA_URL + '", w 32, h 32',
      comment: 'Logo: Mirror brand-mark + 32×32',
    }),
    { action: 'wait', duration: 400 },

    // byText: 'Text' would pick up parent Header (textContent inherits
    // from child), so we target the freshly-dropped Text by tag+nth and
    // pivot to byText only after the inline-edit makes it unique.
    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 1 },
      comment: 'Text "Mirror" rechts neben dem Logo',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 0 },
      text: 'Mirror',
      comment: 'Doppelklick → "Mirror"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 0 },
      prop: 'col',
      color: '#ffffff',
      comment: 'Wordmark weiß',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 0 },
      prop: 'fs',
      value: '17',
      comment: 'Wordmark fs 17',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 0 },
      prop: 'weight',
      value: '600',
      comment: 'Wordmark semibold',
    },
    { action: 'wait', duration: 600 },

    // --- Nav: 3 Links ---
    // After the "Mirror" inline-edit, span-nth grows: 0=Mirror, 1=newly dropped.
    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 2 },
      comment: 'Nav-Link "Docs"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 1 },
      text: 'Docs',
      comment: 'Doppelklick → "Docs"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 1 },
      prop: 'col',
      color: '#a1a1aa',
      comment: 'Nav-Link muted',
    },
    { action: 'wait', duration: 500 },

    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 3 },
      comment: 'Nav-Link "Examples"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 2 },
      text: 'Examples',
      comment: 'Doppelklick → "Examples"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 2 },
      prop: 'col',
      color: '#a1a1aa',
      comment: 'Nav-Link muted',
    },
    { action: 'wait', duration: 500 },

    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 4 },
      comment: 'Nav-Link "GitHub"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 3 },
      text: 'GitHub',
      comment: 'Doppelklick → "GitHub"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 3 },
      prop: 'col',
      color: '#a1a1aa',
      comment: 'Nav-Link muted',
    },
    { action: 'wait', duration: 500 },

    // --- CTA Button ---
    ...paletteHighlight('comp-button'),
    {
      action: 'dropFromPalette',
      component: 'Button',
      target: { byPath: 'Header' },
      at: { kind: 'index', index: 5 },
      comment: 'CTA-Button als letztes Header-Kind',
    },
    { action: 'wait', duration: 500 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'button', nth: 0 },
      text: 'Try the editor →',
      comment: 'Doppelklick → CTA-Text',
    },
    { action: 'wait', duration: 600 },
    {
      action: 'expectDom',
      comment: 'Header has logo + Mirror + 3 nav + CTA = 6 children',
      checks: [{ selector: { byPath: 'Header' }, childCount: 6 }],
    },

    // ===================================================================
    // Phase 7: Sidebar — Code-Preview-Pane (tokenizer execute)
    // ===================================================================
    // ~150 colour-coded spans is too dense to drop one-by-one — even
    // showing "drop, edit, color, repeat" 150× would tire any viewer.
    // We keep the inline tokenizer from webpage-build.ts so the same
    // visual lands without bloating the demo.
    { action: 'comment', text: 'Phase 7: Sidebar — Code-Pane (tokenizer)' },
    {
      action: 'execute',
      comment: 'replace Sidebar with syntax-highlighted code pane',
      code: `
        (() => {
          const e = window.editor;
          if (!e) throw new Error('no editor');

          const KW = new Set(['canvas','Frame','Card','Text','Button','Image','Icon','H1','H2','H3','Input','Textarea','Link']);
          const PR = new Set(['bg','col','gap','pad','rad','hor','ver-center','fs','w','h','weight','name','src','line','grow','center','mobile','tablet','desktop','full','hug','rad']);
          const COL = { kw:'#c084fc', pr:'#60a5fa', st:'#34d399', nu:'#fbbf24', cm:'#52525b', bs:'#d4d4d8' };
          const tokenize = (line) => {
            const out = [];
            let i = 0;
            while (i < line.length) {
              const c = line[i];
              if (c === ' ' || c === '\\t') {
                let j = i;
                while (j < line.length && (line[j]===' '||line[j]==='\\t')) j++;
                out.push({ t: line.slice(i,j), c: COL.bs });
                i = j;
              } else if (c === '"') {
                let j = i + 1;
                while (j < line.length && line[j] !== '"') j++;
                const end = j < line.length ? j+1 : j;
                out.push({ t: line.slice(i,end), c: COL.st });
                i = end;
              } else if (c === '#') {
                let j = i + 1;
                while (j < line.length && /[0-9a-fA-F]/.test(line[j])) j++;
                out.push({ t: line.slice(i,j), c: COL.nu });
                i = j;
              } else if (c === '/' && line[i+1] === '/') {
                out.push({ t: line.slice(i), c: COL.cm });
                i = line.length;
              } else if (/[a-zA-Z_$]/.test(c)) {
                let j = i;
                while (j < line.length && /[a-zA-Z0-9_$-]/.test(line[j])) j++;
                const tok = line.slice(i,j);
                const c2 = KW.has(tok) ? COL.kw : (PR.has(tok) ? COL.pr : COL.bs);
                out.push({ t: tok, c: c2 });
                i = j;
              } else if (/[0-9]/.test(c)) {
                let j = i;
                while (j < line.length && /[0-9.]/.test(line[j])) j++;
                out.push({ t: line.slice(i,j), c: COL.nu });
                i = j;
              } else {
                out.push({ t: c, c: COL.bs });
                i++;
              }
            }
            const merged = [];
            for (const tk of out) {
              if (merged.length && merged[merged.length-1].c === tk.c) {
                merged[merged.length-1].t += tk.t;
              } else {
                merged.push({ t: tk.t, c: tk.c });
              }
            }
            return merged;
          };

          const code =
            'canvas mobile, bg #0a0a0a\\n' +
            '\\n' +
            'brand.bg: #2271C1\\n' +
            '\\n' +
            'Card: bg #18181b, rad 12, pad 20\\n' +
            '\\n' +
            'Frame pad 24, gap 16\\n' +
            '  Card\\n' +
            '    Frame hor, gap 12, ver-center\\n' +
            '      Image src "avatar.jpg", w 48, rad 99\\n' +
            '      Frame gap 2\\n' +
            '        Text "Anna Schmid", weight 600\\n' +
            '        Text "Designer", col #a1a1aa\\n' +
            '\\n' +
            '    Frame hor, gap 24\\n' +
            '      Frame\\n' +
            '        Text "127", weight 600\\n' +
            '        Text "Projekte", col #a1a1aa\\n' +
            '      Frame\\n' +
            '        Text "8.4k", weight 600\\n' +
            '        Text "Follower", col #a1a1aa\\n' +
            '\\n' +
            '    Button "Folgen", bg $brand, col white';

          const lines = code.split('\\n');
          const codeLines = [];
          for (const line of lines) {
            if (line === '') {
              codeLines.push('    Frame h 8');
              continue;
            }
            const tks = tokenize(line);
            codeLines.push('    Frame hor, gap 0');
            for (const tk of tks) {
              const safe = tk.t.replace(/\\\\/g, '\\\\\\\\').replace(/"/g, '\\\\"').replace(/ /g, '\\u00A0');
              codeLines.push('      Text "' + safe + '", col ' + tk.c + ', fs 11, font mono');
            }
          }

          const src = e.state.doc.toString();
          const re = new RegExp('^([ \\\\t]*)Frame name Sidebar\\\\b[^\\\\n]*$', 'm');
          const m = src.match(re);
          if (!m) throw new Error('Sidebar line not found');
          const startPos = m.index;
          const baseIndent = m[1].length;
          const lineEnd = startPos + m[0].length;
          let cursor = lineEnd + 1;
          const after = src.slice(lineEnd + 1);
          for (const line of after.split('\\n')) {
            const li = line.match(/^[ \\t]*/)[0].length;
            if (line.trim() !== '' && li <= baseIndent) break;
            cursor += line.length + 1;
            if (cursor - 1 >= src.length) { cursor = src.length + 1; break; }
          }
          const endPos = Math.min(cursor - 1, src.length);

          const header = [
            '  Frame name Sidebar, bg #0d0d10, x 1, y 2, w 1, h 6, gap 0, pad 24 16, bor-r 1, boc #18181b',
            '    Frame pad-b 12, bor-b 1, boc #18181b',
            '      Text "app.mir", col #71717a, fs 12, font mono',
            '    Frame h 12',
          ];
          const newRegion = header.concat(codeLines).join('\\n');
          e.dispatch({ changes: { from: startPos, to: endPos, insert: newRegion } });
        })()
      `,
    },
    { action: 'wait', duration: 1000 },
    {
      action: 'expectDom',
      comment: 'Sidebar gefüllt mit Code-Pane',
      checks: [{ selector: { byPath: 'Sidebar' }, tag: 'div' }],
    },

    // ===================================================================
    // Phase 8: Content — Hero per Direktmanipulation
    // ===================================================================
    // Vereinfachter Hero (eyebrow + H1 + lead + CTA-Button) per Drops
    // und Inline-Edits. Die 3 Feature-Cards (im Code-Demo voll vorhanden)
    // lassen wir hier weg — pro Card wären's 5 Elemente × 5 Style-Steps,
    // 15+ Drops, das überdehnt die Demo.
    { action: 'comment', text: 'Phase 8: Content — Hero per Drops' },
    rewriteLine({
      matchPattern: '^  Frame name Content,[^\\\\n]*$',
      newLine: '  Frame name Content, bg #0a0a0a, x 2, y 2, w 3, h 6, gap 16, pad 64',
      comment: 'Content layout: gap 16, pad 64',
    }),
    { action: 'wait', duration: 500 },

    // Eyebrow
    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Content' },
      at: { kind: 'index', index: 0 },
      comment: 'Eyebrow-Text',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      // After Phase 6 Header has 4 spans (Mirror, Docs, Examples, GitHub).
      // The just-dropped Content text is span nth: 4.
      selector: { byTag: 'span', nth: 4 },
      text: 'Mirror · Designsprache für AI',
      comment: 'Eyebrow-Text',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 4 },
      prop: 'col',
      color: '#2271C1',
      comment: 'Eyebrow-Akzent',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 4 },
      prop: 'fs',
      value: '12',
      comment: 'Eyebrow fs 12',
    },
    { action: 'wait', duration: 600 },

    // H1
    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Content' },
      at: { kind: 'index', index: 1 },
      comment: 'H1-Text',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 5 },
      text: 'Mit AI UIs bauen — und in Kontrolle bleiben.',
      comment: 'H1-Headline',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 5 },
      prop: 'col',
      color: '#ffffff',
      comment: 'H1 weiß',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 5 },
      prop: 'fs',
      value: '40',
      comment: 'H1 fs 40',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 5 },
      prop: 'weight',
      value: '600',
      comment: 'H1 semibold',
    },
    { action: 'wait', duration: 600 },

    // Lead
    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Content' },
      at: { kind: 'index', index: 2 },
      comment: 'Lead-Text',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 6 },
      text: 'Mirror generiert echte Prototypen statt Mockups. AI schreibt den Code, du verfeinerst ihn — ohne Framework-Wissen, ohne Build-Tools.',
      comment: 'Lead-Paragraph',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 6 },
      prop: 'col',
      color: '#a1a1aa',
      comment: 'Lead muted',
    },
    { action: 'wait', duration: 600 },

    // CTA Button
    ...paletteHighlight('comp-button'),
    {
      action: 'dropFromPalette',
      component: 'Button',
      target: { byPath: 'Content' },
      at: { kind: 'index', index: 3 },
      comment: 'CTA-Button',
    },
    { action: 'wait', duration: 500 },
    {
      action: 'inlineEdit',
      // Header has 1 button (Try the editor → CTA at nth:0). Content's
      // CTA is the 2nd button → nth: 1.
      selector: { byTag: 'button', nth: 1 },
      text: 'Try the editor →',
      comment: 'Hero-CTA',
    },
    { action: 'wait', duration: 600 },
    {
      action: 'expectDom',
      comment: 'Content has eyebrow + H1 + lead + CTA = 4 children',
      checks: [{ selector: { byPath: 'Content' }, childCount: 4 }],
    },

    // ===================================================================
    // Phase 9: Footer — Brand + Copyright per Drops
    // ===================================================================
    // Vereinfacht auf 2 Elemente (Brand + ©). Volle 4-Spalten-Komposition
    // ist im Code-Demo zu sehen; hier reicht der Brand-Text als
    // Footer-Stand-in.
    { action: 'comment', text: 'Phase 9: Footer — Brand + Copyright' },
    rewriteLine({
      matchPattern: '^  Frame name Footer,[^\\\\n]*$',
      newLine:
        '  Frame name Footer, bg #0a0a0a, x 1, y 8, w 4, h 1, hor, gap 12, pad 0 32, ver-center, bor-t 1, boc #18181b',
      comment: 'Footer layout',
    }),
    { action: 'wait', duration: 500 },

    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Footer' },
      at: { kind: 'index', index: 0 },
      comment: 'Brand "Mirror"',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      // Content added 3 more spans (eyebrow, H1, lead) → nth: 7 is brand.
      selector: { byTag: 'span', nth: 7 },
      text: 'Mirror',
      comment: 'Footer-Brand',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 7 },
      prop: 'col',
      color: '#ffffff',
      comment: 'Brand weiß',
    },
    { action: 'wait', duration: 300 },
    {
      action: 'setProperty',
      selector: { byTag: 'span', nth: 7 },
      prop: 'weight',
      value: '600',
      comment: 'Brand semibold',
    },
    { action: 'wait', duration: 500 },

    ...paletteHighlight('comp-text'),
    {
      action: 'dropFromPalette',
      component: 'Text',
      target: { byPath: 'Footer' },
      at: { kind: 'index', index: 1 },
      comment: '© Copyright',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'inlineEdit',
      selector: { byTag: 'span', nth: 8 },
      text: '© 2026 — Open Source',
      comment: 'Copyright-Text',
    },
    { action: 'wait', duration: 400 },
    {
      action: 'pickColor',
      selector: { byTag: 'span', nth: 8 },
      prop: 'col',
      color: '#71717a',
      comment: 'Copyright muted',
    },
    { action: 'wait', duration: 600 },
    {
      action: 'expectDom',
      comment: 'Footer has brand + © = 2 children',
      checks: [{ selector: { byPath: 'Footer' }, childCount: 2 }],
    },
  ],
}
